### ISSUE TITLE
在手机浏览规范页面时，正文字体过小

### ISSUE THREAD

**Issue by Hawkeyes0** [w3c/clreq#10]
![wp](https://cloud.githubusercontent.com/assets/2275023/6916592/28a637de-d7d0-11e4-9853-12379b5124fb.jpg)
如图。在 Windows Phone 上列表和Note部分的字号比较适合阅读，其他的字号很小，不方便阅读。

**Comment by upsuper** [comment]
这显然是你浏览器的问题，Android 上 Firefox 和 Chrome 都表现良好。
