### ISSUE TITLE
规范文档未遵循规范描述

### ISSUE THREAD

**Issue by ibelem** [w3c/clreq#100]
步骤：

A. 访问https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode 

> 3.2.2 橫排的中、西文混排配置
> 
> 橫排時，西文使用比例字體；阿拉伯數字則常用比例字體或等寬字體。原則上，漢字與西文字母、數字間使用四分之一個漢字寬的字距或空白。

B. 阅读全部文档

实际结果：
《中文排版需求》规范很多章节未遵循 “漢字與西文字母、數字間使用四分之一個漢字寬的字距或空白。”

例如：

> 或為首字母縮寫時（如GDP）
> 孤行之定義近似於拉丁文字排版中widow的概念

**Comment by realfish** [comment]
See also #14 & #95.
