### ISSUE TITLE
对旧有的破折号、连接号用法加入澄清注解

### ISSUE THREAD

**Issue by Artoria2e5** [w3c/clreq#101]
网络上的破折号、连接号用法很乱，甚至连《[重訂標點符號手冊](http://language.moe.gov.tw/001/Upload/FILES/SITE_CONTENT/M0001/HAU/c2.htm)》网络试用版也有鬼。

## 破折号

《重訂》的破折号是两个 U+2500；我现在看的维基百科破折号条目也是。每天画框身体棒。

Unicode.org 上面以前有过（谢天谢地这玩意丢了）一个 GB2312 码表，用的是 U+2015 当半个破折号。维基百科不出意料地把这个用法列成了绕过 U+2014 断开现象的一个常见做法。（把连接点定义成 U+30FB 的也有这张表的份——不只是 Big5。）

## 连接号

重訂的甲式连接号是 U+2014，在 `e n` 中间整整添了一个 `r`。

维基百科的格式手册不知道怎么找上了个能把破折号 OCR 成 `U+002D U+FF0D U+002D` 的政府网页，结果把甲式连接号搞成了 U+FF0D。估计也有很多人跳坑了。

## 参见

1. 梁海 (2016-11-23). [破折号好难啊！破折号怎么这么难！！](https://zhuanlan.zhihu.com/p/23889364)

**Comment by bobbytung** [comment]
重訂標點符號手冊基本上沒有指定Unicode，我覺得在編輯時就有技術問題。
CLREQ本來不應該涉及實作問題，但是目的上希望推薦標準化的標點符號使用，並且希望實作上能夠處理如U+2014的斷開問題，所以這裡不加註各種替用符號。
