### ISSUE TITLE
刪節號中文的敘述

### ISSUE THREAD

**Issue by RoosterH** [w3c/clreq#116]
刪節號又作省略號，表示節略原文、語句未完或語氣的不連續。為佔二個漢字空間、包含〃六個” 省略點的U+2026 HORIZONTAL ELLIPSIS […

是不是應該為三個？

**Comment by ethantw** [comment]
由於「刪節號」在Unicode中不區分碼位的原因，我們習慣**使用二個`U+2026`來湊成「一個」中文的刪節號**，這屬於一種沒辦法的辦法。

在理想的情況下，（有六個點的）刪節號是一個標點符號，雖然多數漢字字體沒有將這個碼位設計成六個點，但這段描述沒有問題。

**Comment by RoosterH** [comment]
謝謝回答

這是在網頁所寫的
刪節號／省略號為佔二個漢字空間、包含六個省略點的U+2026 HORIZONTAL ELLIPSIS […]（或使用連續二個「……]」）。
第一個是 […] 3 個省略點
第二個才是「……] 6個省略點

是不是應該改為這樣呢？
刪節號／省略號為佔二個漢字空間、包含三個省略點的U+2026 HORIZONTAL ELLIPSIS […]（或使用連續二個有六個省略點「……]」）。

謝謝

**Comment by ethantw** [comment]
我上面的回覆沒有表述清楚，抱歉。

中文的刪節號與西文的ellipsis在Unicode中沒有區別碼位，都是`U+2026`，所以我們平時慣用（西文字體中）二個三點的`U+2026`湊成「一個」中文刪節號，雖然廣泛使用，但並不準確。《需求》認為，在理想的中文語境下使用刪節號時，應使用占二個漢字空間的一個字符。我傾向於修改最後一個括號中的內容。

> 刪節號又作省略號，表示節略原文、語句未完或語氣的不連續。為佔二個漢字空間、包含六個省略點的U+2026 HORIZONTAL ELLIPSIS […]（或使用連續二個三點的U+2026 HORIZONTAL ELLIPSIS […]，作「……」）。

**Comment by RoosterH** [comment]
謝謝解惑！

**Comment by hax** [comment]
个人感觉这样描述反而引起疑惑。

以我的理解，Unicode未有指明U+2026仅限于西文，但并没有说U+2026就直接可作为一个中文省略号。感觉上也不应如此，因为3点和6点视觉差异很大，应被视为两个不同的符号。

我倾向于：
> 刪節號又作省略號，表示節略原文、語句未完或語氣的不連續，佔二個漢字空間、包含六個省略點（通常使用連續二個三點的U+2026 HORIZONTAL ELLIPSIS […]，作「……」）。

**Comment by bobbytung** [comment]
Ellipses are used to indicate an truncation of text, an unfinished sentence or a break in speech. 
Usually use two U+2026 HORIZONTAL ELLIPSIS, making up a middle aligned series of six dots and take up two character widths.

删节号又称省略号，表示节省原文、语句未完或语气的不连续。通常连续使用两个U+2026 HORIZONTAL ELLIPSIS […]，呈现上占两个汉字空间、六个居中省略点。

刪節號又作省略號，表示節略原文、語句未完或語氣的不連續。通常連續使用兩個U+2026 HORIZONTAL ELLIPSIS […]，呈現上佔兩個漢字空間、六個居中省略點。
