### ISSUE TITLE
單雙引號的解釋

### ISSUE THREAD

**Issue by RoosterH** [w3c/clreq#117]
英文的解釋少了一段重要的 - 弯引号用于横排、直角引号用于直排

In the other hand, Simplified Chinese will apply double quotation marks first and then single quotation marks. For Simplified Chinese, double quotation marks include U+201C LEFT DOUBLE QUOTATION MARK [“], U+300E LEFT WHITE CORNER BRACKET [『], U+201D RIGHT DOUBLE QUOTATION MARK [”], U+300F RIGHT WHITE CORNER BRACKET [』]; the single quotation marks include U+2018 LEFT SINGLE QUOTATION MARK [‘], U+300C LEFT CORNER BRACKET [「], U+2019 RIGHT SINGLE QUOTATION MARK [’] and U+300D RIGHT CORNER BRACKET [」].

简体中文采用先双、后单的引号体例，弯引号用于横排、直角引号用于直排。双引号，包含开始双弯引号 U+201C LEFT DOUBLE QUOTATION MARK [“]、开始双直角引号 U+300E LEFT WHITE CORNER BRACKET [『]、结束双弯引号 U+201D RIGHT DOUBLE QUOTATION MARK [”]、 结束双直角引号U+300F RIGHT WHITE CORNER BRACKET [』]；单引号，包含开始单弯引号 U+2018 LEFT SINGLE QUOTATION MARK[‘]、开始单直角引号 U+300C LEFT CORNER BRACKET[「]、 结束单弯引号 U+2019 RIGHT SINGLE QUOTATION MARK [’]、结束单直角引号 U+300D RIGHT CORNER BRACKET [」]。

**Comment by bobbytung** [comment]
加了一段：
On the other hand, Simplified Chinese will apply double quotation marks first, followed by single quotation marks. For Simplified Chinese, double quotation marks include U+201C LEFT DOUBLE QUOTATION MARK [“], U+300E LEFT WHITE CORNER BRACKET [『], U+201D RIGHT DOUBLE QUOTATION MARK [”], U+300F RIGHT WHITE CORNER BRACKET [』]; single quotation marks include U+2018 LEFT SINGLE QUOTATION MARK [‘], U+300C LEFT CORNER BRACKET [「], U+2019 RIGHT SINGLE QUOTATION MARK [’] and U+300D RIGHT CORNER BRACKET [」]. **In horizontal writing, usually using quotation marks. But in vertical writing, use corner brackets instead.**

**Comment by xfq** [comment]
"quotation marks are usually used" seems more natural to me than "usually using quotation marks".
