### ISSUE TITLE
L2/14-006，关于中文标点的 standardized variant

### ISSUE THREAD

**Issue by lianghai** [w3c/clreq#121]
Ken Lunde（小林剣）的 [L2/14-006](http://www.unicode.org/L2/L2014/14006-sv-western-vs-cjk.pdf) 提案在 UTC \#150 上得到了反馈：

> @ken_lunde: Per feedback at #UTC150, I will work with @lianghai on a revised L2/14-006 proposal for #UTC151 in May. Background → http://www.unicode.org/L2/L2014/14006-sv-western-vs-cjk.pdf

https://twitter.com/ken_lunde/status/824702031331938305

请各位提供意见。

---

背景：

- [用 standardized variant 解决中文标点复用西文字符的样式问题可行吗？有过提案吗？](https://www.zhihu.com/question/54261764/answer/141470320)
- [中文标点 standardized variant 的最新进展](https://zhuanlan.zhihu.com/p/25032542)

**Comment by bobbytung** [comment]
已經在CLREQ的會議中討論過，若還有提出Feedback的需求，請 @lianghai reopen此需求。
