### ISSUE TITLE
加入断行算法优先在标点处断行的建议

### ISSUE THREAD

**Issue by Artoria2e5** [w3c/clreq#122]
有些浏览器（例如 Chrome）经常会在可以选择断开在中文字或中文标点处断行时选择在中文字处断行，试举一例：

> https://zh.wikipedia.org/wiki/Special:PermanentLink/42990868
> 
> Chrome 57.0.2987.19 dev, Windows 10
> ![cr-w10](https://cloud.githubusercontent.com/assets/6459309/22492013/68b9c96c-e7f5-11e6-83c2-4624177f9fde.png)

（Firefox、Edge 倒还可以。）

clreq 或许该明确指出应该优先选择标点处断行。

**Comment by realfish** [comment]
断行位置须兼顾标点禁则，请参考 [3.1.4](http://w3c.github.io/clreq/#prohibition_rules_for_line_start_end)。

**Comment by upsuper** [comment]
理论上说中文应该是除了禁则位置以外处处可以断行吧，不存在优先选择的问题。这个看起来更像是浏览器bug，clreq并没有加东西的必要。

**Comment by Artoria2e5** [comment]
嗯，想了想之后跑去 Chrome 写了个 bug 报告（https://crbug.com/687659 ），似乎事情出在顿号没认为能换行上了。有人表示优先选择谁家都没。

**Comment by upsuper** [comment]
其实我觉得问题更有可能是出在`<a>`的边界上没有给换行机会。

**Comment by hax** [comment]
新版chrome（59）已经修复。
