### ISSUE TITLE
Translation fix needed: Extend over not to

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#123]
3.3.4.1 Basic Requirements 基本规则
http://w3c.github.io/clreq/#h-basic-requirements

> 只要不侵犯最小间距，可允许注文伸展到相邻基字上方。
>  Annotations are allowed to extend to the top of adjacent base text as long as the minimum spacing is ensured. 

I believe the english should say "allowed to extend over the top".

**Comment by ethantw** [comment]
Agree.

**Comment by r12a** [comment]
fixed by https://github.com/w3c/clreq/pull/134
