### ISSUE TITLE
正式的中文標題名稱

### ISSUE THREAD

**Issue by ethantw** [w3c/clreq#13]
@lianghai 提到，當前的中文標題「中文排版規範」可能使讀者誤會文件的本來目的。英文標題是「Requirements for Chinese Text Layout」，直譯過來應作「中文排版需求」。而JLReq的日文標題是日本語組版処理の要件，其中「要件」也表示「需求」之意。希望正式名稱改為「中文排版需求」。

**Comment by bobbytung** [comment]
就改成「中文排版需求」。此外，之前也提及「中文」與少數民族語言間的關係，但在W3C文件上，以蒙古文為例，應該也會是Requirements for Mongolian Text Layout。我們就不額外加上「漢字」了。

此外，這份文件在W3C會產生的效用與技術影響，我寫了篇稿件給劉慶刊載在Type is Beautiful上，應能有效說明。

更改後Close。
