### ISSUE TITLE
Position of ruby, text-emphasis, under/overline, etc in vertical-LR writing mode

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#136]
There's a discussion on the TTML2 issue list about what the default position for ruby, text-emphasis, underline and overline should be when vertical text lines are read LTR (ie. not the more usual RTL!) in Chinese or Mongolian.

See https://github.com/w3c/ttml2/issues/240

Unlike CSS, the current TTML spec proposes that text-emphasis would appear by default to the left of the line, as would ruby text. Underlines would appear to the right. If you want different behaviour you'd have to set a property.

What would be the preference for Chinese users?  (The TTML folks would probably like to make a decision on this this week.)

**Comment by r12a** [comment]
Here's some additional background information about how these things are handled by default in the current CSS drafts.

The CSS spec makes a distinction in the Writing Modes spec between `before` and `over`, and between `after` and `under` (i prefer to use the synonyms `line-over`/`line-under` rather than `over`/`under` in this case, since it's less ambiguous) at https://drafts.csswg.org/css-writing-modes-3/#over.  Basically, `before` means to the left of the vertical line when using `vertical-lr`, and to the right when using `vertical-rl`; `line-over` means to the right in either case.

In other words, `line-over` and `line-under` are the opposite of `before` and `after` locations when text is in writing-mode `vertical-lr`, but the same when text is in writing-mode `vertical-rl`.

For CSS `text-emphasis-position` the default is `over right`. The term `over` is used slightly differently here, but the word `right` is the important one for vertical text. The table in that section sets the expectation that in vertical writing modes text-emphasis will appear to the right by default, even where Chinese favours text emphais appearing below the line for horizontal text. See https://drafts.csswg.org/css-text-decor-3/#text-emphasis-position-property

For CSS `text-underline-position` the word `under` has a slightly different meaning again (signifying a position that is unlikely to cut through descenders), and the default value (`auto`) doesn't seem to clearly address the expectation for vertical text defaults.  The example in that section for CJK text implies, however, that CSS expects that, by default, user agents will position underlines to the right for Japanese and Korean, but to the left for Chinese text.  There is no mention of Mongolian.  Overlines appear on the opposite side of the text from the underline. See https://drafts.csswg.org/css-text-decor-3/#text-underline-position-property

For CSS ruby-position in the current draft the default is `line-over` (in the sense defined for writing modes), ie. ruby appears to the right, whether the text is vertical-lr or vertical-rl. See https://drafts.csswg.org/css-ruby-1/#rubypos

(@fantasai @kojiishii please say if i got any of that wrong.)

**Comment by huchunming** [comment]
@r12a, to my experiences, the  text-emphasis should be appear at leftside, (for example, the underline, and dot).  You may refer to example here: http://www.reader8.cn/data/uploadfile/book/uploadfile/201001/20100131052236403.jpg

**Comment by r12a** [comment]
thanks @huchunming. This morning i had a discussion with @bobbytung , @ethantw  and @ryukeikun. Here's a summary of what i took away from the discussion. (Happy to be corrected on any point.) These notes are only about vertical text.

1. For subtitling, no-one has seen vertical-lr, and very little vertical-rl in chinese too.

2. Straight or wavy lines alongside the text are mostly used for things such as book-title or name highlighting, rather than for emphasis like in Latin-script text underlines. Lines alongside vertical text should appear on the opposite side of items such as emphasis marks, ruby, etc (avoids interference), but most felt that lines (straight or wavy) always appear to the left of the vertical line.

3. Emphasis marks (eg. dots) by default appear on the left side, but could be right.

4. Bopomofo ruby always appears on the right side, and pinyin ruby or hanzi ruby normally appear on the right too.

**Comment by huijing** [comment]
I came across this photo of a Japanese book with vertical typesetting and use of ruby. Does Chinese vertical text typeset like this as well?
![Japanese ruby](https://github.com/huijing/filerepo/raw/gh-pages/ruby.jpg)

**Comment by fantasai** [comment]
My understanding of `vertical-lr` typesetting is that within a line, typesetting is exactly as for `vertical-rl`. This makes sense given that Mongolian and Chinese are a relatively common mix historically as well as currently.

It seems this discussion has veered into “what is appropriate for `vertical-rl` Chinese”, however, which is a different topic.

**Comment by xfq** [comment]
Richard's and Elika's comments seem to have answered the question in this issue, so I'll close it.

Feel free to reopen (or propose to reopen) if you have further comments.

**Comment by r12a** [comment]
See https://github.com/w3c/clreq/issues/176 for a follow-on from this discussion.

**Comment by Aalmaho** [comment]
Ok
