### ISSUE TITLE
添加3.5 段落對齊 / Paragraph adjustment rules 

### ISSUE THREAD

**Issue by siusin** [w3c/clreq#15]
https://clreq.hackpad.com/ep/group/oPdU0TktkdM
https://clreq.hackpad.com/3.5-段落調整-C1iqHrZCjPK

**Comment by ethantw** [comment]
「3.5.3 對齊處理」是否直接對應JLReq的3.5.3 Single Line Alignment Processing？若是的話，應改為「單行對齊處理」較妥當。

**Comment by bobbytung** [comment]
不是，請見均等的兩種狀況。

**Comment by ethantw** [comment]
了解，需要在這裡描述縱橫對齊嗎？
