### ISSUE TITLE
Horizontal lines in vertical text

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#151]
2.4.2 Major Differences Between Horizontal and Vertical Writing Modes 
https://w3c.github.io/clreq/#major_differences_between_horizontal_and_vertical_writing_modes
bullet 2, note

[this extract uses updated text by @huijing ]
> When characters need to be composed horizontally, each character will be arranged in a single horizontal line from right to left, and no columns will be applied. Such a layout is considered a special case for vertical writing mode, often seen on stone inscriptions and headings for newspapers and magazines in the past. Now it has largely been replaced by the horizontal writing mode arrangement from left to right.

I think this text makes it sound like this is the normal approach for handling horizontal lines in vertically set environments, because it only mentions that it's a special case halfway through.  I suggest a rewrite along the following lines:

> Sometimes horizontal lines are used in content that is set vertically, such as on stone inscriptions or, in the past, headings for newspapers and magazines.  In such cases, characters may be ordered from right to left, and no columns are applied, but now this has largely been replaced by the horizontal lines that are read from left to right. 

Note that i removed the mention of such horizontal lines being a single line.  I don't think that is always  true. See for example the caption heading under the picture in the sample at https://github.com/w3c/type-samples/issues/35 and the text above the heading at the top right.

**Comment by huijing** [comment]
We will review the Chinese portion for this section as some edits need to be made. I will revisit the translation again once that has been taken care of.

**Comment by bobbytung** [comment]
Chinese traditionally only uses vertical writing mode. When horizontal lines are used in content that is set vertically, such as on stone inscriptions or headings for newspapers and magazines. In such cases, characters should be ordered from right to left. but now this has largely been replaced by the horizontal lines that are read from left to right.

中文传统上仅使用直排，当横排文字使用于直排文字时，如匾额、报纸、杂志的标题，文字应为由右向左排列。但目前多为由左而右的横排书写方向取代。

中文傳統上僅使用直排，當橫排文字使用於直排文字時，如匾額、報紙、雜誌的標題，文字應為由右向左排列。但目前多為由左而右的橫排書寫方向取代。
