### ISSUE TITLE
Half-size han characters

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#152]
![](https://cloud.githubusercontent.com/assets/4839211/23313401/719d73f8-fab5-11e6-9c8f-8acde6b552d8.jpg) shows a title at the bottom right that starts with 陳 followed by two small horizontally-set characters 容朝

Is this an example of what is called warichu in Japanese, or is it 'tate chu yoko'?  There is something similar going on in the horizontal heading above, to the right of '8.6%', and in the vertical heading to the right of the picture.

In what order are these characters read?

**Comment by xfq** [comment]
The order these characters are read:

* For the heading to the right of the picture, the order is "今年首場";
* For the heading to the right of "8.6%", the order is "國民黨民調";
* For the heading at the bottom right, the order is "陳朝容".

All text written horizontally is read right to left here. Well, except "ＧＤＰ", "8.6%", and the Chinese text in the picture.

**Comment by ethantw** [comment]
@r12a I updated the format so that the photo would appear properly.

I'm not sure if this is warichu, which represents a form for inline *notes*, but in this case, the smaller text was laid out that way to make room for the full titles. Also, this is clearly not tate chū yoko either, the name of the person is 陳朝容 (not 陳容朝 if read horizontally).

The 8.6% part is quite interesting though, the entire text of the title reads ‘國民黨民調　8.6%受訪者沒頭路’. This *is* tate chū yoko, a special case where numerals are set inside one-line vertical writing text.

**Comment by r12a** [comment]
Btw, the fact that 8.6% and GDP read LTR within the RTL flow is perfectly normal to me, since i work with Arabic, Hebrew, Thaana, etc scripts which also have 'bidirectional text' arrangements where numbers and Latin text are embedded in the main script.

I wouldn't have classified that whole ...8.6%... line as tate-chu-yoko. I think it's just a container with writing-mode set to horizontal (and direction to RTL) placed alongside or inside another  container that has writing-mode set to vertical-rl.  For me, tate-chu-yoko is partly defined by the requirement that it fits (width-wise) in a single line of vertical text, and the expectation that it occurs as part of that line.

> Also, this is clearly not tate chū yoko either, the name of the person is 陳朝容 (not 陳容朝 if read horizontally).

Are you saying that because you expect tcy to run LTR? This may be the first time we've examined such a case, but it seems to me that it's logical for the direction of the tcy text to flow RTL here, because RTL for horizontal text is the pattern throughout the page. (I'm not sure what the implications are for CSS support, however...)

**Comment by r12a** [comment]
> (I'm not sure what the implications are for CSS support, however...)

Actually it may be fairly simple - assign direction:rtl to all horizontal text.

**Comment by upsuper** [comment]
> Are you saying that because you expect tcy to run LTR? This may be the first time we've examined such a case, but it seems to me that it's logical for the direction of the tcy text to flow RTL here, because RTL for horizontal text is the pattern throughout the page. (I'm not sure what the implications are for CSS support, however...)

I think it is not tcy because it doesn't perserve the full height of character and compress it horizontally. it merely shrink the font size. This is quite different than what is required in tcy.
