### ISSUE TITLE
About the two glossary formats

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#155]
@ethantw

Currently, [glossary-pinyin.csv](https://github.com/w3c/clreq/blob/gh-pages/glossary-pinyin.csv) includes 99 glossary items, while https://w3c.github.io/clreq/#glossary only contains 80 items. What are the differences between the two? Is the former a superset of the latter? If so, I guess the plan is to do the translation in the csv file and copy the translation to the HTML file, right?

**Comment by ethantw** [comment]
They are basically the same. The CSV one contains 19 extra definitions of 標點符號 (i.e. 句號, 頓號, 間隔號, etc) which the HTML one does not have. I suggest we stick to the portions we distributed the other day but skip any 標點符號 that aren't in the glossary of the HTML one.

**Comment by xfq** [comment]
For the record, (after discussing with Yijun) the editors decided not to include 標點符號 in the glossary, because the document itself has already described them in detail.
