### ISSUE TITLE
要么全简体要么全繁体，现在看着太头痛了

### ISSUE THREAD

**Issue by pinxue** [w3c/clreq#16]
“行间注是标注于字词旁侧的小字号补充文本。行间注的注文通常位于行间，与其所标注的基文对齐，因這一性質而又名為行間注。行间注在中文排版里的用途主要为标音与释义。”

行間注是標註於字詞旁側的小字號補充文本。行間注的注文通常位於行間，與其所標註的基文對齊，因這一性質而又名為行間注。行間注在中文排版裡的用途主要為標音與釋義。

用简体字的人群数量在这搁着，如果真想中文技术、出版社区参与进来的的话，不出个简体版就会有这种问题喽。

**Comment by lianghai** [comment]
您不必操心这些。
简繁两个版本会在正式版提供，而目前这只是第一版公开草案。

**Comment by upsuper** [comment]
我想或许整理简体版和繁体版这件事可以开一个issue放在那边。一来作为一个未来的计划事项，二来（也许）也可以减少开新issue提这件事情的人。

**Comment by siusin** [comment]
@upsuper 支持。

直接开了一个新的issue说明情况，相关讨论请转移到#22.
