### ISSUE TITLE
Typefaces for Chinese Characters

### ISSUE THREAD

**Issue by c933103** [w3c/clreq#164]
- Down below in the document, the "Yuan" typeface style have been briefly mentioned, however it was not introduced in this section. Should an introduction for Yuan be added to the section?
- Is it a good idea to talk about which Chinese typeface correspond to which generic family for font family in css like Kai = Cursive in clreq?

**Comment by bobbytung** [comment]
Hello, 

- About "Yuan" typeface:

Like Japanese, Yuan is 丸ゴジック(round gothic), belonging to Sans-serif. 
So I think it's a variant of 黑體(Hei).

- About Generic Family:

Yes, cursive is mapped to Kai in Safari, Chrome and Firefox on desktop where Kai font is available.
And in CSS Fonts Module level 4, "FangSong" is added to generic family.
