### ISSUE TITLE
Zhuyin annotations

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/clreq#165]
I have some difficulty reconciling CLREQ 3.3.3 with the other sources I can find about zhuyin annotations. 

- what are "dialectal non-checked tones" vs. "dialectal checked tones"? Figures 10 and 11 show different placements of those, but there is no such distinction in "The manual of the phonetic symbols of Mandarin Chinese".

- in figure 13, 3rd example, is the text of the annotation <U+3127, U+31B5> or <U+3127, U+3109>?

- in figures 14 and 15, 3rd examples, what are the texts of the annotation?

**Comment by YuRen-tw** [comment]
#### 1
**Checked tone** in Wikipedia (https://en.wikipedia.org/wiki/Checked_tone):
> a checked tone is not a tone in the phonetic sense but rather a syllable that ends in a stop consonant or a glottal stop.

and

> have disappeared from most Mandarin dialects (spoken in northern and southwestern China), but remain preserved in southeastern branches of Chinese such as Yue, Min, and Hakka.

<table>
  <tr>
    <th>Tone</th>
    <th>Neutral</th>
    <th  colspan="4">Non-Neutral</th>
  </tr>
  <tr>
    <th>Symbol</th>
    <td>˙</td>
    <td>ˊ</td>
    <td>ˇ</td>
    <td>ˋ</td>
  </tr>
  <tr>
    <th>Unicode</th>
    <td>02D9</td>
    <td>02CA</td>
    <td>02C7</td>
    <td>02CB</td>
  </tr>
</table>

<table>
    <th>Dialectal Tone</th>
    <th colspan="2">Non-Checked</th>
    <th colspan="4">Checked</th>
  </tr>
  <tr>
    <th>Symbol</th>
    <td>˪</td>
    <td>˫</td>
    <td>ㆴ</td>
    <td>ㆵ</td>
    <td>ㆶ</td>
    <td>ㆷ</td>
  </tr>
  <tr>
    <th>Unicode</th>
    <td>02EA</td>
    <td>02EB</td>
    <td>31B4</td>
    <td>31B5</td>
    <td>31B6</td>
    <td>31B7</td>
  </tr>
</table>

<table>
  <tr>
    <th colspan="5">Dialectal Checked tones</th>
  </tr>
  <tr>
    <th>Symbol</th>
    <td>ㆴ</td>
    <td>ㆵ</td>
    <td>ㆶ</td>
    <td>ㆷ</td>
  </tr>
  <tr>
    <th>Unicode</th>
    <td>31B4</td>
    <td>31B5</td>
    <td>31B6</td>
    <td>31B7</td>
  </tr>
  <tr>
    <th rowspan="2">Stop consonant</th>
    <td>Bilabial</td>
    <td>Alveolar</td>
    <td>Velar</td>
    <td>Glottal</td>
  </tr>
  <tr>
    <td>-p</td>
    <td>-t</td>
    <td>-k</td>
    <td>-h</td>
  </tr>
</table>

Checked tone have disappeared from Mandarin Chinese, so the symbols are not described in "The manual of the phonetic symbols of ***Mandarin Chinese***"; furthermore, they are in the "Bopomofo Extended" (https://en.wikipedia.org/wiki/Bopomofo_Extended).

#### 2
In figure 13, 3rd example, it's <U+3127, U+31B5>

#### 3
- In figures 14, 3rd example, it's <U+310C, U+3127, U+31B6 with U+0307>
- In figures 15, 3rd example, it's <U+3109, U+3127, U+311C, U+31B7 with U+0307>

<U+0307> is COMBINING DOT ABOVE.
As I know, in Taiwanese Hokkien, a symbol of checked tone is used to indicate the 4th tone.
And a symbol with a "COMBINING DOT ABOVE" is used to indicate the 8th tone, which is also a checked tone, but just higher than 4th.
(see *Taiwanese Phonetic Symbols* in Wikipedia: https://en.wikipedia.org/wiki/Taiwanese_Phonetic_Symbols)
