### ISSUE TITLE
“括”的读音

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#170]
In #166:

> 附錄的詞彙表中：

> 「（開始、結束）括注符號」（共三條）中的「括」字，在簡體中文裡讀「kuo4」（去聲），與傳統中文不同，似應分別註音。

目前我们还没有分别注音的术语，需要讨论如何呈现。

**Comment by lianghai** [comment]
鉴于这是地区正音差异，不是简繁中文的问题，所以不必在简繁版本里两个读音分别注音（虽然简繁版本是有地区倾向的，但分别注音还是不妥）。如有必要注音，应当在简繁版本各自都提供两个读音并注明读音偏好的地区。

**Comment by ryukeikun** [comment]
「简繁版本各自都提供两个读音并注明读音偏好的地区」这本身问题不大。

麻烦的是，不仅是字音问题，还影响到「词汇表」的**排序**。由于目前按音序排列，且这个多音字又是字头，因此会导致词汇表的排序不同，因此解决方案有：

1. 「（開始、結束）括注符號」是 CLREQ 专用词汇，是否考虑修改
2. 建议词汇表放弃「音序」而改「笔画/部首」等字形顺序排。跨区域的文本都不是按照音序排列的。但是考虑到绝大多数用户更习惯于音序排序，是否有必要为这一个词而改变整个词汇表排序方式，需要讨论
3. 繁简不同版本分别按照不同发音分别排序

好像每个方案都有点麻烦……

**Comment by ethantw** [comment]
改用詞彙的英語翻譯字母順序來排序呢？

**Comment by ryukeikun** [comment]
理论上说，索引应该按照不同语种分别排序，即英文版按英文排序，中文版按中文排序。不能指望所有中文用户都会英文，更何况 CLREQ 里一些术语并不都是常用翻译，用户找不到，就起不到索引的作用呀。

**Comment by c933103** [comment]
可不可以考慮不要用普通話/國語排序…不是每個人都懂官話的…

**Comment by Jinjiang** [comment]
> 「词汇表」的排序问题

可以当“多音字”来看待吗？汉子里的多音字比如“乐”可以读作拼音“le4”或者“yue4”，是否可以这样看待：）

谢谢

**Comment by xfq** [comment]
> 可以当“多音字”来看待吗？汉子里的多音字比如“乐”可以读作拼音“le4”或者“yue4”，是否可以这样看待：）

多音字不同的读音语义常常不同，个人感觉不太适用。

**Comment by Jinjiang** [comment]
> 多音字不同的读音语义常常不同，个人感觉不太适用。

不是所有的多音字都是因为不同语义，有些也是因为不同区域 (比如南方/北方) 习惯的念法不同。比如发酵 (jiao2/xiao2) 都是可以的。

**Comment by ethantw** [comment]
未來，我們會對CLReq的詞彙表做一個體驗優化，始其能以讀者的偏好語言文字（簡體中文根據大陸地區的普通話發音、繁體中文根據台灣地區的國語發音、英語以詞彙之英譯）來排序，甚至可以手動切換排序方式。

由於目前詞彙表中，只有「括注符號」「開始括注符號」「結束括注符號」三個兩岸有所差異的發音，在進行上述優化前，我建議我們可以：

1. 將「括注符號」一詞改為「夾注符號」
2. 統一使用kuò來標注「括」字（[台灣教育部承認kuò為括的又音](https://www.moedict.tw/括)）

來規避「括」字的地區發音差異的問題。

我個人認為「夾注符號」比「括注符號」更為中性，也免於後者容易與「括號」混淆，所以我較偏好第一個方法。如有更好的提議，還請指教。

**Comment by ethantw** [comment]
目前先統一改成「夾注符號」，若未來有更好的方式，我們可以再討論。

**Comment by ryukeikun** [comment]
agree!
