### ISSUE TITLE
3.1.6.2 clauses 1 and 2 are conflicting/confusing

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/clreq#172]
Section 3.1.6.2 Compression of punctuation marks at line start states:

---
1. For the case of line head indent, if a bracket is set at the beginning of a line, half a character space can be reduced ahead of the bracket.

2. When an opening bracket appears at the beginning of a line, half a character space can be reduced ahead of the bracket.
---

Given 2, it would seem that 1. applies only to _closing_ brackets. But then, the half character space is _after_ the bracket.

Or, may be 1 should apply only to _opening_ brackets; but then why would one have both 1. and 2.?

**Comment by r12a** [comment]
My guess is that we're talking about 
a. a line that starts a para and is indented by one character space
b. a line that doesn't start a para, or doesn't have an indentation.

My further guess is that (1) refers to scenario (a) and means that the _indentation_ is reduced to half a character width(?)

**Comment by bobbytung** [comment]
<img width="254" alt="2018-08-17 6 28 28" src="https://user-images.githubusercontent.com/1863378/44262434-a3421a80-a24d-11e8-964c-1d1a70e001f3.png">

In Chinese fictions, dialogue usually wrapped with brackets. To align with other paragraphs horizontally, designers may apply 1. rule for indented line head. But 2. is an option.

<img width="88" alt="2018-08-17 6 44 30" src="https://user-images.githubusercontent.com/1863378/44262580-18155480-a24e-11e8-9b51-94bec2ff908d.png">

Usually when designers apply 2. rule on layout, usually included 1. rule.

And for indentation, traditionally cut half of the character width. But the way is not suit for all font. Some fonts put the brackets in the middle, it's a problem.

<img width="392" alt="2018-08-17 6 39 09" src="https://user-images.githubusercontent.com/1863378/44262664-6fb3c000-a24e-11e8-80a3-9f996195dff1.png">

**Comment by moyogo** [comment]
> And for indentation, traditionally cut half of the character width. But the way is not suit for all font. Some fonts put the brackets in the middle, it's a problem.

Should the [`vhal` *Alternate Vertical Half Metrics*](https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz#vpal) or [`halt` *Alternate Half Widths*](https://docs.microsoft.com/en-us/typography/opentype/spec/features_fj#halt) features be used instead of cutting half of the character width when available?
