### ISSUE TITLE
3.1.5.1 Punctuation Marks

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/clreq#173]
> U+2E3A TWO-EM DASH [⸺] or U+2014 EM DASH [—] should take one character height and two character widths.

I suppose this should be "U+2E3A and _two successive_  U+2014 ..."

> According to section 5.1.5 of the General Rules for Punctuation (GB/T 15834―2011), when two horizontal ellipses are used together, they should be four characters wide and occupy an independent line.

The "four" seem very strange here. And this contradict the sentence above it.

**Comment by xfq** [comment]
> > U+2E3A TWO-EM DASH [⸺] or U+2014 EM DASH [—] should take one character height and two character widths.
> 
> I suppose this should be "U+2E3A and _two successive_  U+2014 ..."

I submitted https://github.com/w3c/clreq/pull/175 to fix this.

> > According to section 5.1.5 of the General Rules for Punctuation (GB/T 15834―2011), when two horizontal ellipses are used together, they should be four characters wide and occupy an independent line.
> 
> The "four" seem very strange here. And this contradict the sentence above it.

After reading section 5.1.5 of General Rules for Punctuation (GB/T 15834―2011), I think it means two **Chinese** horizontal ellipses, i.e. twelve dots. The "twelve dots" form is often used for omission of line(s) in poetry, or omission of paragraph(s). Therefore, this rule doesn't really contradict with the sentence above the rule.

See also #25 (discussions in Chinese).

**Comment by r12a** [comment]
https://w3c.github.io/clreq/#x3-1-5-1-punctuation-marks
> U+2E3A TWO-EM DASH [⸺] or U+2014 EM DASH [—] should take one character height and two character widths. Long dashes [——] can be created using two adjacent em dashes.

This para is a little complicated. How about changing to:

> Long dashes [——] can be created using U+2E3A TWO-EM DASH [⸺] or two adjacent U+2014 EM DASH [—] characters. Both alternatives should take one character height and two character widths

**Comment by xfq** [comment]
Looks good to me. Pushed the para to #175.

**Comment by r12a** [comment]
Is the Chinese ok?

**Comment by xfq** [comment]
Personally, I think it's ok. It doesn't say "take one character height", but I assume this is a well-known fact...

**Comment by xfq** [comment]
Closing this issue, since #175 has been merged.
