### ISSUE TITLE
Position of ruby, text-emphasis, under/overline, etc

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#176]
I raised the question at https://github.com/w3c/clreq/issues/136#event-1624793646 because I didn't find any answer in clreq.  I think it would be useful to add a section to clreq that sums up the conclusions reached, rather than just leaving them in a closed issue (see in particular https://github.com/w3c/clreq/issues/136#issuecomment-288703222).

This is a request for text to be added to the document. I may be able to provide some starter text, if that would be useful.

**Comment by xfq** [comment]
These are mostly (if not all) covered in clreq now. Should we close this issue?

**Comment by r12a** [comment]
Happy to close.

**Comment by xfq** [comment]
Thank you!
