### ISSUE TITLE
Glossary should be presented in tables

### ISSUE THREAD

**Issue by ethantw** [w3c/clreq#18]

**Comment by siusin** [comment]
有部分词汇有较长的中文说明，确定table是最好的显示方式？

**Comment by ethantw** [comment]
使用表格的話，讀者可以將焦點放在相同欄位快速地上下査找。一般的describing lists就無法提供這種呈現方式。

**Comment by siusin** [comment]
@ethantw 

之前还有人提出table应该用实线，你怎么看？我可以改style。

**Comment by ethantw** [comment]
樣式等我把注音的插圖加進來後再一起改吧，有很多地方需要調整。我稍後開一個issue記錄需要改進的地方。

**Comment by siusin** [comment]
OK, thx ^_^
