### ISSUE TITLE
Need a font-family style set for zh text

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#184]
Currently, the clreq document attempts to display Chinese text using the Helvetica font. As a result, the Chinese characters are displayed in whatever fallback font is used by the viewer's browser, but common punctuation, such as middle dot, is not displayed correctly.

We should alter the CSS style sheet to set a sequence of fallback fonts, based on readily available fonts for major platforms, for use with text that has the language zh-hans or zh-hant.

**Comment by xfq** [comment]
Fixed in #185.
