### ISSUE TITLE
Add Source Han Sans?

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#187]
From https://github.com/w3c/clreq/pull/185#issuecomment-413903047 :

> Please consider to add `Source Han Sans`. Some people may not have `Noto Sans CJK` on their computers.

Should we add `Source Han Sans` to the font stack in our style sheet?

**Comment by huijing** [comment]
Source Han Sans the system font for which system? Noto Sans was added as the default for Android systems

**Comment by xfq** [comment]
@Stone-Zeng, do you have more info?

**Comment by stone-zeng** [comment]
Some Windows users may install Source Han by themselves, then it will give a better effect, especially punctuation.

**Comment by xfq** [comment]
The editors discussed this issue today and resolved to close this issue as WONTFIX. Closing accordingly.

https://www.w3.org/2018/10/12-clreq-minutes.html
