### ISSUE TITLE
着重号

### ISSUE THREAD

**Issue by ghost** [w3c/clreq#188]
着重号应该是U+0323吧，我从RIME那边了解到的

**Comment by upsuper** [comment]
U+0323语义上是combining dot below，是一个在与其他文字组合时可以在文字下面显示点的字符，这个字符通常用于在拉丁系语言里改变一个音节的读音。而着重号是一种文字装饰，类似于下划线、删除线一类的东西，是属于由排版系统提供的样式。其本身并不是语义的一部分。

输入法试图在纯文本中实现这一样式，可能会活用一些组合字符来，但它们在语义上是不正确的。
