### ISSUE TITLE
Alphabetical Chinese list sorting

### ISSUE THREAD

**Issue by c933103** [w3c/clreq#189]
Some of the currently most popular methods of sorting a Chinese list include:

* Phonetic-based sorting
  * Pinyin
  * Zhuyin
  * Other romanization methods
* Ideograph-based sorting
  * Stroke count
  * Radicals
  * Other methods like four corners
* Encoding-based sorting
  * Unicode Code point
  * Chinese Telegram Code
  * Other encoding schemes

It would be nice for clreq to list out and comoare these different methods of sorting in the document, alongside with advantage and disadvantage of each of them.

Limitation and special consideration for each sorting methods should also be included, for instance if a list is sorted according to radical, then there should be a navigational index next to the list that allow users quickly locate the desired target in the list, if the list was intended for user to select item from.

**Comment by huijing** [comment]
Sorting is beyond the scope of this document.
