### ISSUE TITLE
Starter text for sections on text decoration, emphasis, etc

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#192]
Suggested starter text, as subsections to go under 3 Line Composition.  This covers the discussions in https://github.com/w3c/clreq/issues/136, and https://github.com/w3c/clreq/issues/149.

# Text decoration

Straight or wavy lines alongside the text are typically used in Chinese to indicate proper nouns such as a person's name, a book title, or the name of a place (see Fig XX), rather than for emphasis like the underlining associated with Latin-script text. 

When two different proper nouns appear side-by-side, the underline should be broken between the two.

In horizontal text, lines (straight or wavy) appear underneath the base text.

Usually lines appear to the left of a vertical line, ie. on the opposite side of items such as emphasis marks, or ruby, to avoid interference).

If a line of Chinese text contains some text in Japanese or another language, and there is a line associated with that text, the position of the line should follow the Chinese conventions (see Fig YY).

# Emphasis

Chinese uses dots alongside characters to express emphasis, one dot per base character (see Fig. ZZ).

In horizontal text, emphasis marks appear underneath the base text.

Usually emphasis dots appear to the right of a vertical line, ie. on the opposite side of text decoration lines (to avoid interference).

If a line of Chinese text contains some text in Japanese or another language, and there is are emphasis marks associated with that text, the position of the marks should follow the Chinese conventions (see Fig WW).

**Comment by xfq** [comment]
We now have https://w3c.github.io/clreq/#handling_interlinear_punctuation

@r12a Can we close this issue?

**Comment by r12a** [comment]
Yes. Thanks.

**Comment by xfq** [comment]
Thank you!
