### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by siusin** [w3c/clreq#2]
from @MieMie
[[
1. 「2.3.3 以版心……」 中 「圖片之尺寸橫排時圖片」，中间似乎应该有个标点断句
2. 「3.1.1.2 標號」中「刪節號」的最后多了一个「]」，同样的问题也出现在「3.1.5.1 標點符號」中
3. NOTE 与正文的关系似乎有点乱，有些 NOTE 感觉应该属于正文，反之亦然
4. GitHub 上似乎还是很早的版本？这类小问题还挺多，如果能放到 GitHub 上，讨论、修改起来会会更方便些？
]]

**Comment by siusin** [comment]
1,2,4 Done

**Comment by siusin** [comment]
@houkanshan 
3 需要更详细的说明 ^_^

**Comment by houkanshan** [comment]
我也不清楚标准，但感觉存在不同处理（简/繁、古/今、个别案例）的部分都会放入 NOTE，这里是几个需要考虑的地方：
- https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L669
- https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L683

然后根据上下文看，觉得可以考虑作为正文的：
- https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L502
- https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L1186 （这条不是很明白，是在说明「标题作为某种功能使用时的分类」，还只是在说明「标题在所有使用场景下，依层接构造的几种类型」？）

另外，这有两处「注2」：
- https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L598
- https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L1198

**Comment by ethantw** [comment]
> 感觉存在不同处理（简/繁、古/今、个别案例）的部分都会放入 NOTE

繁簡差異是這分文件主要闡述的着重點之一，寫在正文還是比較合適的。

> 觉得可以考虑作为正文

楷體的用途的確應放入正文。

> 这条不是很明白，是在说明「标题作为某种功能使用时的分类」，还只是在说明「标题在所有使用场景下，依层接构造的几种类型」？

應該是後者。標題的定義也放入正文好了。

> 这有两处「注2」

Thanks! 待之後修正。

**Comment by ethantw** [comment]
B the W, 現在的注釋是一片鮮豔的綠色，實在過於醒目，目光全聚到注釋上了。之後會把樣式調整一下。

**Comment by houkanshan** [comment]
> 繁簡差異是這分文件主要闡述的着重點之一，寫在正文還是比較合適的。

啊这样的话， 看看 [L710](https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L710) 是否应放入正文。与之类似的 [L683](https://github.com/w3c/clreq/blob/gh-pages/zh%2Findex.html#L683) 也在正文
