### ISSUE TITLE
3.1.3 非典型的標點符號及其配置 新增內容

### ISSUE THREAD

**Issue by bobbytung** [w3c/clreq#206]
#### 3.1.3.3 嘆問號與問、嘆號疊加

嘆問號於中國大陸《標點符號用法》（GB/T 15834–2011）中作為嘆號的延伸用法，當語氣同時具備強烈的疑問與感嘆時，可於問號後加上嘆號（?!）。然而在許多作品中，也常見在嘆號後加上問號（!?）的用法。此外，在同標準的問號與嘆號用法也指明在語氣加重時可疊用問號或者嘆號，最多可疊用到三個（!!!、???）。

排版上，《標點符號用法》規定問號與嘆號連用時，佔一個字位置；兩個問號或嘆號疊用時，佔一個字位置；三個問號或嘆號疊用時，佔兩個字位置。此外，在台灣直排的習慣中，嘆問號連用與問號、嘆號疊用時，符號多直立，並且佔一個字的位置。

> Note：
> 在Unicode中已編有U+2047 DOUBLE QUESTION MARK [⁇]、U+203C DOUBLE EXCLAMATION MARK [‼]、U+2048 QUESTION EXCLAMATION MARK [⁈]、U+2049 EXCLAMATION QUESTION MARK [⁉]等符號，在考量字體支援下可斟酌使用。

#### 3.1.3.4 示亡號

示亡號並未列於標點符號相關標準文件，但卻是民間經常使用的俗用符號。示亡號亦稱示殁号，為在人名文字外框描上實心的黑色邊線表示已經過世，類似西文中劍標（U+2020 DAGGER  †與U+2021 DOUBLE DAGGER ‡）之用法。

示亡號主要標示於近年過世的人名，常出現在名單、公報、族譜等人名列表上，用以告知此人已亡歿。而過世已久或眾所皆知的歷史人物不再加註。

-----

Please review and I'll translate later.

Close #39 and #51

**Comment by huijing** [comment]
觉得翻译得有点不协调，麻烦大家过目一下。

3.1.3.3 Exclamatory question mark, repeating question marks and repeating exclamation marks | 叹问号与问、叹号叠加

Exclamatory question marks are defined in the General Rules for Punctuation (GB/T 15834-2011) under extended usage. For questions with a strong exclamatory tone of voice, it is appropriate to add an exclamation mark after the question mark (?!). However, it is common to see a question mark added after an exclamation mark (!?) in numerous publications as well. In addition, GB rules indicate that it is acceptable to chain up to 3 exclamation marks or question marks in succession (!!!, ???) for exclamatory statements or interrogative sentences which require greater emphasis.
叹问号于中国大陆《标点符号用法》（GB/T 15834–2011）中作为叹号的延伸用法，当语气同时具备强烈的疑问与感叹时，可于问号后加上叹号（?!）。然而在许多作品中，也常见在叹号后加上问号（!?）的用法。此外，在同标准的问号与叹号用法也指明在语气加重时可叠用问号或者叹号，最多可叠用到三个（!!!、???）。

In print publications, GB rules state that when question marks and exclamation marks are chained, they are considered one character width. Double question marks or double exclamation marks also one character width. Triple question marks or triple exclamation marks are two character widths. In addition, for vertical writing mode in Taiwan, chained question marks or exclamation marks are upright and take up one character width.
排版上，《标点符号用法》规定问号与叹号连用时，占一个字位置；两个问号或叹号叠用时，占一个字位置；三个问号或叹号叠用时，占两个字位置。此外，在台湾直排的习惯中，叹问号连用与问号、叹号叠用时，符号多直立，并且占一个字的位置。

Note：
The following punctuation marks already exist in Unicode: U+2047 DOUBLE QUESTION MARK [⁇]、U+203C DOUBLE EXCLAMATION MARK [‼ ]、U+2048 QUESTION EXCLAMATION MARK [⁈]、U+2049 EXCLAMATION QUESTION MARK [⁉]. They should be used with discretion.
在Unicode中已编有U+2047 DOUBLE QUESTION MARK [⁇]、U+203C DOUBLE EXCLAMATION MARK [‼ ]、U+2048 QUESTION EXCLAMATION MARK [⁈]、U+2049 EXCLAMATION QUESTION MARK [⁉]等符号，在考量字体支援下可斟酌使用。

3.1.3.4 Symbol of death | 示亡号

The symbol of death is not defined in the GB rules, but is a punctuation mark which is widely used by the commons. The symbol of death is used outside the character frame of a person's name to indicate the person is deceased. It's Western counterpart would be the dagger punctuation mark (U+2020 DAGGER †与U+2021 DOUBLE DAGGER ‡).
示亡号并未列于标点符号相关标准文件，但却是民间经常使用的俗用符号。示亡号亦称示殁号，为在人名文字外框描上实心的黑色边线表示已经过世，类似西文中剑标（U+2020 DAGGER †与U+2021 DOUBLE DAGGER ‡）之用法。

The symbol of death is used to indicate a person who had been recently deceased, and is often seen in name lists, official reports, genealogy records and so on. It is not used for people who have passed away for some time or well-known deceased individuals.
示亡号主要标示于近年过世的人名，常出现在名单、公报、族谱等人名列表上，用以告知此人已亡殁。而过世已久或众所皆知的历史人物不再加注。

**Comment by c933103** [comment]
示亡號主要是在哪些地區使用？

**Comment by xfq** [comment]
> Exclamatory question marks are defined in the General Rules for Punctuation (GB/T 15834-2011) under extended usage.

@huijing What about changing "under extended usage" to "as an extended usage of exclamation marks"?

**Comment by huijing** [comment]
> 
> 
> > Exclamatory question marks are defined in the General Rules for Punctuation (GB/T 15834-2011) under extended usage.
> 
> @huijing What about changing "under extended usage" to "as an extended usage of exclamation marks"?

Makes sense. If that's the only change, should I make the PR?

**Comment by xfq** [comment]
> > > Exclamatory question marks are defined in the General Rules for Punctuation (GB/T 15834-2011) under extended usage.
> > 
> > 
> > @huijing What about changing "under extended usage" to "as an extended usage of exclamation marks"?
> 
> Makes sense. If that's the only change, should I make the PR?

Sure. Thank you!

**Comment by xfq** [comment]
> 示亡號主要是在哪些地區使用？

@c933103 其他地区我不清楚，中国大陆应该是广泛使用示亡号的。

**Comment by c933103** [comment]
> > 示亡號主要是在哪些地區使用？
> 
> @c933103 其他地区我不清楚，中国大陆应该是广泛使用示亡号的。

在香港和台灣都沒找到用例。。。

**Comment by xfq** [comment]
> > > 示亡號主要是在哪些地區使用？
> > 
> > 
> > @c933103 其他地区我不清楚，中国大陆应该是广泛使用示亡号的。
> 
> 在香港和台灣都沒找到用例。。。

维基百科里有一例：https://zh.wikipedia.org/w/index.php?title=示亡号&oldid=55377788#cite_note-3

**Comment by bobbytung** [comment]
> > > 示亡號主要是在哪些地區使用？
> 
> 在香港和台灣都沒找到用例。。。

廣泛使用在港台的訃聞中，親屬家人已經過世者都會使用示亡號。
我就不舉例了，請自行Google「訃聞」做圖片搜尋。

**Comment by r12a** [comment]
> They should be used with discretion.

What does 'with discretion' mean⁇

**Comment by r12a** [comment]
> It's Western counterpart would be the dagger punctuation mark

This seems to imply that one should not use U+2020 DAGGER † or U+2021 DOUBLE DAGGER ‡ for this function. Is that intended?

Also note that the English version has some untranslated chinese text in it.

> (U+2020 DAGGER †与U+2021 DOUBLE DAGGER ‡)

**Comment by r12a** [comment]
> The symbol of death is used outside the character frame of a person's name

Could we have an example?  Even an example in the text would be useful, if we can't scan one.  I think it would be particularly useful to show it in the context of the character frame of the name.

**Comment by xfq** [comment]
> > They should be used with discretion.
> 
> What does 'with discretion' mean⁇

The original Chinese text (在考量字体支援下可斟酌使用) means that they can be used with consideration of font support.

**Comment by bobbytung** [comment]
> > The symbol of death is used outside the character frame of a person's name
> 
> Could we have an example? Even an example in the text would be useful, if we can't scan one. I think it would be particularly useful to show it in the context of the character frame of the name.

Here's some examples I found by Google image search. I'm afraid that they seem to be real funeral announcement.

1. [Taiwan, 2014](http://2.bp.blogspot.com/-bvzkEhW3TNE/UxQ4hJw000I/AAAAAAAAGK8/oGlB8QB2fYU/s1600/陳文雄訃聞.jpg)
2. [Taiwan, 2017](http://www.chi-nanchurch.tw/bulletin/communion/copy3_of_.jpg/@@images/7c0ed0f8-e548-4110-83f1-01e7c1c89b91.jpeg)
3. [HongKong, 2017](https://www.mingpaocanada.com/tor/ftp/News/20170228/HK/_28ME009_.jpg)

**Comment by r12a** [comment]
Ah!  So the symbol of death is the box drawn around the characters⁈

I don't think that's punctuation – it's a kind of text decoration.  But now i really think an example is needed in this paragraph, because i was looking for something that ressembled the dagger mark. We should probably also have some text saying something to the effect that the symbol of death is visually represented by a box drawn around the person's name.

**Comment by huijing** [comment]
Edited the English translation and added an example image to better illustrate its usage.

![symbol-of-death](https://user-images.githubusercontent.com/1461498/73934568-a802fe80-4919-11ea-958a-b7c4126e045f.png)

**Comment by xfq** [comment]
Link to PR: https://github.com/w3c/clreq/pull/234

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/pull/279
