### ISSUE TITLE
Tweak the English version of the region differences section

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#215]
See https://github.com/w3c/clreq/commit/e39e931ce1a577c872482551c2ba9530e22e249e#commitcomment-33511222 for the proposed rephrasing from @r12a.

**Comment by huijing** [comment]
Updated in commit https://github.com/w3c/clreq/pull/208/commits/5f0b1f8b5dfea6af2d2872e48c1dd86bcdc3c23f
