### ISSUE TITLE
Rewrite of Prohibition Rules for Line Start and Line End 行首行尾禁则

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#220]
This section should be rewrite by introducing different level / styles of Prohibition Rules such as "none", "loose", "strict" for UA to match.

**Comment by xfq** [comment]
Link to the current clreq section: https://w3c.github.io/clreq/#prohibition_rules_for_line_start_end

Related information:

* [JLReq § 3.1.7 Characters Not Starting a Line 行頭禁則](https://w3c.github.io/jlreq/#characters-not-starting-a-line)
* [JLReq § 3.1.8 Characters Not Ending a Line 行末禁則](https://w3c.github.io/jlreq/#characters-not-ending-a-line)
* [JLReq § C. Possibilities for Line-breaking between Characters 文字間での分割の可否](https://w3c.github.io/jlreq/#appendix_3)
* [CSS Text § 5.3 Line Breaking Strictness: the line-break property](https://drafts.csswg.org/css-text-3/#line-break-property)

**Comment by ryukeikun** [comment]
建议将目前的三个「注」删除，修改为：

-------
具体地，可以分为四种级别：
1. 不处理（none）：完全不处理行首行尾禁则。常见于台湾香港等地报刊。
2. 基本处理（basic）：点号（顿号、逗号、句号、冒号、分号、叹号、问号）、结束引号、结束括号、结束乙式书名号（篇名号）、连接号、间隔号、分隔号不能出现在一行的开头。开始引号、开始括号、开始单双书名号等符号，不能出现在一行的结尾。这是最推荐的方法。
3. GB法（GB-style）：在执行「基本处理」的基础上增加规定分隔号也不能出现在一行的结尾。
4. 严格处理（strict）：在执行「GB法」的基础上再增加规定破折号、省略号不能出现在一行的开头。

本节与「3.1.6 标点符号的挤压」的关系：应优先按照排版风格处理标点挤压，再处理禁则。因为标点挤压处理会影响换行位置。

排版时如果进行禁则处理，应遵守「先挤进，后推出」原则，即不希望标点符号出现在行首时，应在已经标点挤压的基础上再次检讨是否有机会将其挤到前一行，最后没有挤压机会再从前一行取最后一个字至下一行。前行多出来的空间需按照优先顺序拉伸，最后没有拉伸机会再按平均拉大字距的方式处理。

<注> 原则上，一份文档内的级别应该统一。但若遇连续三个标点符号，如[。』」]等个别特殊状况局部采用「不处理」以避免字距过松造成体例不良，应该视为救济措施的个例，不作为推荐。

------

相应地，表 A.1 应修改表述

------

对于级别的命名，不建议用 loose 而改用 basic 是因为，loose 容易引起误会，让人认为「严格」比「宽松」好。事实上， 排版规则越严格反而会导致可供调整的机会越少，越容易导致字距的破绽，因此实际「宽松」即已经足够，而且也是实作中最常见做法，用「基本」可以减少误解的机会。

增加「GB风格」是从大厂商「符合性」Compliance 考量和便利性而增设的。尽管这条国标值得商榷，但鉴于推荐国标的权威性，相信有很多 UA 希望有一个「做到这个程度即符合国标」的级别。

------
对于连接号、间隔号、分隔号，是否放入 basic 的考量：
鉴于 [Unicode 标准附件第十四号《Unicode 断行算法》（UAX14）](https://unicode.org/reports/tr14/)算法第十三（LB13）条规定了在 ‘]’、‘!’、‘;’、‘/’ 之前不能断行，即使这些字符跟在空格后面。因此，此规则实质上此条规定了分隔号（/）需要避头；算法第二十一条（LB21）规定：在连字符、其他连字符、定宽空格、小写假名等字符前面不能断行。根据此项规则，中文的连接号也要避头。因此在符合 Unicode 定义的环境里就已经支持上述 2. basic 的动作，不矛盾。

与 UAX14 矛盾的有两点：
1. 算法第十九条（LB19）规定：引号的前、后均不能断行。也就是说常用的蝌蚪引号（“ ”）默认是既要避头也要避尾。→ 此规定过于严格，已向 Unicode 提交 bug 报告
<img width="763" alt="bitouwei-unicode-quotation" src="https://user-images.githubusercontent.com/8192599/74391127-9bfdcc00-4e46-11ea-88fb-c582e19c0546.png">
2. 算法第二十二条（LB22）规定：两个省略号之间，以及字母数字叹号与省略号之间不能断行。也就是说，省略号不仅不能中间断开，而且要避头。→ 此规定过于严格，需要UA注意。

**Comment by xfq** [comment]
多谢Eric。我有两个问题：

1. 「完全行首行尾禁则」是否应为「完全不处理标点禁则」？
2. 「前行多出来的空间需按照优先顺序拉伸」指的是？

另外，如果「基本处理」代表「宽松」，建议把第三条「GB法」里的「宽松」也改为「基本处理」。

**Comment by ryukeikun** [comment]
@xfq 
1. 不好意思，是笔误。
2. 挤压、拉伸空间都有优先顺序，这在 jlreq 有，而 clreq 还没有，需要在其他章节补充。
另外第三点也是笔误，不好意思。我重新修改一下。

**Comment by xfq** [comment]
在最新的 CSS Text 标准中，`U+2010 (hyphen)` 和 `U+2013 (En Dash)` 在 loose 时，之前如果是汉字则可以断行（可以出现在一行的开头），前面如果不是汉字则不能断行（不能出现在一行的开头）。中文的连接号是否也需要调整？

相关更改：https://github.com/w3c/csswg-drafts/commit/2cfcf436dde93692634bd8788bd163350be4f6d7#diff-2eb05d513690e5c4031fdea92fa32604R2971-R2978

**Comment by xfq** [comment]
> 挤压、拉伸空间都有优先顺序，这在 jlreq 有，而 clreq 还没有，需要在其他章节补充。

明白，谢谢。我们是否可以写一个issue？

**Comment by ryukeikun** [comment]
@xfq 关于连接号，我曾经想过，可以从我的草案里的 basic 拿下来，放到 GB-style 层级里，这样 basic 就可以用 CSS Text 的 loose 去对应。但是 CSS Text 的 loose 这一点过于宽松？在实作方面，其实都会按照 Unicode 标准附件第十四号《Unicode 断行算法》（UAX14）算法第二十一条（LB21）规定，即在连字符、其他连字符、定宽空格、小写假名等字符前面不能断行，不会出现在行首的。

关于挤压、拉伸空间的优先顺序，已建 #255

**Comment by xfq** [comment]
> 但是 CSS Text 的 loose 这一点过于宽松？

关于这一点，我们可以再和其他编辑讨论，需要的话也可以创建一个 CSS 的 issue。小林老师针对日文的需求去年也有过一些评论：https://lists.w3.org/Archives/Public/public-jlreq-admin/2019OctDec/0005.html

另外，对于其他两种连接号的处理，在 [CSS Text](https://drafts.csswg.org/css-text-3/#line-break-property) 中也与短横线（En Dash）不同。

综合起来看，目前 CSS Text 的规则似乎是：

* Hyphen 和 En Dash 在 `loose` 时，之前如果是汉字则可以断行（可以出现在一行的开头），前面如果不是汉字则不能断行（不能出现在一行的开头）
* 浪纹线（FULLWIDTH TILDE）在 `normal` 和 `loose` 中可以出现在一行的开头
* 没有提到一字线（Em Dash）

和这里的需求也不太一样。

**Comment by ryukeikun** [comment]
正如小林敏老师在邮件所述，hyphen 无论全角还是半角，大多数人还是认为需要避头的。而  U+2013 EN DASH [–] 虽然在 JIS X 4051 中规定要避头，小林老师本人也觉得避头更合适，但对于日文实际现状来说，这个符号比较新（跟多人的人与 hyphen 混用）所以很多人在不知道的情况下会用放到行头。所以在日文的需求来说，应该是要避头的。

另一方面，中国大陆的 [GB/T15834-2011 的 5.1.6 规定](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)连接号是要避头的，而且这个连接号包括U+2014 EM DASH [—]，浪纹线 U+FF5E FULLWIDTH TILDE [～] 和 U+2013 EN DASH [–]（理论上还有 U+FF0D FULLWIDTH HYPHEN-MINUS[－] 但实际上由于输入法/字库的问题，几乎没有人用），所以在需要 hyphen 的地方挪用了西文的 U+2013 EN DASH [–] 来用。

总之，从需求文档的角度来说，需求还算是明确的。CSS Text 的这个 loose 遇到汉字断行的话则过于宽松——这应该是 CSS 的 issue 而不是需求文档的问题。

**Comment by xfq** [comment]
在 CSS Text 中，[line-break](https://drafts.csswg.org/css-text-3/#line-break-property) 属性 `auto` 之外的值定义如下：

> **loose**: Breaks text using the least restrictive set of line-breaking rules. Typically used for short lines, such as in newspapers.
> **normal**: Breaks text using the most common set of line-breaking rules.
> **strict**: Breaks text using the most stringent set of line-breaking rules.
> **anywhere**: There is a soft wrap opportunity around every typographic character unit... [snipped]

按照我的理解，「不处理」对应 `anywhere`，「基本处理」对应 `loose` 或 `normal`，「严格处理」对应 `strict`，而「GB法」目前没有对应的属性值。

如果「基本处理」是最推荐的方法，我建议可以将其对应到 `line-break` 的 `normal` 而不是`loose`。这样的话，虽然对浪纹线的处理还和 CSS 不一致（因为目前浪纹线在 `normal` 中可以出现在一行的开头），但 En Dash 已经一致了。如果这样的话，我们还需要讨论中文排版需求是否需要引入一个与 CSS 对应的 `loose` 值。 @ryukeikun 觉得如何？

**Comment by ryukeikun** [comment]
是不是可以补一句「行首行尾禁则规定属于排版风格，各个用户代理实作可以根据自身实际情况，选择或者自定义适合自己的、更宽松或者严格的禁则。」

**Comment by xfq** [comment]
@ryukeikun 我觉得没问题。我提交了一个PR：https://github.com/w3c/clreq/pull/269
