### ISSUE TITLE
Rewrite of Compression Rules for Punctuation Marks 标点符号的挤压

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#221]
https://w3c.github.io/clreq/#compression_rules_for_consecutive_punctuation_marks

This section should be rewrite because

1. The current rules are basically translated from [JLreq,](https://www.w3.org/TR/jlreq/#positioning_of_consecutive_opening_brackets_closing_brackets_comma_full_stops_and_middle_dots) which are quite cumbersome.

2. There are some misunderstandings during translations from JLreq, e.g. middle dots (cl-05) in JLreq is a class including also colon and semicolon, but the current translation just translate it into Chinese interpunct, leaving no mention of colon or semicolon;

3. Colon and semicolon in Chinese have different behaviors from Japanese, which is not indicated in this section

**Comment by ryukeikun** [comment]
对于 3.1.6 建议修改为：
> 3.1.6 标点符号的宽度调整
> 中文的标点符号通常占一个（或多个）汉字的空间，使其在字间易于识别、适合配置及排版，有些排版风格完全不对标点挤压的宽度进行调整。但是，当执行行首行尾禁则时，或者要让文字体裁更加紧凑、易读时，都需要对标点符号的宽度进行调整。（注：在台湾，很多印刷品采用不调整的风格；而在中国大陆和香港的出版物中，多采取调整的风格，尽管各个出版社、作者的调整风格不尽相同。本文采取最常见方法进行阐述。）

（第二段可以保留）

关于 3.1.6.1 连续标点，目前的八点太繁琐。建议修改如下：

> 无论单个标点采用何种风格，当夹注符号与其他符号连续排列时，都应该进行调整，以使文字体裁更加紧凑、易读。调整的大原则是，应该让开始、结束夹注符号应紧靠被夹注的内容。具体方法如下：
> 1. 当单个夹注符号（单个开始、单个结束）遇到顿号、逗号、冒号、分号、句号、问号、感叹号时，无论二者前后关系，应缩减两者之间半个字宽空隙。
> 2. 当两个夹注符号连续出现时（无论是开始+开始，结束+结束，或者结束+开始），原则上应缩减两者间的半个字宽空隙。

这里的 1. 涵盖了原来的 1.2.3.
<img width="681" alt="屏幕快照 2019-07-03 20 42 52" src="https://user-images.githubusercontent.com/8192599/60589068-8665f580-9dd3-11e9-8628-62af539e8528.png">

这里的 2. 涵盖了原来的 4.5.6. 这是原文日文的总结缩写。「但是实际上，对于中文排版，一些印厂对于如「开始双引号+开始单引号」、「结束单引号+结束双引号」的情况会只缩减四分之一空。」这句话可以作为备注。
<img width="1077" alt="屏幕快照 2019-07-03 20 45 30" src="https://user-images.githubusercontent.com/8192599/60589090-97166b80-9dd3-11e9-967e-f196db2269d1.png">

以上两条应该没有问题，需要复查港台居中标点的情况。

问题是原来的 7.8. 应该是
> 3. 对于间隔号，当其出现于结束夹注符号之后或开始夹注符号之前时，应缩减其间四分之一个字宽空隙。

但这句话是照搬日本规范而不是中文规范。港台的间隔号是全宽（3a），而中国 GB 规定间隔号本身就是半宽（就是已经挤压掉前后的四分空的状态，3b），如果与其他连续出现的话，「缩减两者之间的半个字宽空隙」就会有两种方式，如 3c 和 3d，需要讨论。

<img width="776" alt="屏幕快照 2019-07-03 21 01 29" src="https://user-images.githubusercontent.com/8192599/60590036-f2e1f400-9dd5-11e9-9f72-e4a3fcaee0c7.png">

**Comment by xfq** [comment]
本 issue 只包括重写 [§ 3.1.6](https://w3c.github.io/clreq/#compression_rules_for_consecutive_punctuation_marks) 的开头部分及 [§ 3.1.6.1](https://w3c.github.io/clreq/#h-compression_of_adjacent_punctuation_marks)，并不修改 § [3.1.6.2](https://w3c.github.io/clreq/#h-compression_of_punctuation_marks_at_line_start) 是吗？

**Comment by upsuper** [comment]
> 当单个夹注符号（单个开始、单个结束）遇到顿号、逗号、冒号、分号、句号、问号、感叹号时，无论二者前后关系，应缩减两者之间半个字宽空隙。

可以修改为比如说“如有半个字宽的空隙，则应缩减”，这样对于标点居中的情况就不需要另外排除，也可以解决像`“。。。”`这样（前引号和句号之间）不存在空隙的特殊情况？

**Comment by RuixiZhang42** [comment]
[3.1.6.1](https://w3c.github.io/clreq/#h-compression_of_adjacent_punctuation_marks) 第七、八条提到「间隔号」，而英文却是「solidus」，应当改为「interpunct」。

日本规范将「结束夹注号」、「间隔号」、「开始夹注号」一律视为「半身宽」，在 [jlreq 3.1.4](https://www.w3.org/TR/jlreq/#positioning_of_consecutive_opening_brackets_closing_brackets_comma_full_stops_and_middle_dots) 的 g 跟 h 里提到的「在间隔号前后各加一个四分空」，最后效果其实是「半身结束夹注号」「全身间隔号」「半身开始夹注号」：

![compress](https://user-images.githubusercontent.com/39968857/74702953-ac60ce80-51d9-11ea-8d9a-21edc8e53d9a.png)

以上第二行（港台）与第三行（大陆方案一）对应 [@ryukeikun 的&nbsp;3d](https://github.com/w3c/clreq/issues/221#issuecomment-508055215)，而第四行（大陆方案二）对应&nbsp;[3c](https://github.com/w3c/clreq/issues/221#issuecomment-508055215)。

**Comment by himorin** [comment]
hi, 日本规范 does not 两端各加四分空, but similar to what 港台规范. All of original glyph has 1em but not half em - remove 1/2em (in total) spacing from punctuation (solid setting) and put spacing in between (1/4em by default, could be used for justify).

'Solid setting' in https://w3c.github.io/jlreq/#fig2_13 does not mean to use 1/2em glyph, but remove half em spacing within all punctuation in 1em glyph - as specified in css-text-4 processing.
/cc @kidayasuo (we might be better to have some more text in English?)

**Comment by RuixiZhang42** [comment]
@himorin 
> hi, 日本规范 does not 两端各加四分空, but similar to what 港台规范. All of original glyph has 1em but not half em - remove 1/2em (in total) spacing from punctuation (solid setting) and put spacing in between (1/4em by default, could be used for justify).

I understand. In my example, I actually used U+30FB Katakana Middle Dot for the first row (日本规范), which of course had full 1em width. My point is to demonstrate how to go from “Japanese solid setting” to “the end result”, not to explain how to “remove a total of 1/2em for full-width punctuation marks”.

Essentially, we have the following Japanese layout producers:
```
Removing 1/2em space (in total) -> Solid setting -> Add space back
```
My 日本规范 illustration only focuses on the latter half of the above procedures. Otherwise, the discussion would become too convoluted. For Japanese, it is subtracting space to get solid first, then adding space back for adjustments.

I don’t think China (mainland), Taiwan and Hong Kong have the notion of “solid setting” (not in current official documents that I am aware of), so skipping the “subtraction” part seems more appropriate.

**Comment by xfq** [comment]
Agreed. In JIS X 4051 § 4.2:

> 始め括弧類，終わり括弧類，中点類及び句点類の字幅は，半角とする。

@himorin Since Chinese does not have this process and every punctuation is full-width by default, there is no need to add space, so only removing/compressing (1/2 or 1/4 em) space is needed.

**Comment by RuixiZhang42** [comment]
@ryukeikun @upsuper
我其实并不赞同「缩写、合并」目前的八条规则。它们作为规则，应该一条一条地被列出来，并且详细说明具体的挤压操作。「如有半个字宽的空隙，则应缩减」这句话当然是概括得非常到位，但是如果只留下这一句话，就会不可避免地引起「理解偏差」（例如：如何判断「有半个字宽的空隙」呢？）。例子如下图：

> ![problem](https://user-images.githubusercontent.com/39968857/75275331-5dff9100-57d2-11ea-8746-8716c8f61472.png)
> 港台「不喜欢」贴着字框做标点，所以，「前一个居中的、体积小的标点+后一个不靠边的标点」很容易产生大于二分空的空隙，那么是不是按照「一句话规则」就要挤压呢？

---

@xfq 
在我看来，第&nbsp;3.1.6.1&nbsp;节的第一条规则反而是需要扩充说明的。In my opinion, the first rule in Section&nbsp;3.1.6.1 should be *extended* (instead of being merged with other rules).

The first rule should simply say:

> Rule&nbsp;1: **In common rules of Chinese Mainland, when a closing bracket appears behind a slight-pause comma, comma or period, the space can be reduced by half a character width.**

> ![rule1](https://user-images.githubusercontent.com/39968857/75273276-46260e00-57ce-11ea-9b1b-22c27fe23f15.png)

Then, I propose *adding* two sub-rules:

> Rule&nbsp;1(a): **For Chinese Mainland horizontal layout, when a closing bracket appears behind a colon, semicolon, question mark or exclamation mark, the space can also be reduced by half a character width. But no adjustments are made for vertical layout.**

> ![rule1a](https://user-images.githubusercontent.com/39968857/75277828-c94b6200-57d6-11ea-9e21-ed6201f5b18d.png)

> Rule&nbsp;1(b): **For Taiwan and Hong Kong, when a closing bracket appears behind a slight-pause comma, comma, period, colon, semicolon, question mark or exclamation mark, no adjustments are made for either horizontal or vertical layout.**

> ![rule1b](https://user-images.githubusercontent.com/39968857/75278203-702ffe00-57d7-11ea-9e9d-e588ca53ebd3.png)

**Comment by ryukeikun** [comment]
@RuixiZhang42 

按照铅字的传统，居中标点（正如日文的中点类「・」一样），标点本身字面依旧为半身（二分），并将左右各四分空提供出来用于压缩；而夹注符号也是本身占半身，提供单侧二分空供压缩。字型厂商可以不必「贴着字框」做标点，但至少应该保证标点的实际字面占二分，留下空隙给用户代理作为挤压空间。

![75275331-5dff9100-57d2-11ea-8746-8716c8f61472](https://user-images.githubusercontent.com/8192599/81259284-99d89180-9072-11ea-9920-0bcb77932aa2.png)

**Comment by ryukeikun** [comment]
@RuixiZhang42  @xfq
叙述「无需调整」已经在此节 3.1.6 言及，因此作为下层的 3.1.6.1 小节只要叙述「如果调整」应该调整什么地方即可。因此 @RuixiZhang42 建议的 Rule 1(b) 其实可以省去。

整个逻辑是，3.1.6 总述先说明「可以调，可以不调，这属于排版风格。港台有很多不调。」
然后其下 3.1.6.1 说明如果要调可以调什么地方。特别注意的是，居中式的标点如果要调也是可以调的，特别是在铅字时代竖排也有很多调整实例，而不是 @RuixiZhang42 建议的 Rule 1(b) 那样完全否认「在港台横竖排都不调整」，这不符合实际情况。

**Comment by ryukeikun** [comment]
建议行文修改第二版如下：

> 3.1.6 标点符号的宽度调整
> 标注在字间的标点符号（除乙式括号、破折号、省略号以外）通常占一个汉字宽度，使其易于识别、适合配置及排版，有些排版风格完全不对标点宽度进行任何调整。但是为了让文字体裁更加紧凑易读，以及执行行首行尾禁则时，就需要对标点符号的宽度进行调整。是否调整取决于对排版风格的判断，台湾的很多印刷品都采用不调整的风格；而在中国大陆和香港的出版物中，多数采取调整的风格。标点符号宽度调整通常分为两种情形：1. 标点符号连续出现 2.标点出现在行首或行尾。调整时的风格不尽相同，下文仅阐述基本原则。

> 3.1.6.1 标点符号可供调整的「调整空间」
> 标点符号分为「不可调整」「可调整」两类，「可调整」再根据调整空间分为六类：横排字面左、横排字面右、横排左右两侧；竖排字面上、竖排字面下、竖排上下两侧。
<img width="1035" alt="屏幕快照 2020-05-07 19 47 02" src="https://user-images.githubusercontent.com/8192599/81286145-90175400-909b-11ea-8493-e9ccae14c95e.png">

> 不可调整的标点包括：中国大陆GB式的半字连接号、间隔号、分隔号，因为这几个标点固定半个字宽；横排的港台式问号、感叹号和直排的冒号、分号、问号、感叹号（包括GB偏靠式和港台居中式），因为这几个标点固定一个字宽。

> 3.1.6.2 连续标点符号的调整
> 无论文本整体采用何种风格，当夹注符号与其他符号连续排列时，或者夹注符号重复出现（如开始+开始，结束+结束，或者结束+开始）时，都应该进行「基本挤压」调整，以使文字体裁更加紧凑、易读。
> 原则上的调整度应为：如果两个符号占用2个字宽，应当缩减成1.5个字宽。在此原则上，允许排版风格进一步调整让两个符号只占1个字宽。
> 挤压方向判定：原则上应该让开始、结束夹注符号应紧靠被夹注的内容。推荐组合详情见表格。

表格可以列举，待后期更新。

**Comment by r12a** [comment]
I just raised a related question in https://github.com/w3c/clreq/issues/295 about colons and semicolons.  Maybe @ryukeikun just answered that question in the above comment, at the same time as in was asking it?

**Comment by xfq** [comment]
> 无论文本整体采用何种风格，当夹注符号与其他符号连续排列时，或者夹注符号重复出现（如开始+开始，结束+结束，或者结束+开始）时，都应该进行「基本挤压」调整，以使文字体裁更加紧凑、易读。

这里是否需要定义一下「基本挤压」？

**Comment by RuixiZhang42** [comment]
@xfq 
>这里是否需要定义一下「基本挤压」？

这正是我在 https://github.com/w3c/clreq/issues/221#issuecomment-591014539 提出的观点：写得太笼统，则会引起歧义或者理解偏差。

@ryukeikun 也误会了我的本意。我说「在港台横竖排都不调整」，是指「在自然状态下，不需额外调整」。以下图为例：
![punctstyle](https://user-images.githubusercontent.com/39968857/85228463-87f84700-b3b1-11ea-9adf-59de7cc44294.png)

本例就体现了「如果『基本挤压』定义含糊，就会出现歧义」的观点。在这个例子中，「句号+右括弧」属于「夹注符号与其他符号连续排列」，但是
1. 简中和日文，一般会做「基本挤压」调整，即「在自然状态下，拿掉句号后面的二分空，使之只占半角」。而右括弧后面的二分空则用于行中调整，需要推进时，就可以挤压这个二分空。
2. 繁中，**则不做「基本挤压」调整**，即「在自然状态下，句号看上去占全角」。如果需要推进，则挤压句号前后的两个四分空、也挤压右括弧后面的二分空。

我说的「在港台横竖排都不调整」，指的是「自然状态下不做『基本挤压』调整」；而 @ryukeikun 说的「也可以调整」，指的是「需要行中调整时，哪些是可以挤压的地方」。
![punctstyle2](https://user-images.githubusercontent.com/39968857/85229245-9dbc3b00-b3b6-11ea-90fc-7198c5c48a6d.png)

**Comment by ryukeikun** [comment]
> > 无论文本整体采用何种风格，当夹注符号与其他符号连续排列时，或者夹注符号重复出现（如开始+开始，结束+结束，或者结束+开始）时，都应该进行「基本挤压」调整，以使文字体裁更加紧凑、易读。
> 
> 这里是否需要定义一下「基本挤压」？

为了行文简洁，不要节外生枝地新造概念，建议删掉这个「基本挤压」，将原文改成

……**都应该进行原则调整**，以使文字体裁更加紧凑、易读。**原则调整的度**为……
