### ISSUE TITLE
基本樣式相關改進

### ISSUE THREAD

**Issue by ethantw** [w3c/clreq#23]
- [x] 避免使用偽斜體漢字
- [x] 注釋背景過於醒目
- [x] 小節內容改用ordered lists便於定位
- [x] 縮小lists內的標題、段落間距
- [x] 表格調整

還有一個與樣式較無關的問題，目前的注釋id自原始頁面由腳本自動生成，後加入的內容已打亂其id排序，也沒有對注釋加入閱讀編號，引用時會比較麻煩。

**Comment by siusin** [comment]
我新加入的注释已经把id删除了，要不直接把所有注释的id都删除？文档里面应该没有对单一注释对引用吧？

**Comment by ethantw** [comment]
我翻了一些W3C的TR文檔，注釋大都沒有獨立的id，那就統一拿掉吧 :hammer:

**Comment by ethantw** [comment]
調整得應該差不多了，未來若有樣式相關改進需求再開新issue吧。
