### ISSUE TITLE
text-spacing 的默认值 space-first 问题

### ISSUE THREAD

**Issue by hax** [w3c/clreq#236]
在看 #230 时看到一个`text-spacing`特定的issue：https://github.com/w3c/csswg-drafts/issues/2462

如果我理解没错，日本同学提议以 `space-first` 作为默认值，行为是：起始括号等在行首用半角但段首除外（段首用全角）。

中文排版中常见这样吗？

感觉上，中文排版如采用段首缩进两字，就不需要额外的段首全角特例。如果不使用段首缩进，一般会使用空行来区分段落，也不需要段首全角特例。

所以如果以`space-first`作为默认值是否会对中文排版有影响？

**Comment by ryukeikun** [comment]
从中国大陆正统的正文排版习惯来说，的确不需要「段首全角」的特例。包括人民出版社、人民文学出版社等各大出版社，对于段首的引号均执行「半宽」的做法。

所以对应到此项，用`trim-start`即可满足要求中文排版需求。
目前的草案也注明 `space-fist` is not recommended for general authoring use. 所以有需要的日本用户可以使用此项，但中文不必。

**Comment by xfq** [comment]
In [§ 3.1.6.2 Compression of punctuation marks at line start or line end](https://w3c.github.io/clreq/#id101):

> For the case of line head indent, if an opening bracket is set at the beginning of the first line of the paragraph, half a character space can be reduced ahead of the bracket.

With `text-spacing: space-first`, the "can be reduced" will become "must not be reduced", so it does not conform to the typographic conventions in Mainland China.

Closing this issue.
