### ISSUE TITLE
「两个省略号连用」的分离禁则

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#25]
3.1.5.a 所述「两个省略号连用时，占四个漢字位置并须单独占一行」，援引《GB/T 15834—2011》。

这条规则得以成立的前提是，省略号的使用者须严格遵循《GB/T 15834》所定义的标号使用规范。该「规范」定义了「十二连点」所标示的是「诗行、段落的省略」。

在通用实践里，「两个省略号连用」完全有可能出现在「行内」；因此《GB/T 15834》所规定的书写形式，似乎不宜列入通用排版需求的「分离禁则」。

**Comment by bobbytung** [comment]
的確，台灣的標點符號手冊也未強制要求禁止分離。
煩請 @ethantw 修正。

**Comment by ethantw** [comment]
直接把該規則拿掉？還是稍做修改？（呼叫一下 @ryukeikun）

**Comment by ryukeikun** [comment]
这规则的确援引《GB/T 15834—2011》。我们先看原文：

> 4.11.3.7 在标示诗行、段落的省略时，**可**连用两个省略号（即相当于十二连点）
> 5.1.5 ……两个省略号连用时占四个字位置并**须**单独占一行。省略号不能中间断开分处上行之末和下行之首。

我觉得，这部分内容不应该删除，而是应该转移到我们 3.1.1 b. 里面去。

至于具体解读，GB 一直很暧昧。单纯字面来看，规定说
1. 两个省略号连用（12个点），「可以」用两个，但是非强制，也就是说用一个也可以。
2. 但一旦用了两个，「须」单独成行。很明显，原意是不能让三个点单独跑到行首。
那么六个点一起到行首怎么样呢？GB 没说，也许它觉得这本来就是不规范的用法，不是排版的问题了。

**Comment by ethantw** [comment]
瞭解了。「單獨占一行」其實就是我們所稱的「禁則」，而非要求12個省略點自成一個段落（行）。這樣一來，放在3.1.5我覺得也沒什麼問題，只是需要rephrase成《需求》的慣用語。

> 《標點符號用法》（GB/T 15834–2011）5.1.5節还规定，两个省略号连用时，占四个漢字位置，**並不得拆分至上下二行。**

這樣如何？

**Comment by realfish** [comment]
《GB/T 15834》说的「须单独占一行」，指的就是「单独成行」或「单独成段」的意思。因为这条书写规则并非独立出现，而是建立在十二连点的用法之上：

> 在标示**诗行**、**段落**的省略时，可连用两个省略号。

<br>
相应地，《15834》在描述通常意义上的「分离禁则」时是这样表述的：

> 省略号不能中间断开分处上行之末和下行之首。

值得注意的是，《15834》未曾指明过省略号的「中间断开」是否是以三点为一组的断开；换言之，《15834》并不明确讨论中文标点符号在计算机字符层面的构造及实现方法。这一点，破折号的情况（de facto 双字符标点）是类似的。

<br>
所以，以上其实有两个问题：
1. 十二连点单独成行，严格来说是比「分离禁则」更强的一条书写规则——就视觉结果而言，它首先要求十二连点不分离，同时要求清空符号所在行的首尾。
2. 《GB/T 15834》描述的十二连点单独成行，更像是一种要求作者主动进行的分段 / 换行的操作。比起**排版规则**而言，它更像是一种**写作 / 书写指导**。

**Comment by bobbytung** [comment]
> 《標點符號用法》（GB/T 15834–2011）5.1.5 还规定，两个省略号连用时，占四个漢字位置并须单独占一行。

例如：
潯陽江頭夜送客，楓葉荻花秋瑟瑟。
⋯⋯⋯⋯
千呼萬喚始出來，猶抱琵琶半遮面。

指定由四個漢字位置、12連點構成「句」的省略，的確偏向於編輯體例。但無論如何，使用時必須單獨成行，且中文書不會遇到每行小於四個字的狀況（笑）。所以，雖有規定，但與3.1.5.a符號分離禁則的處理不符合。這裏不需提及。
