### ISSUE TITLE
'Character dimension' -> 'character frame'

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#251]
There are 6 occurrences of the term 'character dimension' in the text, which i think should read 'character frame' instead.

**Comment by r12a** [comment]
The text around the term mentioned above probably also needs revisiting. Here are my suggested rewrites of the sentences affected.

https://w3c.github.io/clreq/#line_composition_rules_for_punctuation_marks
> The usage of Chinese punctuation marks differs across different regions. One major difference is how the letter face is positioned relative to the character frame and handled. Punctuation marks are usually center-aligned in the character frame in Taiwan and Hong Kong, while punctuation marks are positioned in the corner of the character frame on the side closest to the preceding text in the Chinese Mainland. The differences and the correct ways to layout punctuation marks in different areas will be introduced in detail later.

https://w3c.github.io/clreq/#glyphs_sizes_and_positions_in_character_faces_of_punctuation_marks
> There are no notable differences among different areas in the glyphs of punctuation marks. The major differences are their sizes and where the letter faced is positioned relative to the character frame.

https://w3c.github.io/clreq/#hanging_punctuation_marks_at_line_end
> In Simplified Chinese, all the pause or stop punctuation marks can be hung at line end since they are positioned at the starting point of the character frame.

https://w3c.github.io/clreq/#composition_of_chinese_and_western_mixed_text
> The way glyphs are positioned relative to the character frame follows the Western convention for both Simplified and Traditional text.

**Comment by xfq** [comment]
I think the suggested rewrites are indeed a better translation of 字面分布. @r12a would you please submit a pull request for this?

**Comment by macnmm** [comment]
I use "ideographic embox" or "CJK embox" for this. "Virtual Body" is also used in Japanese （仮想ボディー）

**Comment by r12a** [comment]
'character frame' is defined in jlreq and adopted into clreq too for the outside box.

However, i found it more difficult to find a way of saying 'the bit of the character frame that contains ink'.  I used 'letter face' (defined again in jlreq & clreq as a smaller box containing the letter itself, though that's slightly vague – does it just include the squared boundaries of the area containing ink (vertically and horizontally within the character frame) for the ideographic full stop, for example?), and in one place left 'glyph' but wasn't sure if those words were accurate enough.

**Comment by macnmm** [comment]
glyph bounding box < ideographic [average] character face < ideographic embox

**Comment by macnmm** [comment]
for punctuation, we have to get specific about the width relative to the embox, I think. Character face terms can vary widely in what they are talking about.

**Comment by xfq** [comment]
As @r12a said, "character frame" is used in jlreq (文字の外枠 in Japanese) and clreq (文字外框 in Chinese) for the rectangular area occupied by a character when it is set solid.

"Letter face" is also used in jlreq (字面 in Japanese) and clreq (字面 in Chinese) for the area contains ink.

And clreq introduced a new term called 字面分布, which means how the letter face is positioned relative to the character frame, and this concept does not exist in jlreq. IIRC jlreq just uses "文字の外枠の...字面を配置する" or "文字の外枠に対する字面の配置位置" for this.

**Comment by ryukeikun** [comment]
@xfq  Maybe 字面位置（glyph/face positioning [inside Character Frame]）is better than current 字面分布，(glyph/face distribution)?

**Comment by xfq** [comment]
@ryukeikun Both look good to me, but this issue is mainly about English translation rather than the wording in Chinese, so I suggest that we discuss it in a separate issue.
