### ISSUE TITLE
破折号描述里的歧义

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#260]
https://w3c.github.io/clreq/#id82 :

> 破折号表示语气或声音的延续、语意的转换或行文的补充。为占二个汉字空间的 `U+2E3A TWO-EM DASH [⸺]` 或 `U+2014 EM DASH [—]`。

第二句话有歧义，不清楚「占二个汉字空间的」只修饰 `U+2E3A`，还是修饰后面的两个码位。

**Comment by ryukeikun** [comment]
问题的原因是[「破折号到底是一个字（码位）还是两个字（码位）」的问题](https://thetype.com/2019/03/14918/#pozhehao-twoem)， 现在这个歧义的行文似乎是之前讨论的结果。如果要改清晰一点，是不是应该这样？

> 破折号表示语气或声音的延续、语意的转换或行文的补充。呈现上为一条居中的横杠，占二个汉字空间。 推荐使用占两个汉字宽度的 U+2E3A TWO-EM DASH [⸺]，但通常也使用两个连续的 U+2014 EM DASH [—]来实现。

**Comment by xfq** [comment]
这样确实清晰一些。另外，「二个」是否改为「两个」比较好？

**Comment by xfq** [comment]
我提交了一个PR：https://github.com/w3c/clreq/pull/266

**Comment by stone-zeng** [comment]
这里的「占两个汉字空间」与后面 U+2E3A「占两个汉字宽度」是否有重复？
