### ISSUE TITLE
关于 2.4.2.d

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#27]
### 2.4.2.d.1

> 直排時，順其行文結束，各欄左右行數可以不一致。

此处「各欄左右行數」似乎是 typo？根据上文推断，是否应为「上下各欄行數」？

<br/>
### 2.4.2.d.2

> 橫排時，各欄的行數需平均。但因字數不足，行數無法與欄數配合時，不足的行數於最後一欄末尾留空。

就大陆地区的横排实践而言，「平均各栏行数」应该仅是某一种特定的排版偏好（optional），似乎不足以构成普遍的排版惯例（conventional）。

<br/>
### 关于平均各栏行数

平均各栏行数的目的，是保证各栏的「视觉长度」尽可能一致。

因此，平均各栏行数通常有一个设计前提是段落密排，也即没有额外段间距；否则，以「行数」为基准来实现平均计算，通常难以得到理想的视觉平均效果。当下中文排版实践中，段间距已获得普遍应用（甚至有不少设计者在段首缩进的同时，叠加使用段间距）。

此处是否值得加注一笔？

**Comment by bobbytung** [comment]
## 2.4.2.d.1

是的，這裏應該修正為：

> 直排時，順其行文結束，各欄上下行數可以不一致。

## 2.4.2.d.2

這裏主要從JLREQ而來，圖示如： http://www.w3.org/TR/jlreq/ja/Images-ja/img1_25.png
就我編排雜誌的經驗，盡量會讓兩欄於最末頁齊行。希望 @realfish 提供一些簡體書的範本。
如果橫排也可不齊行，那麼2.4.2.d主要講的是直橫排差異，可整段刪除。

補上我手邊有的書的範例：
1. 按照2.4.2.d敘述，橫排雙欄行數一致：
   http://www.dropbox.com/s/lk70nuukd6ft6qe/IMG_0030.JPG
2. 雙欄行數不一致，但作者資料作為Box元素補齊行數差：
   http://www.dropbox.com/s/haah5zvgw36tp0k/IMG_0031.JPG

**Comment by realfish** [comment]
一时难以收集权威文献，手边只有一些孤证供临时参考：
1. 《离线·开始游戏》（Offline No.001，电子工业出版社），设计师杨林青是《第一财经周刊》的前任设计师，也为三联书店、世纪文景等出版机构工作。
2. 《知日·书之国》（ZHI JP No. 4，凤凰出版社），该刊物有不少版面刻意使用非平均的双栏排版。

![offline](https://cloud.githubusercontent.com/assets/3247876/7091136/2cd75a74-dfda-11e4-8b51-ad2b35d0b5d6.JPG)
![zhijp](https://cloud.githubusercontent.com/assets/3247876/7091141/34401c42-dfda-11e4-8cab-f5a530660bf5.JPG)

---

补充一例：

有一定学术性、并在版式设计方面具有一定示范效应的文字设计类译著《西文字体——字体的背景知识和使用方法》（中信出版社），设计师陈嵘，译者是 CLReq 编委之一的 Eric :)

![img_5040](https://cloud.githubusercontent.com/assets/3247876/7094401/7d88bd6e-dff3-11e4-8a93-9f36558dac20.JPG)

**Comment by bobbytung** [comment]
我覺得2.4.2.d不完全適用於中文，整段刪除。
其他編輯 @ethantw 覺得如何？

**Comment by ryukeikun** [comment]
既然在分栏方面横排与直排没有差别，我赞成把 2.4.2.d 直接删掉。

**Comment by bobbytung** [comment]
- [ ] 刪除2.4.2.d
