### ISSUE TITLE
关于科技文献的句号、逗号

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#28]
#### 3.1.1.a：注 1

> 許多理工書籍、科技文獻、西文教科书语法书籍等內含大量西文詞句、並採用橫排，為求標點符號體例一致，也有採用`[.](FULL STOP)`為句號、採`[,](COMMA)`為逗號與頓號的案例。詳見3.1.3節。

上文与 3.1.3  描述科技文献句号时所指涉的字符不一致，后者所用的 `[．](FULLWIDTH FULL STOP)` 应该更值得推荐。另外，与 `FULLWIDTH FULL STOP` 搭配使用的逗号应该推荐 `FULLWIDTH COMMA (U+FF0C)`，不必转为 `COMMA (U+002C)`。

---

补充：3.2.1 末尾也有提及科技文献的句号，问题同上。

**Comment by ethantw** [comment]
當作「頓號」使用時，好像使用半形的`[,](COMMA)`比較多見？

**Comment by ethantw** [comment]
改成以下描述是否合理？

> 許多理工書籍、科技文獻、西文教科书语法书籍等內含大量西文詞句，並採用橫排，為求標點符號體例一致，也有採用`[．](FULLWIDTH FULL STOP)`為句號、採`[,](COMMA)`或`[，](FULLWIDTH COMMA)`為逗號與頓號的案例。

**Comment by realfish** [comment]
> 當作「頓號」使用時，好像使用半形的 `[,](COMMA)` 比較多見？

啊，这个现象我倒没考虑……推理来看，我倾向于认为：
- 科技文献混用逗号和顿号的情况比其他文献更多见（可能是作者不够注意体例，也可能故意不用顿号）；
- 在印刷品中见到的 half-width comma，很可能是标点挤压的样式所造成。

不过我编排中文科技文献的经验很有限，以上仅供参考 :)
