### ISSUE TITLE
Add page format in Glossary?

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#282]
In https://w3c.github.io/clreq/#type_area :

> First, prepare a template of the page format, which determines the basic appearance of document pages.

Maybe we should add a Glossary entry to explain what page format is.

jlreq has one: https://w3c.github.io/jlreq/#term.page-format

**Comment by ryukeikun** [comment]
The term「Page format / 組体裁」should be排版样式 in Chinese. Cf. 「体裁」in Japanese means format but means "literary form" in Chinese. All 体裁 word in current Clreq should be  changed into 样式.

page format | （页面）排版样式| The layout and presentation of a page with text, graphics and other elements for a publication such as a book. 书籍等出版物上图、文及其他元素的版式布局及表现形式

**Comment by xfq** [comment]
Thank you! Fixed in https://github.com/w3c/clreq/commit/f1224dc5e51e96c57d325d3022585a36e6fbbff3
