### ISSUE TITLE
Cleaning unnecessary "Notes"

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#284]
There are too much "Notes" in current version, need to be cleaned, either deleted, or merge into body text, here are some lists that I propose:

§ 2.1.1 
Note 1 is better to be main body text instead of note.

§ 2.2.3
Note for Kaiti is better to merge into the paragraph above.

§ 2.3.5.3 should be merged into the line above.
§ 2.3.5.4
Note 1 is important for Ruby layout, so better written into body text instead of note.

§ 2.4.2 
Note 1 and 3 can be changed into main text.

§ 3.1.1.2.8  书名号 
Note should be merged into the second paragraph.

§ 3.1.1.2.9  专名 
Note should be merged into the first paragraph

§ 3.1.5.1 
Note can be delete 

§ 3.3.3.3.3
This note is actually explaining what is 轻声, not necessary here, can be deleted.

§ 4.1.1 
There are 5 notes here, note 2, 3, 4, 5 should be rewritten and merged into main text.

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/commit/65fef82e99d0c1c7482b082978b0e762923c7316
