### ISSUE TITLE
添加「两端对齐」？

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#287]
https://w3c.github.io/clreq/#ways_of_alignments

这里提到了居中对齐、行首对齐、行尾对齐、均等排列，但是好像没有提到常见的「两端对齐」？

**Comment by yoonhakcher** [comment]
「均等排列」即是。

**Comment by xfq** [comment]
明白了，谢谢。这里感觉不太明确。文本中的「未满一行时，空白平均置于该行各字间」容易让人理解为段落末行时未满一行时的情形，而「两端对齐」通常是指除了段落中最后一行以外的其它行两端对齐，正如后文所说的「段落末行或段落仅有一行 时则不使用均等排列」一样。

感觉文本可以改写得更清晰一些，也可以直接提到「两端对齐」。
