### ISSUE TITLE
字体范例的选择

### ISSUE THREAD

**Issue by Buernia** [w3c/clreq#29]
2.2节中的字体范例图像，所展示的字体不知道是以何种标准选择的（也许是直接从系统或软件预装字体中选取而来）。个人感觉效果不佳。在此提出一些看法，见笑。
个人认为字体范例的选取应使用较常见于印刷品中的字体。并且基于可能的“预装字体优先”的选择。我的建议如下（皆为简体中文范例的选择）：
（括号内为其它备选项，标注等号的字体名为与推荐选项中文字形相同但文件不同的字体）
宋体：
宋体-简 粗体或常规体（中易宋体，=华文中宋，方正书宋）——基于铅字宋二体的字体
方正宋体-超大字符集（=方正宋体）——基于铅字宋一体的字体
黑体：
黑体-简 中等（=华文黑体，=Adobe黑体，方正黑体）——基于铅字黑体的字体
微软雅黑（=方正兰亭黑）——大字面的现代黑体
思源黑体——字面介于前二者之间的黑体
楷体与仿宋体由于现有字体的字形高度一致，不作推荐。
另外：
字体范例字体似乎都经过了电脑加粗，不利于展示字体，望修正。
个人不太喜欢台湾教育部标准字形，建议使用旧字形的字体来展示繁体中文。
以上，不当之处请指正。

**Comment by Buernia** [comment]
(手滑按了回车键，续。)

楷体与仿宋体由于现有字体的字形高度一致，不作推荐。
另外：
字体范例字体似乎都经过了电脑加粗，不利于展示字体，望修正。
个人不太喜欢台湾教育部标准字形，建议使用旧字形的字体来展示繁体中文。
以上，不当之处请指正。

**Comment by ethantw** [comment]
> (手滑按了回车键，续。)

![2015-04-10 21 21 07](https://cloud.githubusercontent.com/assets/31068/7088594/8e86bcd2-dfc7-11e4-9b20-2fbda5503cfa.png)

可以透過右上角的「筆」來修改issues或comments內容哦。

**Comment by bobbytung** [comment]
字體圖例需要重新製作，我覺得原則為：
- 兼顧簡繁
- 表示大陸、香港、台灣的字形差異
- 包含字體內常見的設計差異

## 宋/明體
- 方正宋一（簡字、宋一體）
- 中易宋（簡字、宋二體）
- 新細明體 或 儷宋（繁字）
- 宋體繁（繁字）

## 黑體
- 黑體簡（簡字）
- 微軟雅黑（簡字）
- 或 增加思源黑體（簡字）
- 黑體繁（繁字）
- 思源黑體（繁字）
- 或 增加微軟正黑體（繁字）

楷體依然使用楷體繁、楷體簡、標楷體，但差異不大。

仿宋除華文仿宋外， @Buernia 還建議哪些字體具代表性？

**Comment by Buernia** [comment]
> 可以透過右上角的「筆」來修改issues或comments內容哦。

初来 Github ，尚未熟悉使用方法，见谅。

> 仿宋除華文仿宋外， @Buernia 還建議哪些字體具代表性？

虽然现有电脑仿宋体设计高度一致，但是依据各地字形选取不同字体是有必要的。
港澳台的字体使用情况我并不清楚，王汉宗的仿宋体作为繁体范例如何？

**Comment by ethantw** [comment]
Done with https://github.com/w3c/clreq/pull/137
