### ISSUE TITLE
Chinese name for even inter-character spacing

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#290]
In [§ 2.1.3.2 Even inter-character spacing](https://w3c.github.io/clreq/#even_inter_character_spacing), the Chinese name for even inter-character spacing is 平均排列, but in [§ 3.4.3 Line Alignment Processing](https://w3c.github.io/clreq/#ways_of_alignments) it is 均等排列. We should unify them.

**Comment by ryukeikun** [comment]
相对于「密排」「紧排」「疏排」是出版行业的现成术语，这一点似乎没有现成术语，但是可以考虑「摊排」「匀排」「均排」「均匀排列」等说法，没有歧义即可。

**Comment by xfq** [comment]
Link to yesterday's discussions: https://www.w3.org/2020/09/16-clreq-minutes.html#t12
