### ISSUE TITLE
省略号的对齐

### ISSUE THREAD

**Issue by tanukihee** [w3c/clreq#302]
在省略号小节中，英文翻译部分并未把中文的「居中」给翻译出来

> Ellipses.
>
> 省略号／删节号
>
> 刪節號／省略號
>
> Ellipses are used to indicate a truncation of text, an unfinished sentence or a break in speech. An ellipsis in Chinese consists of six dots and takes up the space of two Hanzi characters. This is normally achieved using two U+2026 HORIZONTAL ELLIPSIS characters, side-by-side.
>
> 省略号又作删节号，表示节略原文、语句未完或语气的不连续。删节号呈现上占两个汉字空间、包含六个**居中**的省略点，通常使用两个连续的 U+2026 HORIZONTAL ELLIPSIS […] 来实现。
>
> 刪節號又作省略號，表示節略原文、語句未完或語氣的不連續。刪節號呈現上佔兩個漢字空間、包含六個**居中**的刪節點，通常使用兩個連續的 U+2026 HORIZONTAL ELLIPSIS […] 來實現。

导致有人按西文省略号的理解，认为中文省略号是偏下（横排）／偏左（竖排）的了。

![image](https://user-images.githubusercontent.com/34062491/82771012-3ec5dd80-9e6d-11ea-8a0d-4a98fd0cb1c0.png)
https://r12a.github.io/scripts/han/

**Comment by tanukihee** [comment]
中文描述中是否也要强调「（不论在横排还是竖排中，省略号）既要水平居中，也要垂直居中」？以横排为例，占两个汉字空间的、基线对齐的（左右）居中也算「居中」吧。

效果图对比
![image](https://user-images.githubusercontent.com/34062491/82905318-4fbe3e00-9f96-11ea-97af-0c6e58ffcea5.png)

**Comment by tanukihee** [comment]
借着省略号的位置，要不要同时强调一下（横排时）破折号的垂直居中？

>破折号表示语气或声音的延续、语意的转换或行文的补充。呈现上为一条**居中**的横杠，占两个汉字空间。

也是与省略号类似的共用码位的问题，中西文字体的设计有别，西文字体的 dash 肯定会更低
![image](https://user-images.githubusercontent.com/34062491/84357993-0fe39180-abf9-11ea-8c23-d10812274b19.png)

图片来源：[不离不弃的破折号](https://www.thetype.com/2019/03/14918/)

**Comment by xfq** [comment]
> 借着省略号的位置，要不要同时强调一下（横排时）破折号的垂直居中？

我开了一个新 issue 讨论这个问题：https://github.com/w3c/clreq/issues/310
