### ISSUE TITLE
標點符號於直排時的位置差異

### ISSUE THREAD

**Issue by bobbytung** [w3c/clreq#31]
按照GB/T15834-2011中，5.2.1的規範：

> 句號、問號、嘆號、頓號、分號與冒號均置於相應文字之下偏右。

這部分也反映於UTR#50的[範例](http://unicode.org/reports/tr50/)上。

關於這一點，的確於大陸繁體古籍竪排書上如此處理，使得這一點規定不是「簡繁」標點符號的差異，而是「地區排版習慣與規則」的不同。建議於下一版在3.2標點符號與其排版中加一節做詳細的說明。

這會與Locale（zh-Hant-CN, zh-Hant-TW, zh-Hant-HK），以及Unicode及字型實作有所影響，需要詳細說明。

**Comment by lianghai** [comment]
标点符号样式本来就完全是地区习惯不同的，和「简繁」问题无关。一切涉及标点样式的讨论都不应当用「简繁」来区分情况。
大陆竖排标点靠右上，不论简繁都如此，不仅仅是「大陸繁體古籍竪排書」的问题。
另外，「（对）Unicode及字型實作有所影響」指的是什么？

**Comment by bobbytung** [comment]
先寫下筆記，竪排（直排時）：
- zh-Hant-CN與zh-Hans-CN的標點從GB/T-15834，以及UTR#50的範例，置於文字下方偏右。
- zh-Hant-TW時，標點置中。
- zh-Hans-TW案例較少。

第一項我檢證一下目前的實作，在我記憶裡似乎沒依照LTLI做到這麼細的調整。之後再寫成敘述加入CLREQ修改。
