### ISSUE TITLE
The English name of 省略号

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#312]
The English of name of 省略号 is sometimes "ellipsis/ellipses", sometimes "horizontal ellipsis/ellipses". We should unify them.

**Comment by xfq** [comment]
I think the first one is better, because the second one (probably from the Unicode name) might make the reader feel that it can only be used in horizontal writing mode.

**Comment by ryukeikun** [comment]
I agree. It is better to use "ellipsis/ellipses".

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/commit/00bbb130a88b7f361e2e5171eebba69a5ce57dde
