### ISSUE TITLE
Need to improve § 3.4.3 Line Alignment Processing

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#327]
https://w3c.github.io/clreq/#ways_of_alignments

The current text of § 3.4.3 Line Alignment Processing is written base on [JLReq 3.5.3 Single Line Alignment Processing そろえの処理](https://www.w3.org/TR/jlreq/#single_line_alignment_processing), but with bad translation. e.g. the content of this section is actually only refer to SINGLE LINE paragraph, but this point is not mentioned at all at current text, making contradictions with other parts.

**Comment by ryukeikun** [comment]
> 对齐处理

→ 单行对齐处理

>对齐系指使段落间各行文字实际配置位置能够与默认的文字配置位置符合。

→ 此处的「单行对齐」是指针对行长比预定行长更短的单行文字进行对齐的处理。这种方法常用于并排项目、标题和诗词等等。

> 1. 居中对齐：行内文字原则上紧贴配置，文字列的中央与行的中央对齐排列，未满一行时，该行文字列对行首与行尾的空白量均等。

→ 1. 居中对齐：行内文字原则上**密排，但可以依据排版风格对中西间距和夹注符号进行调整。**文字列的中央与行的中央对齐排列，<del>未满一行时，该行文字列对</del>行首与行尾的空白量均等。
> 2. 行首对齐：行内文字原则上紧贴配置，文字列开头与行首位置对齐，未满一行时，该行末字至行尾使用空白。

→ 行首对齐：行内文字原则上**密排，但可以依据排版风格对中西间距和夹注符号进行调整。**文字列开头与预设行首位置对齐，<del>未满一行时，</del>该行末字至行尾使用空白。
> 3.  行尾对齐：行内文字原则上紧贴配置，文字列末尾与行尾位置对齐，未满一行时，该行首字至行首使用空白。

→ 3.  行尾对齐：行内文字原则上**密排，但可以依据排版风格对中西间距和夹注符号进行调整。**<del>未满一行时，</del>该行首字至行首使用空白。
> 4. 均等排列：行内文字原则上紧贴配置，文字列开头与行首位置对齐、文字列末尾与行尾位置对齐，未满一行时，空白平均置于该行各字间。

→ 均等排列：行内文字原则上**密排，但可以依据排版风格对中西间距和夹注符号进行调整。**文字列开头与行首位置对齐<del>未满一行时，</del>**然后按照行调整的拉伸处理原则，将空白平均置于该行各字间，让文字列末尾与行尾位置对齐。**

**Comment by xfq** [comment]
同意，我们也可以加上一张图对比一下这几种对齐方式。
