### ISSUE TITLE
"Former editors" in the Chinese version is unchanged

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#329]
After clicking 简体中文 or 繁體中文, the "Former editors:" header remains unchanged while other headers do change to Chinese. Not sure why...

/cc @r12a

**Comment by himorin** [comment]
script.js line 138, `    var originalText = $dt.dataset.originalText || $dt.textContent`  should be `    var originalText = $dt.dataset.originalText || $dt.innerText`?

**Comment by himorin** [comment]
sorry. no.. use `$dt.textContent.trim()` should be better...

**Comment by xfq** [comment]
Thanks for the hint @himorin - you are right indeed.

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/commit/c545424c6829da35c819f851e8f347fd91e75aea
