### ISSUE TITLE
版心中的“字间距”？- 来自金山WPS的反馈

### ISSUE THREAD

**Issue by lianqi** [w3c/clreq#33]
在“版心”设计元素中，是否还可以补充一个“字间距”，它的用途是让用户设置“每行允许显示的字数”？

**Comment by lianghai** [comment]
嗯，「字距」与「每行字数」（即「每行允许显示的字数」，文中现在的措词是「一行的長度（字數）」）二者是和「行距」与「每页行数」二者对称的，现在文中已经有后三者了，「字距」应当加上。

**Comment by ryukeikun** [comment]
added.
