### ISSUE TITLE
关于间隔号

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#339]
关于间隔号的描述，有几点疑问：

> 间隔号为U+00B7 MIDDLE DOT [·]。用于双书名号（书名号乙式）分隔篇、章、卷，以及外国人名中文译名、少数民族音译名，分隔姓名使用。

这里是否需要提一下分隔日期的用法？是否还有其他用法？

> 间隔号在繁、简中文间的用法有所不同，原则上繁体中文无论直排或横排，都占用一个汉字的大小；简体中文用于分隔日期（如 9·11）等情况时，可用半个汉字的大小。

这里的「等情况」指的是？

> 间隔号位于字面正中，占一个汉字的大小，直、横排方向一致。为了节省排版空间、使词组或数字较紧凑地排列，可以使用半个汉字大小的间隔号。

> 不可调整的标点包括：中国大陆GB式的半字连接号、间隔号、分隔号，因为这几个标点固定半个字宽

如果中国大陆GB式的间隔号是固定半个字宽，希望在间隔号的章节说明。

> 占一个汉字大小，可视情况改用半个汉字大小。

「视情况」指的是？

**Comment by NightFurySL2001** [comment]
中国国标 GB/T 15834-2011 《标点符号用法》内写明：
> 5.1.7 间隔号标在需要隔开的项目之间，占半个字位置，上下居中，不出现在一行之首。

**Comment by xfq** [comment]
Related discussions: https://www.w3.org/2020/12/16-clreq-minutes.html#t06
