### ISSUE TITLE
关于书名号

### ISSUE THREAD

**Issue by NightFurySL2001** [w3c/clreq#340]
请检查以下问题：
1. 部分提及中国国标 GB 的内容部分并未简转繁，请问是遗漏检查翻译吗？

> 简：根据中国大陆的《标点符号用法》（GB/T 15834—2011），无论书名、篇章名都应该使用双书名号[《》]，只有在书名号中还需要书名号时，里面一层用单书名号，外面一层用双书名号。甲式书名号（波浪底线）仅用于古籍。
> 繁：根據中国大陸的《标点符号用法》（GB/T 15834—2011），**无论书名、篇章名都应该使用双书名号[《》]，只有在书名号中还需要书名号时，里面一层用单书名号，外面一层用双书名号**。甲式書名號（波浪底線）僅用於古籍。

2. 《标点符号用法》（GB/T 15834—2011）内 5.2.4 建议直排时书名号应使用波浪底线/甲式书名号。
![image](https://user-images.githubusercontent.com/33471049/101888737-8299ed80-3bd9-11eb-9d7b-dfab91bbc8e1.png)

**Comment by xfq** [comment]
Related discussions: https://www.w3.org/2020/12/16-clreq-minutes.html#t05

**Comment by ryukeikun** [comment]
第一个问题，应该是繁简转换遗漏，应该修改。
第二个问题，国标里说竖排的书名号应该用波浪式，但是现实出版中采用双尖括弧式也不少。由于国标本身是推荐性质，所以本文档编辑并没有突出这一点。

我认为，对于竖排书名号使用双尖括弧式可以容忍，没有必要禁止。从设计样式上说，双尖括弧式和直角引号共存比较搭配；而波浪式与下划线式的专名号共存比较搭配，这属于风格问题。

![IMG_2933](https://user-images.githubusercontent.com/8192599/103065677-86c30380-45fa-11eb-9ca8-ee00644114ee.jpeg)
金城出版社，《礼乐01：大学之道》，2013年，北京
