### ISSUE TITLE
关于破折号的英文翻译

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#341]
目前在文档里大多译为em dashes，容易引起歧义，是否考虑修改为two-em dash或long dash？

欢迎其他建议。

**Comment by realfish** [comment]
「破折号」在语义上基本是对 dash symbol 的直译（[参考](https://old.pep.com.cn/xiaoyu/jiaoshi/study/jszy/bdfhyf/pozheh/201012/t20101202_980936.htm)）。

而 en dash、em dash、two-em dash 则是对 dash 符号视觉长度的区分描述，在这一点上，这组西文符号术语更适合对应到中文标点的「连接号」（此处选用 GB/T 15834 的术语）。晚近至 GB/T 15834—1995 中，连接号仍有三种长度的形式（此处暂不考虑「浪纹」）：

> 连接号的形式为“—”，占一个字的位置。连接号还有另外三种形式，即长横“——”（占两个字的位置）、半字线“–”（占半个字的位置）［…］。

在 1995 年版该份国标中，破折号另有定义。也即，破折号与连接号是语义作用不同的两个独立标点。

虽然经 2011 年修订后，连接号与破折号在形态和语义功能上被重新规划 / 简化（在 GB/T 15834—2011 中连接号事实上只有 `–` `—` 两种长度），但历史痕迹有助于我们辨析破折号与其他形态相近的标点符号之间的边界在哪里，为「破折号」这一名称的来源和翻译提供参考。

个人比较倾向于破折号另辟新的英文译名（例如 Pozhe symbol, Pozhehao），并在术语表或必要的注释中描述其形态为 two-em dash、其常见实践为「两个连续 em dash 不间断排列」，以此来明确破折号的语义和形态。

**Comment by acli** [comment]
中文的破折號英文就是 (grammatical) dash，實際排版使用的就是 two-em dash 。Em-dash 的確是誤譯。

英文不會叫 long dash，不建議這樣譯。

(理論上中文排版的基本單位並不是 em (中文實際用的單位我偏向叫 CJK space，但沒有人會這樣叫)，所以理論上橫排而字形並非正方時 two-em dash 並不完全正確，但 Unicode 中的 two-em dash 其實就是為了描述中文的破折號而特設的，所以其實沒有不寫 two-em dash 的理由。)

**Comment by realfish** [comment]
需要补充一点，2-em dash 和 3-em dash 依然是「西文标点」。

比如，这两个标点在英语行文中通常表示省略、删节，但日常使用较少。以 <cite>Chicago Manual of Style</cite> 为例，至今（17th edition）仍保留着这两个标点的使用指南，参考例句：

> Admiral N—— and Lady R—— were among the guests.
> [用 2-em dash 表示单词部分或全部的省略]

> Chaudhuri, Amit. Odysseus Abroad. New York: Alfred A. Knopf, 2015.
> ———. A Strange and Sublime Address. London: Minerva, 1992.
> [在 bibliography entry 中，用 3-em dash 表示作者列表与上一条相同]

需要注意，Unicode 的 U+2E3A 和 U+2E3B 更少用。即便在上述例句中，CMOS 也没有要求或推荐使用这种特殊字符来书写 2-em/3-em dash，而是用重复多个 em dash (U+2014) 来表示。

**Comment by xfq** [comment]
相关Unicode提案：https://www.unicode.org/L2/L2010/10037r-longdashes.pdf

**Comment by acli** [comment]
Two-em dash 和 three-em dash 在英文的角度，是否標點並不能一概而論，很多人並不認同它們是標點，即是說它們在文法上並不存在，只是排版用的符號

至於 CMOS 怎樣說，我只能說 CMOS 是很好的權威，但不能䀆信，CMOS 中有錯的部份。我是應該是少數指出 CMOS 有錯的人，但我知道有資深、傳統排版出身的人都說 CMOS 有錯。

英文的排版傳統中，three-em dash 正確點說可以是 three-em rule，只要你有辦法排出3 個em 寛度，不斷續的直線，便是正確。使用三個 em rule 排出一個 three-em rule並不違背這個傳統  (事實上，在鉛字排版時，這應該是正常的做法），只是現在很多字型的 em dash 都有 non-zero sidebearing，你不能確定這樣排出來沒有斷續。中文的情況也是一樣，要排出的是 two-em rule，技術上你是用一個 two-em rule 字元還是兩個 em rule 字元都沒有違背傳統，但你要確定排出來的是沒有斷的單一條直線。

**Comment by acli** [comment]
當然，如我之前說的，叫中文的破折號做 two-em dash 並不完全正確，但理由和它是否「西文標點」無關，而是 em 的定義和「中文字寛/高度」並不完全對應，但如果我們接受「中文字」和「em」大致上對應，中文的破折號絕對是 two-em dash（而且絕對不是 em dash）

**Comment by realfish** [comment]
2-em/3-em dash 是否被英语使用者认可为标点符号，不属于 CLReq 的讨论主旨。但可以明确的是，「Unicode 中的 two-em dash」并非「為了描述中文的破折號而特設」，辨析这个概念有助于 CLReq 建立术语体系。

另外，CMOS 是一份体例（house style），而 CLReq 是一份需求文档（requirements），两者的共性在于其主旨都不是建立权威规范，虽然在实践中它们都有可能成为有公信力的参考文档。同时两者的区别在于，体例是从诸多实践规则中有选择的摘取风格、理念统一的规则来汇编，需求文档则是广泛参考诸家的实践来求同存异——从这个角度来说，无论一种具体的体例在理念上是否绝对「完美」「正确」，都有可能成为需求文档必须去重视的对象。

**Comment by acli** [comment]
重要的是，首先，叫中文破折號做 em dash 絕對是誤譯，至於怎樣叫，叫它做 two-em dash 並沒有錯。如果覺得有問題，可以用傳統的字眼，叫它做 two-em rule

（題外話，CMOS 是 style guide，你說它是 (CUP的) house style 技術上可以說沒有錯，但事實上沒有人會說它是 house style。另外，CMOS 固然並不是「權威規範」，但很多北美編輯都視它為最終權威。）

**Comment by realfish** [comment]
我不会将「em dash」视作中文破折号的「绝对误译」，而且这个译法在诸多方面仍有可取之处。但我也认为「em dash」可能不是 CLReq 对中文破折号的最佳译法。这个 issue 在讨论的就是翻译的取舍和潜在的译法，目前还没有任何「绝对」的定论。

**Comment by acli** [comment]
「em dash」是誤譯的理由是 em 是有標準定義的長度單位，而一個中文字的寛度只有大約一個em，但破折號要兩個中文字的寛度，所以 requirements 說 em dash,  是表示破折號只須排一個中文字的寛度，這是誤導，令人做出排版錯誤，所以絕對是誤譯。如果想精確一點就應該說是 two-em rule (或 dash)，如果想籠統可以只說它是 dash 或 Chinese dash

**Comment by ryukeikun** [comment]
综合术语本身含义的对照性（dash 的英文含义）、中英文读者的可接受度，本着非必要情况下尽量不生造新词的原则（比如 Pozhehao symbol 就不易懂），以及各种实作中的兼容程度，编辑会议讨论决定还是用 2-em dash 比较好。
