### ISSUE TITLE
关于蒙古文这样连写文字的禁则等问题 - 来自内蒙古大学的反馈

### ISSUE THREAD

**Issue by lianqi** [w3c/clreq#35]
最近看到各位专家有关中文版式的讨论，很受启发。
只是需要补充的是中文版式里面似乎没有考虑到像蒙古文这样连写文字的禁则等问题：
如，以中文为主的版式是横向的，且其换行、断行都有其基本成熟的规则。但如果其中加入蒙古文（其实阿拉伯文也同样），
其行内就出现新的问题。所以我觉得我们还必须考虑中文版面多文种混排的问题。
我不知道各位专家是否已有成熟的方案。

**Comment by ryukeikun** [comment]
我觉得我们应该就几点问题展开讨论：
1. 各民族语言文字有其各字的排版需求，各文种基本原则应该分别起文档论述
2. 此文档作为「中文排版需求」，必须要考虑到与其它文种混排的情况。要说，但不能也不可能说得过细。
3. 在民族自治地区，双语文是很常见、很必要的。除了双语文并排，也可能双语文混排，其重要程度不亚于中西混排，不能只谈中西混排而忽视在实际运用中很需要的民族语文内容。
4. 各民族语文众多，可根据书写系统大致分述基本原则，如壮文用拉丁字母，而朝、藏也都为横排，一些事项可遵循西文混排事项；而维吾尔文、哈萨克文都采用阿拉伯字母从右向左体系；而直排蒙文在混排中迁就横排汉文而放倒，即使和直排汉文混排也有反向移行问题等等，这些可分类概述，讲到基本原则即可，也不要导致内容冗长。

如果以上三点原则没有大问题，我可以起草混排部分的修改大纲，具体内容当然需要各文种专家的支持。

**Comment by lianqi** [comment]
Cc 内蒙古大学的那顺乌日图老师

Hi Ryukeikun，

感谢你的回复！

请见comment如下：

**Comment by ryukeikun** [comment]
安琪你好！
我草拟了一个大纲，请大家看一下

https://clreq.hackpad.com/3.3--r2Rp71RAnFI

**Comment by upsuper** [comment]
https://github.com/w3c/mlreq

**Comment by c933103** [comment]
應該要考慮的是有什麼問題是和西文或者其他語言混排不會產生但是和中文混排就會產生
