### ISSUE TITLE
2.3.3 里的问题

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#352]
https://w3c.github.io/clreq/#using_type_area_for_composition_in_real_pages

> Page for Table of Contents, Indexes and References: The size of the type area for the table of contents, indexes and references of books is based on the size of the type area for the main body content. There are many examples of tables of contents in vertical writing mode where the left-to-right size is identical to that of the type area, but the top-to-bottom size is a little bit smaller.

> 目录、索引、参考文献等页面以版心的尺寸作为基准设计。但有不少案例会于内文采单栏横排时，目录等页采多栏设计。而目录页有时天地侧会对文字进行缩排。

这一段有两个问题：

1. 「采单」应为「菜单」
2. 中英文描述内容不一致（尤其是后半段）

**Comment by realfish** [comment]
关于第 1 点，「采」字应该无误，是个断句、分词问题。这里的「采」是「采取」「采纳」的意思，「采单栏」与后文「采多栏」对应。

**Comment by realfish** [comment]
§2.3.3 在编撰时，跟 JLReq 的 [§2.2.5](https://w3c.github.io/jlreq/#kihonhanmen_and_examples_of_real_page_format) 有很强的对照性，但部分术语、排版说明的挪用和阐释可能都还不够明晰。

比如，标题中「体裁」这一措辞可能不太适合简体中文版（如果预设简中读者主要习惯中国大陆语境），这一点我在 #57 里[也有提到](https://github.com/w3c/clreq/issues/57#issuecomment-112981047)。又比如，日语「基本版面（kihon-hanmen）」与「版心（源自中文雕版印刷的术语）」的对应性。

再比如 @xfq 提到的第 3 小节，其中「天地侧会对文字进行缩排」是片面的描述。JLReq 中的确说到了相关排版方式，但语境是竖排文本。

* * *

试拟第 3 小节的简中版如下：

> 目录、索引、参考文献（参考书目）：此类页面也以正文版心为基准进行排版。但具体实践中，行头、行尾常会添加额外留白；此外，在正文采用单栏排版的同时，此类页面也有可能分为多栏。

试译如下：

> Pages for table of contents, index, and bibliography: these pages’ layout is also based on the type area of body text. In practice, additional paddings might be attached onto the start and the end of the lines. Furthermore, these pages might be set in multiple columns while the body text is single column.

**Comment by xfq** [comment]
同意，我们可以和第一部分的更改（#296）对照一下看看这整节的内容修改后是否通顺。

**Comment by ryukeikun** [comment]
我在之前的编辑会议也说过，不应该使用日文词「体裁」，因为中文「体裁」多指文学体裁。这里作为 format 的翻译，建议改成「样式」或者「版样」即可。

另外需要特别注意的是，日语「基本版面（kihon-hanmen）」并不与「版心」对应。中文的「版心」对应的是日文的「版面」，而 jlreq 里强调的「基本版面」是按照正文字号的网格版样。
