### ISSUE TITLE
书籍页面 recto、verso 的定义、翻译问题

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#354]
在 [4.1.3](https://w3c.github.io/clreq/?lang=en#handling_of_new_retros) 的第一个 NOTE 里，中文写着「书籍由封面作为第一页开始……」，英语译作「Books usually begin with page 1」。这个说法似有不妥。

书籍的封面，通常不是第一页（page 1），而是脱离正文页面编号体系的特殊页面。

而「Books usually begin with page 1」这句译文，似乎是借鉴了 JLReq [4.1.4](https://www.w3.org/TR/jlreq/#how_to_handle_headings_with_new_recto_page_break_and_bew_column) 第二个 NOTE 的英语翻译。但 JLReq 日语原文所说「書籍は，表（おもて）面を1ページとして開始する」，意思是「书籍以（纸张的/书叶的）正面作为第 1 页而开始」。在这里，「表面（おもて面）」指的应该是西文书籍的 recto side/page。与此对应的，日语「裏面」指的是 verso side/page。

上述日语的「表面、裏面」，分别译作「正面、反面」比较合适，也比较符合 recto/verso 的语义。

从正文页码的编号习惯上说，将 recto、verso 对应到「奇数页、偶数页」也说得通。

* * *

在阅读 4.1.3 和 4.1.4 时，我想到的一个问题是：CLReq 是否应该在 2.4（书写方向）相关章节，针对书籍及其他分页式的媒介，更明确地定义书叶（leaf）的「正面、反面」？

其实在 2.4.2 里，也已经用到了「Vertical […] left (recto) side」和「Horizontal […] right (recto) side」这样的阐释方式。或许另外再特别叙述一下「recto、verso」跟中文书页的对应关系（可以分横排、竖排分别叙述），会更清晰？

* * *

一个延伸讨论：

Recto、verso 比较适合描述双面印刷书叶（leaf）的正面和反面。而「右页、左页」则是以书脊为基准，描述 spread（对页/跨页）上的两个分页。但 recto 现在通常也暗示「正文起始页」所在的左右方位。

中文书的「正文起始页」，是否会因为对装订方式的选择或认知不同，而左右对调？

竖排古籍比较明显：单面印刷的传统雕版里，一种经典布局是用中缝将纸张分为左右两块，中缝常有鱼尾标记。用「蝴蝶装」装订书籍时，中缝位于订口（鱼尾进入书脊），这时事实上的正文起始页在书脊右侧（跟现代竖排书相反）；而若用「包背装」来装订，则中缝位于切口侧，正文起始页在书脊左侧（跟现代竖排书一致）。也即，相同雕版印刷的书页，正文起始页的左右位置可因装订方式而对调。可大致参考下图：

![](http://n.sinaimg.cn/translate/97/w590h307/20181121/FyOI-hnyuqhi5375399.jpg)

「蝴蝶装」这个概念，现在也被挪用来描述「左右书页能完全平展」的装帧方式，典型用途是跨页图稿的作品集。这种作品集每个 spread 是一个整体，相对于传统西文书籍来说是一种特例（左翻书的正文起始页在左，右翻书的正文起始页在右）；但放到中文书的语境里，能跟传统的「蝴蝶装」对应起来，似乎又显得不那么特殊了。

**Comment by ryukeikun** [comment]
根据[四月例会](https://www.w3.org/2021/04/14-clreq-minutes.html)讨论结果：

1. 目前的中英文版本均有不正确的地方，需要改善。在第四章整体修改（见 #285 ）之前，先做局部订正
2. 目前中文版里误解了 jlreq 中「表（おもて）」的涵义，将「正面」误成「封面」，这个错误不仅在第四章， 也在第二章各处，需要订正
3. 由于目前书籍装帧已经完全沿用西式的双面印刷，因此中文采用「正面」「反面」的叙述与英文的 recto/verso 对应，没有问题；但必须注意，现代中文里的「页面」概念，已经与中国传统古籍只有单面印刷、折成两面的装帧（比如 @realfish 提到的包背装 ）中的「页」（叶）是有区别的。 @bobbytung 台湾的业界现在如何称呼，请补充
4. 与此相关联的 [2.4.2.1](https://w3c.github.io/clreq/?lang=en#major_differences_between_horizontal_and_vertical_writing_modes)  的叙述中应该改作「直排时：页面的正面在左侧，左侧页码为奇数；右侧装订，从左向右翻页」「横排时：页面的正面在右侧，右侧页码为奇数；左侧装订，从右向左翻页」;
5. 无论如何，尽管「页」「面」到底是混在一起还是需要分开尚有摇摆，在中国大陆的出版行业里中，依旧采用「一叶有两面」的概念而保留了「另面起」「另页起」的术语，这写术语会在之后第四章整修的时候写入。

参考：

> CY/T 50-2008 出版术语 
> 3.119 页 page 
> 两面印刷的书刊一张纸的一面。作为印刷术语时指一张纸。

2008的这份行业标准里，条目做「页」，但两个概念共存

> GB/T 9851.9-2017 印刷技术术语 第9部分 书刊印刷术语
>2.15 页面 page
> 书刊中一张纸的一面。

2017 年的这份推荐国标里，条目改作「页面」，实际上含义仅只有「面」，这样改的好处是和「页码」连接（因为口语说的「页码」实际是「面码」）

<img width="736" alt="スクリーンショット 2021-04-15 9 53 33" src="https://user-images.githubusercontent.com/8192599/114799094-d3ad2e80-9dd1-11eb-9906-78db0b1eb3be.png">
《实用出版与印刷工作手册》，印刷工业出版社，1998，北京

![IMG_3868](https://user-images.githubusercontent.com/8192599/114799307-50400d00-9dd2-11eb-9732-cf81e1a2d8c2.jpg)
《编辑出版印刷手册》，科学普及出版社，1987，北京
