### ISSUE TITLE
`GB/T 15834` 和 `2011` 之间的连接符号的使用并不统一

### ISSUE THREAD

**Issue by Geeyun-JY3** [w3c/clreq#365]
以下仅针对简体中文部分。
文档中提及《标点符号用法》2011 年版的标准号时，`GB/T 15834` 和 `2011` 之间的连接符号的使用并不统一。如：

1. https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L182
用的是 `―`（U+2015 Horizontal Bar）

2. https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1292
用的是 `–`（U+2013 En Dash）

3. https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1455
用的是 `—`（U+2014 Em Dash）

4. https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L3157
用的是 `-`（U+002D Hyphen-Minus）

是不是应该统一一下？

参考：
全国标准信息公共服务平台：http://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D7FE25D3A7E05397BE0A0AB82A
国家标准全文公开系统：http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=22EA6D162E4110E752259661E1A0D0A8
在线预览|GB/T 15834-2011
：http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=22EA6D162E4110E752259661E1A0D0A8

**Comment by ryukeikun** [comment]
根据《GB/T 1.1—2020 标准化工作导则第1部分 标准化文件的结构和起草规则》中 8.1 封面中针对「文件编号」的注释写到

> 顺序号和年份好之间使用一字线形式的连接号。例如 GB/T XXXX—XXXX

结合实际情况，在此推荐全部统一使用 —（U+2014 Em Dash）
<img width="717" alt="屏幕快照 2021-05-12 20 36 06" src="https://user-images.githubusercontent.com/8192599/117969126-ffd0b680-b361-11eb-8442-ba02d7884aa6.png">
