### ISSUE TITLE
Translation issue and question about "Arrangement of tables and/or illustrations"

### ISSUE THREAD

**Issue by NightFurySL2001** [w3c/clreq#369]
In 2.4.2 (3)(1 and 2), the translation for the sub points are weird and labelled "Check this translation". However, there is a bigger confusion arises from these line.

https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1226
https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1231

In Chinese, there are two terms that can be used to describe a table: 行 and 列. The corresponding terms in English are "row" and "column". However, in different regions, the Chinese terms are used differently: in China, 行 refers to row and 列 refers to column; in Taiwan however, 列 refers to row and 行 refers to column. [(Reference)](https://zh.wikipedia.org/wiki/Topic:U3b8ags204w4rqvy) This might causes issues when trying to describe how tables are arranged across different regions. My understanding is that 行 usually goes in the same direction as the general writing direction, while 列 is perpendicular to the direction of writing. For the ease of understanding, I have made this following diagram:

![image](https://user-images.githubusercontent.com/33471049/118107250-1a159d80-b411-11eb-9079-2dc1fb09a5db.png)

This will involve how the terms in English should be mapped: either the row/header are described in terms of relative writing direction, or in terms of absolute direction. I would prefer the terms in English to be described in terms of relative writing direction, thus 列 will always be translated to column, while 行 will always be translated to row with no regards to the writing direction. Why? If absolute directions are used (i.e. row = horizontal, column = vertical), the direction of increment for row (horizontal) will be in the opposite direction when in vertical writing mode (列 goes from right to left).

Also, the section title was "Arrangement of tables and/or illustrations."/"表格、图片等标题栏的位置" which we should expect any descriptions about the title itself.

Thus, my suggestions for the translation fixes are as follow:

https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1226
> In vertical writing mode, list the column (incrementing towards the left) headers at the right of table and the row (incrementing going down) headers at the top of table; put the title of the tables and/or illustrations at the left or right side.
> 直排时，表格横列（往左递增）的标题列位右侧，直行（往下递增）的标题列位上方；表格、图片等标题置放于左或右侧。

https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1231
> In horizontal writing mode, list the column (incrementing going down) headers at the right of table and the row (incrementing towards the right) headers at the top of table; put the title of the tables and/or illustrations at the top or bottom.
> 横排时，表格直列（往下递增）的标题列位上方，横行（往右递增）的标题列位左侧；表格、图片等标题置放于上或下方。

**Comment by xfq** [comment]
We need to listen to opinions from Taiwan. @bobbytung? Any comment on this suggestion?

**Comment by bobbytung** [comment]
在台灣，對於表格的「行」與「列」沒有明確規定，僅有一句「直行橫列」的口訣。
我想主要是因為過往以直排為主，與行字方向相同成為行，而行（ㄒㄧㄥˊ）行（ㄏㄤˊ）方向稱為列。

後來以公文書為主，文件改為橫排後，對於表格的「行」與「列」沒有進一步的規定。所以基本上無論內文文字為直排還是橫排，我想行（由上而下）與列（直排由右而左/橫排由左而右），稱呼不會變。

而以現在的辦公軟體，如Pages, Number, Excel等，多用「直欄」與「橫列」為術語。

台灣的用法，可以這則連結中的解釋作為代表的範例：
https://terms.naer.edu.tw/detail/1274826/

**Comment by NightFurySL2001** [comment]
其实这个主要是提出该段完全无法理解的问题。我的猜测是原本该段是要表达表格内的标题栏目和/或表格外的标题应该放置的位置，但是中英表述互相矛盾。

> 3. Arrangement of tables and/or illustrations.  
> 表格、图片等标题栏的位置  
> 表格、圖片等標題列的位置
>     1. In vertical writing mode, align the top of tables/illustrations to the right of the page but list the headers on the right side.  
>     直排时，表格横列的标题列位上方，直行的标题列位右侧。  
>     直排時，表格橫列的標題列位上方，直行的標題列位右側。
>     2. In horizontal writing mode, align the top of tables/illustrations to the left of the page but list the headers on the left side.  
>     横排时，表格横列的标题列位上方，直行的标题列位左侧。  
>     橫排時，表格橫列的標題列位上方，直行之標題列位左側。

**Comment by xfq** [comment]
Discussions in yesterday's meeting: https://www.w3.org/2021/08/10-clreq-minutes.html#t08

**Comment by NightFurySL2001** [comment]
From the discussion it seems that the direction of 行 and 列 is fixed per region as most people do not change their current writing direction anymore and thus the terms are stuck regionally. Here is the fix I propose:

(New paragraph)
> In Mainland China, the direction of row in a table is called 行 which is horizontal, while the direction of column is called 列 which is vertical. In Taiwan and Hong Kong, the direction of row in a table is called 列 which is horizontal, while the direction of column is called 行 which is vertical. The direction of writing (either in horizontal mode or vertical mode) is historically called as 行, with the direction of 行 (Chinese: 行（xíng/ㄒㄧㄥˊ）行（háng/ㄏㄤˊ）方向) called 列; however these terms are not swapped in modern usage when changing writing directions out of habits. The following subpoints will indicate the incrementing direction in table to prevent confusion.
> 在中国大陆，表格内的横向方向称呼为“行”，而直向方向称呼为“列”。在台湾和香港，表格内的横向方向称呼为“列”，而直向方向称呼为“行”。历史上，无论横排直排，文字书写方向皆称呼为“行”，而行（xíng）行（háng）方向则称之为“列”；但现在出于习惯，这几个词汇不会再因切换书写方向而互换方向。下面的分节将会标示表格内递增的方向以避免混淆。
> 在中國大陸，表格內的橫向方向稱呼為“行”，而直向方向稱呼為“列”。在臺灣和香港，表格內的橫向方向稱呼為“列”，而直向方向稱呼為“行”。歷史上，無論橫排直排，文字書寫方向皆稱呼為“行”，而行（ㄒㄧㄥˊ）行（ㄏㄤˊ）方向則稱之為“列”；但現在出於習慣，這幾個詞彙不會再因切換書寫方向而互換方向。下面的分節將會標示表格內遞增的方向以避免混淆。

https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1226
> In vertical writing mode, list the column (incrementing towards the left) headers at the right of table and the row (incrementing going down) headers at the top of table; put the title of the tables and/or illustrations at the left or right side.  
> 直排时，表格横列（往左递增）的标题列位右侧，直行（往下递增）的标题列位上方；表格、图片等标题置放于左或右侧。  
> 直排時，表格橫行（往左遞增）的標題列位右側，直列（往下遞增）的標題列位上方；表格、圖片等標題置放于左或右側。

https://github.com/w3c/clreq/blob/d4cf48684f03e75956a7459be04b3139c32e0e9b/index.html#L1231
> In horizontal writing mode, list the column (incrementing going down) headers at the right of table and the row (incrementing towards the right) headers at the top of table; put the title of the tables and/or illustrations at the top or bottom.  
> 横排时，表格直列（往下递增）的标题列位上方，横行（往右递增）的标题列位左侧；表格、图片等标题置放于上或下方。  
> 橫排時，表格直行（往下遞增）的標題列位上方，橫列（往右遞增）的標題列位左側；表格、圖片等標題置放于上或下方。

**Comment by xfq** [comment]
Discussions in yesterday's meeting: https://www.w3.org/2021/10/13-clreq-minutes.html#t09

**Comment by xfq** [comment]
@NightFurySL2001 感谢反馈！请问我们如何在[致谢](https://w3c.github.io/clreq/#acknowledgement)里称呼您？

**Comment by NightFurySL2001** [comment]
谢谢。您可以使用”NFSL2001“称呼。

**Comment by NightFurySL2001** [comment]
New comments added in #400 .

**Comment by xfq** [comment]
Discussions in yesterday's meeting: https://www.w3.org/2021/12/17-clreq-minutes.html#t02

**Comment by realfish** [comment]
目前文档 2.4.2 一节中的[第 3 项](https://w3c.github.io/clreq/#id71)，表述方式和术语使用不够明晰。结合 [12 月 17 日 CLReq 例会讨论](https://www.w3.org/2021/12/17-clreq-minutes.html#t02)，尝试按如下方向改拟：

- 将图表「标题/说明文字」（title/caption）的排版规则，与表格「标题行/标题列」（header row / header column）的排版规则，拆分表述。
- 采用「逻辑行/逻辑列」（row/column in logical directions）统一术语。
- 增加「NOTE」以描述中文术语中「行」「列」的地区差异。

试改拟如下（简体中文版）——

* * *

#### 2.4.2 横排与直排的主要差异点

直排与横排的主要差异点，列举如下：

1. 文字、行、栏以及页面配置、装订方向［……］
2. 文中包含西文、阿拉伯数字时，配置如下［……］
3. 图片、表格的标题或说明文字
	1. 直排时，图片、表格的标题或说明文字，放在图、表的左侧或右侧。
	2. 横排时，图片、表格的标题或说明文字，放在图、表的上方或下方。
	> NOTE
	> 
	> 标题或说明文字（title/caption）通常是表格之外的文本内容，与表格内的标题行（header row）、标题列（header column）不同。
4. 表格标题行、标题列的位置
	1. 直排时，表格的标题行（直行）位于右侧，标题列（横列）位于上方。
	2. 横排时，表格的标题行（横行）位于上方，标题列（直列）位于左侧。
	> NOTE
	> 
	> 在不同的地区，中文术语中的「行」（<i>háng</i>）和「列」（<i>liè</i>）所描述的单元格排列方向，可能是不同的。例如，中国大陆的「行」通常指一组水平排列的单元格，「列」指一组垂直排列的单元格；而台湾、香港地区的「行」通常指一组垂直排列的单元格，「列」（或「栏」）指一组水平排列的单元格。
	>
	> 本文档采用「逻辑行」「逻辑列」来统一表述，也即，「行」在直排模式下垂直、在横排模式下水平，「列」在直排模式下水平、在横排模式下垂直。
5. 换页、换章时最末页采多栏排列、行于页面结束时，依以下方式处理［……］

**Comment by NightFurySL2001** [comment]
@realfish 针对新建议的 2.4.2 第4点的note，建议加上两点：
1. 历史上，“行”即文本书写方向，“列”为“行”的递增方向。（虽然现在词汇在各别地区已经固定，但是解释来源有助于理解现在的使用情况，也正好就是note中「逻辑行」「逻辑列」的使用方式）
2. 水平方向的递增方向在横排和竖排不一样：横排的横行是从左到右，但是竖排的横列是从右到左，我觉得需要特别标注。

**Comment by realfish** [comment]
感谢 @NightFurySL2001 的反馈，几点说明如下：

> 1. 历史上，“行”即文本书写方向，“列”为“行”的递增方向。（虽然现在词汇在各别地区已经固定，但是解释来源有助于理解现在的使用情况，也正好就是note中「逻辑行」「逻辑列」的使用方式）

NOTE 中的内容仅用于补充说明「行」「列」这两个中文术语在**现状**下存在的分歧问题。

如果我们采纳「逻辑行」「逻辑列」的表述（最终术语名称可能尚待编辑组讨论），那么中文「行」「列」的历史情况，实际上跟本文档没有直接关系。

在采用[逻辑方向](https://www.w3.org/TR/css-logical-1/)的前提下，行、列的行进方向实际上由[书写模式](https://www.w3.org/TR/css-writing-modes-3/)决定。因而，中文表格逻辑行、逻辑列的视觉方向可由具体排版环境中的书写模式直接推断。逻辑方向和书写模式本身，W3C 已有 spec 描述，并且这些 spec 已经覆盖了比中文横排、直排更全面的书写模式。——是否需要在 CLReq 中明确地引用相关 spec，可以另行讨论。

> 2. 水平方向的递增方向在横排和竖排不一样：横排的横行是从左到右，但是竖排的横列是从右到左，我觉得需要特别标注。

同上，逻辑方向和书写模式的定义，已覆盖中文横排和中文竖排中的具体方向。——CLReq 可以进一步考虑，是否需要对逻辑方向做出更详细的阐释。

* * *

作为参考，CSS Grid 中的 row 和 column，跟表格中逻辑行、逻辑列的方向规则是一致的：<https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/CSS_Grid_Logical_Values_and_Writing_Modes>
