### ISSUE TITLE
关于引号用途的描述

### ISSUE THREAD

**Issue by upsuper** [w3c/clreq#37]
现在的版本中关于引号写的是

>  引號用於強調字詞，或作為引用話語、文獻的起訖邊界。

引号还可以直接用于表示话语本身，例如小说中的对白。这个感觉应该不属于“引用”的范畴。

**Comment by realfish** [comment]
对白、对话属于「直接引用」。

**Comment by upsuper** [comment]
或许不能说小说……小说中的对白有可能可以看作直接引用，不过轻小说的有一些或许不可以。

我印象中有看到一种说法认为轻小说的写法是源于剧本的（道听途说，无可查证的正规来源）。剧本上的对白并不是引用，因而也不使用引号。但轻小说考虑小说的表示法，将对白用引号扩起来，但这样的对白同剧本中的并无差异，我怀疑不应当算作是“引用”。

**Comment by realfish** [comment]
将言语（语音）式的对话、对白直接记录（转录）成文字，不加篡改——这样的内容用「直接引用」这个术语来描述，应该是没有问题的；这与写作体裁没有什么直接关系。

类似剧本式的特殊文体，直接引用的内容（对白）可能占据了绝大多数篇幅。在这种特殊文体中，省略重复出现的引号，没有什么问题。很多剧本还会引入其他特殊标记，或者对常用标点定义特殊用法，这些特例由作者、编辑和特殊文体的设计师协商解决就可以了，应该没有必要在通用排版规范中一一列举……

**Comment by upsuper** [comment]
如果这样的话那就关掉吧……
