### ISSUE TITLE
分栏排版

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#373]
文档里多次提到分栏排版，但没有说什么是分栏排版，我们可在正文或者词汇表里定义一下。

**Comment by xfq** [comment]
可以加上示意图，这样更清晰一些，比如这样的：

* https://www.w3.org/TR/2020/NOTE-klreq-20200527/images/4-2.png
* https://www.w3.org/TR/2020/NOTE-klreq-20200527/images/4-3.png

**Comment by ryukeikun** [comment]
[词汇表](https://www.w3.org/TR/clreq/#glossary)里已经有「栏」「栏间距」等词条，词汇表部分是 OK 的。
文档内部没有叙述，应该放入 [2.3](https://www.w3.org/TR/clreq/#type_area) 进行重写，并添加图片。我另外开一个大 issue 来讨论这个问题。
