### ISSUE TITLE
繁體中文文本中誤用了簡化字

### ISSUE THREAD

**Issue by duyuang** [w3c/clreq#377]
3.3.1.2 標注釋義等非語音信息 中「尤以**轻小说**為主」中混用了簡體，應作「尤以**輕小說**為主」
![image](https://user-images.githubusercontent.com/35097840/122185444-afe49280-cebf-11eb-96b3-16bf0b8d44ae.png)

**Comment by xfq** [comment]
感谢指出！请问我们如何在[致谢](https://w3c.github.io/clreq/#acknowledgement)里称呼您？

**Comment by duyuang** [comment]
> 
> 
> 感谢指出！请问我们如何在[致谢](https://w3c.github.io/clreq/#acknowledgement)里称呼您？

不客氣，在致謝中稱呼 Du Yuang 即可。

**Comment by duyuang** [comment]
> 
> 
> 感谢指出！请问我们如何在[致谢](https://w3c.github.io/clreq/#acknowledgement)里称呼您？

此外，繁中文本中混用簡化字不止上述一處，以下是我整理出的部分，因個人能力有限，若有遺漏，在所難免。

修改遵循了以下三點：
* 簡體文獻名與名單中的簡體人名特意未作繁化
* 未對現有的「裏」「裡」二字進行修改（台灣用「裡」，港澳用「裏」，文本中已混用）
* 未對「著」「着」二字進行修改（台灣將「着」字併入「著」，港澳沒有，文本中已混用）

| 章節 | 修正前（修正部分用刪除線標識） | 修正後（修正部分用粗體標識） |
| -- | -- | -- |
 [1.3.1 本文檔所使用的中文語言](https://w3c.github.io/clreq/#chinese_text_in_this_document) | 在本工作草稿的早期~~阶~~段，文中漢語所使用的版本取~~决于~~貢獻此~~内~~容的~~编~~寫者。未~~来~~的版本~~会~~逐步改善整理此混合文本，但在本~~阶~~段，原始文本~~将~~被保留以快速完成和修正本文檔。 | 在本工作草稿的早期**階段**，文中漢語所使用的版本取**決於**貢獻此**內**容的**編**寫者。未**來**的版本**會**逐步改善整理此混合文本，但在本**階**段，原始文本**將**被保留以快速完成和修正本文檔。 |
 | [2.1.3.1 增加字距](https://w3c.github.io/clreq/#increased_inter_character_spacing) | 圖片與表格之說明文字字數~~较~~少時，為取得平衡，而加大字距。 | 圖片與表格之說明文字字數**較**少時，為取得平衡，而加大字距。 |
| [2.1.3.2 均排](https://w3c.github.io/clreq/#even_inter_character_spacing) | 表格~~标题~~、名~~单~~等求呈現一致時，會採用均排的方式處理。 | 表格**標題**、名**單**等求呈現一致時，會採用均排的方式處理。 |
| [2.1.3.3 減少字距](https://w3c.github.io/clreq/#reduced_inter_character_spacing) | 圖2 ~~紧~~排<br>減少字距，使得文字外框一部分重疊，稱作~~紧~~排。這種處理方式，主要應用於： | 圖2 **緊**排<br>減少字距，使得文字外框一部分重疊，稱作**緊**排。這種處理方式，主要應用於： |
| [3.1.1.2 標號](https://w3c.github.io/clreq/#indication_punctuation_marks) 2.括號 | _「注」中的所有~~头~~應改為**頭**；所有~~号~~應改為**號**_ |
| [3.1.1.2 標號](https://w3c.github.io/clreq/#indication_punctuation_marks) 6.連接號 | 連接號用於連結時空起訖或數量多寡，~~还~~可以用~~于~~化合物的名~~称~~或表格、插~~图~~的~~标号~~，~~门~~牌~~号码~~、~~电话号码~~等~~号码~~的~~连~~接，阿拉伯~~数~~字表示日期時年月日的區隔，~~复~~合名~~词~~中的~~连~~接，以及羅馬拼音、外~~来语内~~部的分合等。<br>根~~据~~台灣教育部的《重訂標點符號手冊》，連接號分為甲式及乙式，甲式為U+2013 EN DASH [–]、乙式為U+FF5E FULLWIDTH TILDE [～]或U+007E TILDE [~]。<br>根~~据~~中~~国~~大陸的《标点符号用法》（GB/T 15834—2011），~~连~~接~~号~~的形式有短~~横线~~[–]、一字~~线~~[—]和浪~~纹线~~[～]三~~种~~。 | 連接號用於連結時空起訖或數量多寡，**還**可以用**於**化合物的名**稱**或表格、插**圖**的**標號**，**門**牌**號碼**、**電話號碼**等**號碼**的**連**接，阿拉伯**數**字表示日期時年月日的區隔，**複**合名**詞**中的**連**接，以及羅馬拼音、外**來語內**部的分合等。<br>根**據**台灣教育部的《重訂標點符號手冊》，連接號分為甲式及乙式，甲式為U+2013 EN DASH [–]、乙式為U+FF5E FULLWIDTH TILDE [～]或U+007E TILDE [~]。<br>根**據**中**國**大陸的《标点符号用法》（GB/T 15834—2011），**連**接**號**的形式有短**橫線**[–]、一字**線**[—]和浪**線**[～]三**種**。 |
| [3.1.1.2 標號](https://w3c.github.io/clreq/#indication_punctuation_marks) 7.間隔號 | 間隔號為中文標點，當外語姓名包含西文首字母縮寫作為單節時，原則上西文字母~~后~~面應該使用西文句點，如「比爾·蓋茨」、「B. 蓋茨」。 | 間隔號為中文標點，當外語姓名包含西文首字母縮寫作為單節時，原則上西文字母**後**面應該使用西文句點，如「比爾·蓋茨」、「B. 蓋茨」。 |
| [3.1.1.2 標號](https://w3c.github.io/clreq/#indication_punctuation_marks) 8.書名號 | 根據中~~国~~大陸的《标点符号用法》（GB/T 15834—2011），~~无论书~~名、篇章名都~~应该~~使用~~双书~~名~~号~~[《》]，只有在~~书~~名~~号~~中~~还~~需要~~书~~名~~号时~~，~~里~~面一~~层~~用~~单书~~名~~号~~，外面一~~层~~用~~双书~~名~~号~~。甲式書名號（波浪底線）已甚少出現於現代的出版品，但仍可見於教科書或古籍的標示。 | 根據中**國**大陸的《标点符号用法》（GB/T 15834—2011），**無論書**名、篇章名都**應該**使用**雙書**名**號**[《》]，只有在**書**名**號**中**還**需要**書**名**號時**，**裏**面一**層**用**單書**名**號**，外面一**層**用**雙書**名**號**。甲式書名號（波浪底線）已甚少出現於現代的出版品，但仍可見於教科書或古籍的標示。 |
| [3.1.2 標點符號的字形、尺寸與字面分布](https://w3c.github.io/clreq/#glyphs_sizes_and_positions_in_character_faces_of_punctuation_marks) | 刪節號、破折號等標號，位字面正中，佔~~两~~個漢字的空間，並不得以適配分行之由斷開或拆至兩行，依文字書寫方向使用相應的標注方向。 | 刪節號、破折號等標號，位字面正中，佔**兩**個漢字的空間，並不得以適配分行之由斷開或拆至兩行，依文字書寫方向使用相應的標注方向。 |
| [3.1.3.4 示亡號](https://w3c.github.io/clreq/#symbol_of_death) | 示亡號並未列於標點符號相關標準文件，但卻是民間經常使用的俗用符號。示亡號亦稱示殁~~号~~，為在人名文字外框描上實心的黑色邊線表示已經過世，類似西文中劍標（U+2020 DAGGER †與U+2021 DOUBLE DAGGER ‡）之用法。 | 示亡號並未列於標點符號相關標準文件，但卻是民間經常使用的俗用符號。示亡號亦稱示殁**號**，為在人名文字外框描上實心的黑色邊線表示已經過世，類似西文中劍標（U+2020 DAGGER †與U+2021 DOUBLE DAGGER ‡）之用法。 |
|  [3.1.4 行首行尾禁則](https://w3c.github.io/clreq/#prohibition_rules_for_line_start_end) | 原則上，一份文檔內的級別應該統一。但若遇連續三個標點符號，如[。』」]等個別特殊狀況局部~~采~~用「不處理」以避免字距過松造成體例不良，應該視為救濟措施的個例，不作為推薦。| 原則上，一份文檔內的級別應該統一。但若遇連續三個標點符號，如[。』」]等個別特殊狀況局部**採**用「不處理」以避免字距過松造成體例不良，應該視為救濟措施的個例，不作為推薦。 | 
| [3.1.5.1 標點符號](https://w3c.github.io/clreq/#h-unbreakable_marks_punctuation) | 《標點符號用法》（GB/T 15834—2011）5.1.5節~~还规~~定，~~两个~~刪節號／省略號~~连~~用~~时~~，~~占~~四~~个~~漢字位置~~并须单独占~~一行。 | 《標點符號用法》（GB/T 15834—2011）5.1.5節**還規**定，**兩個**刪節號／省略號**連**用**時**，**佔**四**個**漢字位置**並須單獨佔**一行。|
| [3.1.6 標點符號的寬度調整](https://w3c.github.io/clreq/#punctuation_width_adjustment) | 標註在字間的標點符號（除乙式括號、破折號、省略號以外）通常占一個漢字寬度，使其易於識別、適合配置及排版，有些排版風格完全不對標點寬度進行任何調整。但是為了讓文字體裁更加緊湊易讀，以及執行§ 3.1.4 行首行尾禁則時，就需要對標點符號的寬度進行調整。是否調整取決於對排版風格的判斷，臺灣的很多印刷品都採用不調整的風格；而在中國大陸和香港的出版物中，多數~~采~~取調整的風格。標點符號寬度調整通常分為兩種情形：1. 標點符號連續出現 2.標點出現在行首或行尾。調整時的風格不盡相同，下文僅闡述基本原則。 | 標註在字間的標點符號（除乙式括號、破折號、省略號以外）通常占一個漢字寬度，使其易於識別、適合配置及排版，有些排版風格完全不對標點寬度進行任何調整。但是為了讓文字體裁更加緊湊易讀，以及執行§ 3.1.4 行首行尾禁則時，就需要對標點符號的寬度進行調整。是否調整取決於對排版風格的判斷，臺灣的很多印刷品都採用不調整的風格；而在中國大陸和香港的出版物中，多數**採**取調整的風格。標點符號寬度調整通常分為兩種情形：1. 標點符號連續出現 2.標點出現在行首或行尾。調整時的風格不盡相同，下文僅闡述基本原則。 |
| [3.2.3 直排的中、西文混排配置](https://w3c.github.io/clreq/#mixed_text_composition_in_vertical_writing_mode) | 直排時通常不使用彎引號，但在直排中引用西文內容時，可~~采~~用與西文樣式更匹配的彎引號。該情況下，彎引號的書寫方向需跟隨被引用的西文內容轉向。 | 直排時通常不使用彎引號，但在直排中引用西文內容時，可**採**用與西文樣式更匹配的彎引號。該情況下，彎引號的書寫方向需跟隨被引用的西文內容轉向。 |
| [3.3.1.1 為漢字標注讀音](https://w3c.github.io/clreq/#h-indicating_pronunciation_for_chinese_characters) | 行~~间~~注最常~~见~~的用途係為漢字標注讀音。漢字標音針對的是漢語初學者，包括母語為漢語的幼兒以及學習漢語的外國人士，因此對個別字標音的情況較少，多為全文標音。常規排版中沒有行間注標音的習慣，對生僻字也幾乎從不標音，即便標音也只是用行內括號標注。<br>中文的~~标~~音方案有注音符~~号与~~羅馬拼音~~两~~大~~类~~：<br>1.注音符~~号~~ | 行**間**注最常**見**的用途係為漢字標注讀音。漢字標音針對的是漢語初學者，包括母語為漢語的幼兒以及學習漢語的外國人士，因此對個別字標音的情況較少，多為全文標音。常規排版中沒有行間注標音的習慣，對生僻字也幾乎從不標音，即便標音也只是用行內括號標注。<br>中文的**標**音方案有注音符**號與**羅馬拼音**兩**大**類**：<br>1.注音符**號** |
| [3.3.1.2 標注釋義等非語音信息](https://w3c.github.io/clreq/#h-indicating_meaning_or_other_information) | 為外來語、首字母縮略詞標注其中譯，或對翻譯名詞標注其原文，多見於專有名詞、作品名及譯後概念較難傳達的詞彙。常~~见于译~~作，尤以~~轻小说~~為主。 | 為外來語、首字母縮略詞標注其中譯，或對翻譯名詞標注其原文，多見於專有名詞、作品名及譯後概念較難傳達的詞彙。常**見於譯**作，尤以**輕小說**為主。 |
| [3.3.2 行間注排版概述](https://w3c.github.io/clreq/#overview_of_positioning_of_interlinear_annotations) | 注音符~~号~~等~~宽~~且每个~~汉~~字~~标~~音的注音符~~号~~字~~数~~不超~~过~~三~~个~~，~~较为~~可控；而拉丁字母非等~~宽~~，拼式~~长~~短不一，且相~~邻~~拼式相~~连时应当~~有~~词间~~空格隔~~开~~。~~两类标~~音行間注的排版差~~异较~~大。 | 注音符**號**等**寬**且每个**漢**字**標**音的注音符**號**字**數**不超**過**三**個**，**較為**可控；而拉丁字母非等**寬**，拼式**長**短不一，且相**鄰**拼式相**連時應當**有**詞間**空格隔**開**。**兩類標**音行間注的排版差**異較**大。 |
| [3.3.4.1 基本規則](https://w3c.github.io/clreq/#h-basic-requirements) | * ~~仅横~~排。注文通常置~~于~~基文上方。不論二者寬窄關系如何，注文應密排，並與基文居中對齊。<br>* 被迫於直排文本標音~~时~~，注文通常置~~于标~~音文本右~~侧~~，但~~难~~以~~阅读~~。<br>* 若注文~~长于~~基文且位~~于~~行端，二者可向行端~~对齐~~。<br>……<br>下文描述~~两类~~典型用例之~~间~~的差~~异~~。 | * **僅橫**排。注文通常置**於**基文上方。不論二者寬窄關系如何，注文應密排，並與基文居中對齊。<br>* 被迫於直排文本標音**時**，注文通常置**於標**音文本右**側**，但**難**以**閱讀**。<br>* 若注文**長於**基文且位**於**行端，二者可向行端**對齊**。<br>……<br>下文描述**兩類**典型用例之**間**的差**異**。 |
| [3.3.4.2 單字標音](https://w3c.github.io/clreq/#h-characters_as_basic_units_for_annotating_pronunciation) | 1.基文~~为单个汉~~字。~~仅标~~注~~汉~~字，不~~标~~注阿拉伯~~数~~字、~~标点~~等字符。<br>2.注文~~总~~是在上方。<br>3.因注文~~宽~~度~~经~~常超~~过~~基文，通常~~为~~正文~~设~~定~~较~~大的字距以供~~给~~注文足~~够~~的~~横~~向伸展空~~间~~，避免基文~~间~~距~~频~~繁被~~过宽~~的注文~~撑~~大。<br>4.注文全小~~写~~，有時~~专~~名首字母大~~写~~。 |1.基文**為單個漢**字。**僅標**注**漢**字，不**標**注阿拉伯**數**字、**標點**等字符。<br>2.注文**總**是在上方。<br>3.因注文**寬**度**經**常超**過**基文，通常**為**正文**設**定**較**大的字距以供**給**注文足**夠**的**橫**向伸展空**間**，避免基文**間**距**頻**繁被**過寬**的注文**撐**大。<br>4.注文全小**寫**，有時**專**名首字母大**寫**。 |
| [3.3.4.3 分詞連寫標音](https://w3c.github.io/clreq/#h-words_as_basic_units_for_annotating_pronunciation) | 1.基文~~为~~一~~个~~或多个~~汉~~字~~构~~成的~~词语~~。分~~词连写规则~~可依~~据~~《汉语拼音正词法基本规则》（GB/T 16159—2012）。<br>2.注文有~~时~~在下方。<br>3.正文~~与标~~音~~双~~方皆分~~词连写~~。相~~邻~~基文之~~间~~有~~约~~1/2em的空格隔~~开~~，基文~~内~~部字距通常正常。<br>4.~~许~~多分~~词连写标~~音用例~~体现~~出~~对~~整~~个~~句子~~标~~音的~~逻辑~~，而非~~简单对词语标~~音：注文有句首大~~写~~、~~专~~名首字母大~~写~~。有~~标点~~，~~标点~~跟~~随~~左~~侧~~（前方）注文，如圖21所示。 | 1.基文**為**一**個**或多个**漢**字**構**成的**詞語**。分**詞連寫規則**可依**據**《汉语拼音正词法基本规则》（GB/T 16159—2012）。<br>2.注文有**時**在下方。<br>3.正文**與標**音**雙**方皆分**詞連寫**。相**鄰**基文之**間**有**約**1/2em的空格隔**開**，基文**內**部字距通常正常。<br>4.**許**多分**詞連寫標**音用例**體現**出**對**整**個**句子**標**音的**邏輯**，而非**簡單對詞語標**音：注文有句首大**寫**、**專**名首字母大**寫**。有**標點**，**標點**跟**隨**左**側**（前方）注文，如圖21所示。|
| [3.4.1 段首縮排](https://w3c.github.io/clreq/#line_head_indent_at_the_beginning_of_paragraphs) | 篇章最初段落的首行不縮排，其~~余~~段落首行縮排。此方法多見於西文書籍。 | 篇章最初段落的首行不縮排，其段**餘**落首行縮排。此方法多見於西文書籍。 |
| [3.4.2 段落縮排](https://w3c.github.io/clreq/#line_head_indent_of_paragraphs) | 段落縮排係指將版心（單欄排版時）以及欄的範圍（多欄排版時）由行頭側以指定的量，將文字開始位置向~~后~~移動的處理。此種縮排方式多應用於段落內或段落間引用文章、詩詞及標題等。 | 段落縮排係指將版心（單欄排版時）以及欄的範圍（多欄排版時）由行頭側以指定的量，將文字開始位置向**後**移動的處理。此種縮排方式多應用於段落內或段落間引用文章、詩詞及標題等。 |
| [3.5.4 拉伸處理的優先順序](https://w3c.github.io/clreq/#procedures_for_inter-character_space_expansion) | 若上述所有項目均無法調整，或調整之後依舊無法達到預設行長，則只能針對剩~~余~~所有字符間距，進行同時、同等量拉伸，但是：  | 若上述所有項目均無法調整，或調整之後依舊無法達到預設行長，則只能針對剩**餘**所有字符間距，進行同時、同等量拉伸，但是：  |
| [A.2 非夾注型標號](https://w3c.github.io/clreq/#table_of_non-bracket_indication_punctuation_marks) | 佔二個漢字大小，呈一~~点~~線、中間不斷開，應將省略點置於字面中央。  | 佔二個漢字大小，呈一**點**線、中間不斷開，應將省略點置於字面中央。  |
| [B. 詞彙表](https://w3c.github.io/clreq/#glossary) | ~~紧~~排<sup>注：僅位於「詞彙（繁）」列的</sup> <br>……<br>於各字之間加入均**匀**空白的排版方式。<br>……<br>在中文文本中，包含部分西文~~时~~的~~处~~理方式。<br>……<br>具有相同基本~~设计~~的字形~~图~~像集合(GB/T 16964.1-1997, 3.6)，現多與字體混用。 | **緊**排</sup> <br>……<br>於各字之間加入均**勻**空白的排版方式。<br>……<br>在中文文本中，包含部分西文**時**的**處**理方式。<br>……<br>具有相同基本**設計**的字形**圖**像集合(GB/T 16964.1-1997, 3.6)，現多與字體混用。 |
| [E. 致謝](https://w3c.github.io/clreq/#acknowledgement) | 感~~谢~~以下參與者~~对~~本文~~档~~的建~~议~~與~~补~~充（依字母及拼音順序排列）：<br>欲了解最新的參與者信息，~~请参~~看GitHub~~贡献~~者列表。 | 感**謝**以下參與者**對**本文**檔**的建**議**與**補**充（依字母及拼音順序排列）：<br>欲了解最新的參與者信息，**請參**看GitHub**貢獻**者列表。

**Comment by xfq** [comment]
问题已修复：https://w3c.github.io/clreq/
