### ISSUE TITLE
所扩内容跨段时引号的特殊用法

### ISSUE THREAD

**Issue by upsuper** [w3c/clreq#38]
我在轻小说译本中有看到过类似于

> “一段话。
> “第二段话。
> “最后一段话。”

这种形式的不匹配的引号用法，或许值得特殊说明？

**Comment by upsuper** [comment]
这种用法在GB/T 15834-2011中有提到，在4.8.3.5

**Comment by ryukeikun** [comment]
我觉得可以考虑加入。不知其他编辑意见如可？ @ethantw

**Comment by ethantw** [comment]
台灣很多印刷書也這麼使用，的確値得說明。

**Comment by ryukeikun** [comment]
那我就这项加进去吧

**Comment by upsuper** [comment]
我发现英文似乎也是这么用的 [[1]]

<img width="655" alt="2016-12-25 6 45 43" src="https://cloud.githubusercontent.com/assets/333750/21470204/60c1b23c-cad2-11e6-9219-3337989ab078.png">

[1]: http://www.news.com.au/national/victoria/news/police-raids-in-melbournes-northern-suburbs/news-story/135a23d342de22b6abedc7203b02d04f

**Comment by xfq** [comment]
GB/T 15834-2011 § 4.8.3.5:

> 独立成段的引文如果只有一段，段首和段尾都用引号；不止一段时，每段开头仅用前引号，只在最后一段末尾用后引号。

Related discussion in Zhihu: https://www.zhihu.com/question/20220789

**Comment by xfq** [comment]
Another example in English:

> The letter was to this effect:
> 
> "My dear Lizzy,
> 
> "I wish you joy. If you love Mr. Darcy half as well as I do my dear Wickham, you must be very happy. It is a great comfort to have you so rich, and when you have nothing else to do, I hope you will think of us. I am sure Wickham would like a place at court very much, and I do not think we shall have quite money enough to live upon without some help. Any place would do, of about three or four hundred a year; but, however, do not speak to Mr. Darcy about it, if you had rather not.

> "Yours, &c."

*Pride & Prejudice, Chapter XIX of Volume III (Chap. 61)*
