### ISSUE TITLE
关于示例里 《诗经》中的 《关雎》标点符号的疑问。

### ISSUE THREAD

**Issue by ixnij** [w3c/clreq#380]
在阅读 [2.2.1 中文排版常用字体 ](https://w3c.github.io/clreq/#four_commonly_used_typefaces_for_chinese_composition) 及以下的小节关于中文字体排版的文章时，我对被用于示例宋体及其他常用于排版的字体的 《关雎》的简体版本的示例的点号有些疑问：

![《关雎》](https://w3c.github.io/clreq/images/zh/songti.png) 

在简体中文的示例中，“关关雎鸠” 和 “在河之洲” 之间的点号是顿号，而不是逗号；而在 “关关雎鸠、在河之洲” 后边是分号，而不是句号，后边以此类推。

我在简体中文语境书写《诗经》中的诗歌时，诗句中间大多是逗号，而一句的结尾都是句号。部编版的语文教科书也是如此排版（诗句中间逗号，句尾句号）。想请教一下这样书写的用意。

**Comment by acli** [comment]
古文無標點，標點都是後人加上去的，容許我用英文形容一下，這我們叫editorial discretion，即是後人在整理古文時，覺得在那裏意思已經完結，就加句號，覺得意思未完，就加頓號。
另，在引入西方的逗號前，中文是用頓號的（當然以前不叫頓號，我不太清楚以前叫什麼），就好像現代日文也沒有逗號，句號之前只有頓號一樣。

這裏的冒號可能也是引入了英文的一種舊式用法，可能表示一種分號和句號之間的間隔（現在英文已很少用，而且很多人以為英文沒有這種用法），不過這只是我個人的猜測。

**Comment by acli** [comment]
不過如果是我們的例句，不同標點應該是正簡中文的例句是兩個人抄了兩個不同的版本，然後沒有人校對，結果標點就不同了。我覺得這個例句可以統一用冒號或者統一用分號（除非有人反對）

**Comment by ixnij** [comment]
> 古文無標點，標點都是後人加上去的，容許我用英文形容一下，這我們叫editorial discretion，即是後人在整理古文時，覺得在那裏意思已經完結，就加句號，覺得意思未完，就加頓號。
> 另，在引入西方的逗號前，中文是用頓號的（當然以前不叫頓號，我不太清楚以前叫什麼），就好像現代日文也沒有逗號，句號之前只有頓號一樣。

这自然不错，但是我觉得既然当今大家都统一习惯加上这样的标点符号，可这里没有按照这样的习惯进行书写，这就有些让人感觉不自然了。

> 這裏的冒號可能也是引入了英文的一種舊式用法，可能表示一種分號和句號之間的間隔（現在英文已很少用，而且很多人以為英文沒有這種用法），不過這只是我個人的猜測。

或许就是这样吧，但我认为对于中文的排版就应该符合中文的书写习惯。

> 不過如果是我們的例句，不同標點應該是正簡中文的例句是兩個人抄了兩個不同的版本，然後沒有人校對，結果標點就不同了。我覺得這個例句可以統一用冒號或者統一用分號（除非有人反對）

不过这里为何要使用冒号？我用的是简体中文，不太清楚繁体的习惯。

**Comment by acli** [comment]
除非有其他人反對，上面已經提過，這些我都不會反對。

但是中文標點的用法是什麼呢，其實除了幾個中文才有的（例如着重號、專名號、書名號），我看很多都是抄英文的（亦可能是抄法文），但我們是抄的是大概兩個世紀前他們的用法，而現在英文的用法已經改變了，是我們石化了他們兩個世紀前的用法。

我不知道你有沒有見過，但現在基督教還很多人用的和合本聖經（不是其他新版本，也不是和合本新標點版），那裏用的標點正正就是我們用逗號的地方他們用頓號（亦即按古文用法），原全不跟現在的中文標點規則，但那是1904年排版的書，當時「中文標點用法」可能尚未成形。我們例句抄的版本是什麼年份出版的？

說了一大遍，其實我想講的只是，除非有其他人反對，反正原文根本沒有標點，我不覺得把這段例文的標點「現代化」有什麼問題。但樓上問的是「用意」，我只是想講「用意」只是editorial discretion，而正簡版本不同標點只是代表我們抄了兩個不同的版本。

**Comment by acli** [comment]
> 这自然不错，但是我觉得既然当今大家都统一习惯加上这样的标点符号，可这里没有按照这样的习惯进行书写，这就有些让人感觉不自然了。
> [...]
> 我认为对于中文的排版就应该符合中文的书写习惯。

但是中文標點的用法究竟是什麼？除了幾個中文才有的標點符號（例如着重號、專名號、書名號），我看很多其實都是抄英文的（亦可能是抄法文，例如中文的書名號二式《》很明顯是抄法文的引號«»），但我們是抄的是大概兩個世紀前他們的用法，現在英文的用法改變了，但我們石化了他們兩個世紀前的標點。

我不知道你有沒有見過，但現在還有很多人用的基督教[和合本聖經](http://www.cut.ibibles.net/001Genesis.htm)（不是其他新譯本，也不是新標點和合本或和合本修訂版），用的標點正正就是我們會用逗號的地方他們就用頓號（亦即按古文的規則排版），完全不跟現在的中文標點規則，但那是二十世紀初，超過一百年前排版的書，現在通用的「中文標點用法」，當時可能尚未成形，起初看和合本也當然看不自然，看慣了就覺得很正常。

我們的例句究竟抄了什麼年份出版的詩經？會不會是二十世紀初？還是編者覺得古文應該按古文的標點規則排版？如果古文標點是問題，又不想把引文的標點「現代化」，可能例句不應引用詩經。

> 不过这里为何要使用冒号？我用的是简体中文，不太清楚繁体的习惯。

冒號的用法正簡中文應該沒有分別，所以我也沒有答案，但如果冒號不是誤打，按照「中文標點基本上是抄二百年前的英文標點」的假設，冒號可能表示兩種意思：
1. 後句闡釋前句
2. 後句和前句有某種其他關係（即基本上跟分號一樣），但關係可能較分號所表達的小，但又不至於小到要用句號

**Comment by ixnij** [comment]
> > 这自然不错，但是我觉得既然当今大家都统一习惯加上这样的标点符号，可这里没有按照这样的习惯进行书写，这就有些让人感觉不自然了。
> > [...]
> > 我认为对于中文的排版就应该符合中文的书写习惯。
> 
> 但是中文標點的用法究竟是什麼？除了幾個中文才有的標點符號（例如着重號、專名號、書名號），我看很多其實都是抄英文的（亦可能是抄法文，例如中文的書名號二式《》很明顯是抄法文的引號«»），但我們是抄的是大概兩個世紀前他們的用法，現在英文的用法改變了，但我們石化了他們兩個世紀前的標點。
> 
> 我不知道你有沒有見過，但現在還有很多人用的基督教[和合本聖經](http://www.cut.ibibles.net/001Genesis.htm)（不是其他新譯本，也不是新標點和合本或和合本修訂版），用的標點正正就是我們會用逗號的地方他們就用頓號（亦即按古文的規則排版），完全不跟現在的中文標點規則，但那是二十世紀初，超過一百年前排版的書，現在通用的「中文標點用法」，當時可能尚未成形，起初看和合本也當然看不自然，看慣了就覺得很正常。
> 
> 我們的例句究竟抄了什麼年份出版的詩經？會不會是二十世紀初？還是編者覺得古文應該按古文的標點規則排版？如果古文標點是問題，又不想把引文的標點「現代化」，可能例句不應引用詩經。
> 
> > 不过这里为何要使用冒号？我用的是简体中文，不太清楚繁体的习惯。
> 
> 冒號的用法正簡中文應該沒有分別，所以我也沒有答案，但如果冒號不是誤打，按照「中文標點基本上是抄二百年前的英文標點」的假設，冒號可能表示兩種意思：
> 
> 1. 後句闡釋前句
> 2. 後句和前句有某種其他關係（即基本上跟分號一樣），但關係可能較分號所表達的小，但又不至於小到要用句號

那么我认为在这种场合下不应该使用 《周南》中的民歌作为例句。不过作为标准，我还是倾向于使用现代同意的标点用法。

**Comment by bobbytung** [comment]
補一下當年選擇這一段文字的脈絡。

最初的版本使用的是「東方文字傳情之美」，這是來自W3C其他國際化文件，而來源是華康字體的範例。為了讓字體範例更為中立，當時決定挑選其他的文字，從沒有著作權問題，且廣為人知的古籍中挑選。

同時為了表示簡繁體的差異，不能挑選簡繁轉換後字形（Glyph）沒有差異的內容，《關雎》中有異有同，像是「關」與「关」，「逑」與「逑」整體與部首的差異。

此外加入標點，是為了呼應下面標點符號位置，在簡繁之間的位置差異。

CLREQ編輯僅有 @ethantw 協助製作圖例，所以當時選了幾個能夠「畢其功於一役」的圖來做。

若要更換展示常見簡繁體字體的範例文字，我想可以。也希望多來貢獻協助提供圖例製作。

**Comment by realfish** [comment]
经 CLReq [八月例会讨论](https://www.w3.org/2021/08/10-clreq-minutes.html#t06)，计划暂保留「关关雎鸠……」示例文本，但删去其中的标点符号，并重新挑选样本字体。

字体的选择大致参照如下几点考量：

- 宋黑仿楷，每类展示四个字体，繁简示例文本各占一半；
- 尝试覆盖「国字标准字体」字形、《通用规范汉字表》字形、传承字形（旧字形）等；
- 同类别内部，尝试体现字重对照，以及风格对照（黑体喇叭口、仿宋骨架）等。

* * *

样图如下：

<img width="800" alt="four-type-classes--song" src="https://user-images.githubusercontent.com/3247876/129163971-f60c0c4d-8def-4804-94d2-50d2090a2fcb.png">
<img width="800" alt="four-type-classes--hei" src="https://user-images.githubusercontent.com/3247876/129163980-9aec1c29-c4b6-4682-a04b-730eb60f0dae.png">
<img width="800" alt="four-type-classes--fang" src="https://user-images.githubusercontent.com/3247876/129163988-d9bda1a9-1f6c-4680-98dc-73bae267c3b1.png">
<img width="800" alt="four-type-classes--kai" src="https://user-images.githubusercontent.com/3247876/129164001-ffc77496-a81f-41e5-9648-8b2874a3873d.png">

注：

- 样图暂为 PNG，后续提交 SVG。
- 感谢 @ryukeikun 详细 review 及帮助。
