### ISSUE TITLE
关于 3.1.7（标点悬挂）

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#388]
本节第一段：

> 参考[日文排版](https://www.w3.org/TR/jlreq/#positioning_of_punctuation_marks)的做法，［……］

所引链接指向 <i>JLReq</i> 的 3.1.2，内容不太匹配（可能因 <i>JLReq</i> 版本改动）。目前，<i>JLReq</i> (version 20200811) 的相关内容位于 [2.5.1 下的 c](https://www.w3.org/TR/jlreq/#id83) 和 [3.8.2 的 note](https://www.w3.org/TR/jlreq/#h-note-162)。

* * *

本节最后一段：

> 连续多个标点符号的情况下，不作行尾点号悬挂的配置。

理论上，连续多个标点（标点簇）中的**最后一个标点**，若是悬挂合法的标点——也即以顿号、逗号、句号为代表的几个点号之一——则最后一个标点**本身**仍可悬挂。如果这种阐释/理解是正确的，则关于「连续多个标点」的说明或可删去；作为补充，在第二段中附加一则限定：

> 通常，**行尾只可悬挂一个点号**；适合行尾悬挂的点号有顿号、逗号及句号。［……］

**Comment by ryukeikun** [comment]
我个人从来没有看到过连续标点的最后一个标点悬挂出去的例子， @realfish 你看过实际例子吗？

**Comment by realfish** [comment]
这种例子比较少见，需要行文和排版的巧合。我临时翻了一下手边的书，Idea Document《文字とタイポグラフィの地平》p. 152 正好有一例：

![IMG_0019](https://user-images.githubusercontent.com/3247876/137107734-c464c65d-228e-4c9e-b790-a217f541524e.jpg)

——其中，`（p.153-p.158）。` 这串文本正好处在行尾，标点簇 `）。` 里的句号就是悬挂的。

* * *

另外，为了说明这个问题，其实可以特意构造一些例子，比如这样：

<img width="538" alt="punct-hangout" src="https://user-images.githubusercontent.com/3247876/137108093-32c14fa0-734c-4f72-bcf6-1beda1ecd4ef.png">

——其中，三连标点簇 `」）。` 在正常行文中还比较容易遇到，所以理论上就会出现在行尾，遇到悬挂设置。

**Comment by ryukeikun** [comment]
尽管这样情况很少见，但作为需求文档，可以容忍这样的排法。可以按照 @realfish 建议修改。
