### ISSUE TITLE
标点符号可添加“示亡号”

### ISSUE THREAD

**Issue by upsuper** [w3c/clreq#39]
“示亡号”就是在人名旁边加一圈黑框表示这个人已经死了的那个符号。这个符号似乎在各种标准里面都没有出现，但是在正规档案和书籍中似乎并不鲜见。

维基百科相关资料：https://zh.wikipedia.org/wiki/%E7%A4%BA%E4%BA%A1%E5%8F%B7

**Comment by ryukeikun** [comment]
## 1. 先说为什么没有加的原因。

是的，正如维基百科页面所记载，这个标点符号并不在GB《标点符号用法》所列之内。也许 GB 把它算广义的「符号」，比如星号（*）等，这种分类并不是根据「是否常见」来定义的。GB 中对标点符号的定义是：

> 标点符号 punctuation：辅助文字记录语言的符号，是书面语的有机组成部分，用来表示语句的停顿、预期以及表示某些成分（主要是词语）的特定性质和作用。 
> 
> 注：数学符号、货币符号、校勘符号、辞书符号、注音符号等特殊领域的专门符号不属于标点符号。

另一方面，原本以为这是一个中文特色符号，加进来可以凸显和日文、韩文的不同，但是后来发现这个符号也不是汉语独创，而是源于俄文书刊……

## 2. 除了“示亡号”，类似符号还有

代字号　×　（张某某）
虚缺号　□  （碑文里无法辨认的字）
标示号   *
这些符号都是中国国家语言工作委员会的厉兵先生在[《出版工作中的语言文字规范》讲义](http://wenku.baidu.com/link?url=Rz6SmhadkY08iawjYGkwLv1F6rsZwcAcU2fNix9r85OcaA5wd2a4Ha6_lTkaX0T_i-aEeJ2LtUXEpYRnQuyD6a3hY3Nxw6N7NT5vpSgrF8O) 中提到的没有被GB收入的「中文标点符号」，这些符号的确是「中文特色」，而且不知道两岸三地是否有差异，如何处理，需要讨论。

**Comment by lianqi** [comment]
也叫示殁号，国内做法通常是一个黑色方框，框住已逝世的人名字。

**Comment by ethantw** [comment]
有見過某些版本的中文《聖經》會用雙底線來標示地名、以單底線來標示人名，是否也需要在CLReq中說明？

**Comment by upsuper** [comment]
底线地面人名的问题可以单开一个新issue讨论。

**Comment by ryukeikun** [comment]
我似乎也有见过，但是一种比较老旧的方法，到现代是否具有普遍性？最好查一下资料？

**Comment by ethantw** [comment]
想到一個有趣的問題，示亡號的「一圈黑框」又跟著重號、專名號或書名號附著在文字周圍的方式不同，它是繞著文字走一圈，文字長短會影響框的尺寸，統一碼裡不知道有沒有這種符號（製表符？XD）可以表示。

**Comment by bobbytung** [comment]
以俗用標點加在 3.11 Categories and Usage of Punctuation Marks 标点符号的分类及用法 標點符號的分類及用法

**Comment by xfq** [comment]
添加到 [§ 3.1.3 Atypical punctuation marks and their composition](https://w3c.github.io/clreq/#atypical_punctuation_marks_and_their_arrangements) 这一节如何？

**Comment by xfq** [comment]
可以加一个 § 3.1.3.3 俗用标点

**Comment by ryukeikun** [comment]
示亡号的图 8 不太准确，没有按照中文花名册占字原则排版，应该替换
<img width="653" alt="Shiwanghao" src="https://user-images.githubusercontent.com/8192599/109946326-74142b80-7d1b-11eb-8af4-49599ee748da.png">

**Comment by xfq** [comment]
谢谢 @ryukeikun ，已修复，见：https://w3c.github.io/clreq/#symbol_of_death （访问前可能需要清空浏览器缓存）

<img width="1309" alt="fix" src="https://user-images.githubusercontent.com/2863444/112453166-5e31dd80-8d92-11eb-8eef-f6832403431d.png">

**Comment by xfq** [comment]
我们是否可以关闭这个issue了？
