### ISSUE TITLE
Language switching doesn't work for the spec metadata

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#392]
After clicking 简体中文 in https://w3c.github.io/clreq/, the spec content is changed to SC, but the spec metadata section ("This version:", "Latest published version:", "Latest editor's draft:", "Editors:" etc.) is still in English.

This may be related to recent changes in ReSpec.

**Comment by xfq** [comment]
"Abstract" and "Status of This Document" are also in English.

**Comment by r12a** [comment]
Looks like we may need to raise an issue in the Respec repo.

**Comment by xfq** [comment]
I just took a look and changed this line:

https://github.com/w3c/clreq/blob/df5729baf10b6a5867cd788c213db717ede7aea5/script.js#L136

to `$$('h1 + h2 + details dl dt')` and the problem was solved. However, "More details about this document" is still in English because our script does not currently support the localization of the summary element.

**Comment by xfq** [comment]
I just sent https://github.com/w3c/clreq/pull/393 to fix this.

**Comment by xfq** [comment]
IMHO when ReSpec changes the markup structure of the spec metadata section, it is best to make an announcement (to spec-prod@w3.org, maybe) so that downstream specs that rely on the markup structure can better adapt to the changes.
