### ISSUE TITLE
统一文档内引号的使用

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#399]
目前文档里既使用了单直角引号，如 https://w3c.github.io/clreq/#h-note-38

也使用了弯引号，如 https://w3c.github.io/clreq/#h-note-23

我们是否需要统一一下引号的使用？也可以把这一点在我们的[编辑指南](https://w3c.github.io/clreq/EDITING)里体现。

**Comment by xfq** [comment]
Related: https://github.com/w3c/clreq/pull/449

**Comment by kecrily** [comment]
我倾向简体中文使用弯引号，繁体中文使用方引号，繁简体各自使用区的出版物也都是这样使用的。
