### ISSUE TITLE
避免使用 ruby、行距计算和单引号笔误

### ISSUE THREAD

**Issue by siusin** [w3c/clreq#4]
From Xidorn
[[
1. 我建议在此文中应避免使用 ruby 一词。汉语里似乎应该用“标音”或“标音符号”？[1] 如果有需要的话可以在文末附录B的词汇表中提到与日文的“rubi/ruby/ルビ”类似，并可用类似机制实现。但 ruby 毕竟不是中文排版词汇（这个似乎根本是 W3C 创造的一个排版词汇，日语里面通常应该用的是 rubi？）为求方便而直接取用个人觉得不是很恰当。
2. 2.3.5 的最后一个 Note 里面的最后一个公式在网页里面看到的样子是“行高＝文字尺寸÷2＋行距＋文字尺寸÷2＝文字尺寸＋行距行距＝行高－文字尺寸”，我看了三遍才看出来中间的两个行距之间应该有断行或者至少标点、空格来分割。这个应该要修改。
3. 3.1.1.2 引号中对简体中文的描述里，单引号的直角单引号，似乎使用了和直角双引号一样的字符。应该是一个笔误。

[1] https://zh.wikipedia.org/wiki/%E6%A0%87%E9%9F%B3
]]

From Bobby
[[
這份文件中盡量減少使用Ruby，我把各點列出來
- 2.3.5 Note
  ...翻譯書籍亦可能如日文排版一般加入Ruby文字…
  這裏指的是日文排版，使用Ruby應該沒問題。
- 3.3.2.1 綜述
  ...两类标音 ruby 的排版差异较大…
  此處ruby可刪除。
- 3.3.2.3.1 基本規則
  ...这一排版需求有赖于 HTML Ruby Markup Extensions 对 成组连写的支持以及 CSS Ruby Module Level 1 的空白处理…
  此處是Spec名，保留。
- 3.3.2.4.2 合文
  ...使用ruby標音可能導致文本排版效果不佳…
  此處ruby可刪除。
- 3.3.2.5.1 詞的對齊
  ...底線處詳見〈JLReq・Positioning of Group-ruby with Respect to Base Characters〉…
  此處是Spec名，保留。
- 5.2.7 行間注
  兩處譯名再商討如何調整。
  以上除內文兩處刪除外，主要是譯名看該如何調整，再反應到英文版上。
  5.2.7的譯名，您有推薦的取代詞彙嗎？
  ]]

From Xidorn
[[
我的想法是“行间注”保留 interlinear annotation 即可，因为根据文中对行间注的解释，至少最后一条用作批注看过去与日文中的 ruby 在含义和用法上都有较大差别。
“注文”可以考虑使用 annotation text 来代替 ruby text。
]]

**Comment by upsuper** [comment]
小倩啊，我那些邮件里每个都是三个问题，如果要贴到 GitHub 的话，最好分拆开来贴。之后的我就直接贴在 GitHub 好了。

**Comment by siusin** [comment]
@upsuper 

Sorry >_< 我改一下标题吧~

好的~GitHub比较方便跟进。

**Comment by ethantw** [comment]
- [x] 避免使用ruby
- [x] 行距计算公式的格式修正
- [x] 单引号笔误

**Comment by ethantw** [comment]
應該沒問題了，先關。
