### ISSUE TITLE
楷体和仿宋体的使用

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#409]
https://w3c.github.io/clreq/#four_commonly_used_typefaces_for_chinese_composition

> [楷体]主要使用于标题、引言、摘句、对话、内容出处等与内文有所不同的段落上

> [仿宋体]常用于副标题和引言、摘句等区隔于内文的段落上

感觉二者都适用于区别于内文的段落上，用法是否有区别？

**Comment by realfish** [comment]
在内文级别的样式中（inline-level styles），由于中文常使用标点符号来辅助标记部分语义——例如，书名号可标记作品名、引号某些语境里可标记强调/突出——所以通过字体风格来区分语义的场景，相比西文会少一些。

下面（不完整地）归纳一些楷体和仿宋的常见用例，作为区分的参考：

1. 楷体、仿宋，均见于段落式的直接引用——
    - 典型场景：成段地引用文章，引用一首诗歌；
    - 大致上可被（不精确地）视作，是 `<blockquote>` 样式的一部分。
2. 楷体，作为正文段落内的「强调」字体——
    - 典型场景：翻译类作品，用于对应原文中用意大利斜体（italic type）表示强调的文本；
    - 大致上可被（不精确地）视作，是 `<em>` 的样式（另，`<strong>` 常用黑体）。
3. 楷体，一般性地对应西文的意大利斜体——
    - 这种用例，是第 2 种的扩展，典型场景也是翻译类作品；
    - 大致上可被（不精确地）视作，是 `<em>` 和 `<i>` 的样式（另，`<cite>` 常被改写为引号、书名号等显式的标点符号）。
4. 楷体，作为脚注字体。
5. 楷体，作为落款信息——
    - 典型用例：文章、文件尾部的落款姓名；
    - 大致上可被（不精确地）视作，是 `<footer>` 或 `<address>` 内的部分样式。
6. 仿宋，作为标题字体——
    - 典型场景：中国大陆的部分公文体例；
    - 大致上可被（不精确地）视作，是 `<h1>` `<h2>` … 等标题样式的一部分。
7. 仿宋，作为全文字体——
    - 典型场景：中国大陆的部分公文体例，早年铅字排印的部分书籍。
8. 仿宋（有时特定为某类风格的长仿宋体），作为机械制图的标准字体。

**Comment by c933103** [comment]
是否需要區分一般書法意義上的楷體，和電腦上與Windows附屬的標楷體相當的字體？

**Comment by realfish** [comment]
<i>CLReq</i> 所讨论的宋、黑、仿、楷四大类常用字体，在没有特别说明的情况下，应指广义上的「印刷字体」（包括数码字体意义上的「屏显」）。更精确一些，指的是能覆盖一个相对较大字符集的（例如，能覆盖常用汉字）字库产品的风格分类。可以比较明确的一点是，它们不是 logotype，也不是为**少量字符**专门书写或定制设计的美术字。

此处可见宋、黑、仿、楷的示例字体：<https://w3c.github.io/clreq/#commonly_used_chinese_typefaces>

**Comment by ryukeikun** [comment]
需要修改一下表述，四大印刷字体之所以是四大，是因为有且只有这四类字体目前广泛用于长文排版。试改写这段如下

-------

2.2.1 中文排版常用字体
中文排版使用的字体种类繁多，但有四种字体最为重要：

- 宋体
- 楷体
- 黑体
- 仿宋体

这四种字体均既可单独用于图书的长篇正文排版，也可以混合搭配使用。下列各节分别介绍其使用情境。

……

2.2.3 楷体
楷体又称正书、真书，字体特性为带有书法形态、手写笔触。如图4所示。
楷体普遍用于公文书、教科书。台湾的公文书多全文使用楷体。
楷体也可与其他字体搭配，用于标题、引言、摘句、对话、内容出处等与内文有所不同的段落上。

2.2.4 黑体
黑体又作方体，字体特性为笔画宽度平均，较少装饰。如图5所示。
传统印刷品少使用黑体作为内文文字，但受到万维网、数字出版的影响，使用黑体作为内文字体的印刷品逐渐增多。
黑体也可与其他字体搭配，用于标题、图说、对话之人名。内文中也会使用字重较粗的黑体作为特定文字的强调、着重。

2.2.5 仿宋体
仿宋体的字体形态介于宋体与楷体之间。如图6所示。
仿宋体常用于文艺作品和古籍，而中国大陆则规定政府公文原则上应使用仿宋体。
仿宋体也可与其他字体搭配，常用于副标题和引言、摘句等区别于内文的部分上。

-------


可以考虑加注释或者在参考文献里增加

- 《党政机关公文格式》— Layout key for official document of Party and government organs（GB/T 9704-2012）

-------

**Comment by c933103** [comment]
但例如「蒙納顏楷」之類字體，雖然也屬於楷體，但個人認為這類書法效果較為突出的楷體並不太算屬於如Figure 4圖中所示常用於公文和教科書的那一種楷體。日文的話這類更為正式楷體應該算是教科書體，但在中文字體的範圍內應該怎樣形容這一特定類別較為標準正式的楷體？

**Comment by xfq** [comment]
@c933103 这个问题和本issue讨论的问题无关，建议单独开一个新的issue讨论。

**Comment by acli** [comment]
依英文排版的分類, 顏體比較接近書法體 (calligraphic type), 並非所謂斜體 (italic type)｡ 我的看法是日文的楷體一般也是書法體, 不是 italic｡ (中文 ｢斜體｣ 其實是誤譯, 英文傳統中 italic 並不指字體傾斜，而是指有 ｢flow｣ 和字形有行草 (cursive) 的結構｡)

中文楷體的用法基本上是石化了西方十六世紀前的用法。
