### ISSUE TITLE
Inconsistent status for clreq-gap

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/clreq#413]
https://www.w3.org/TR/2021/WD-clreq-gap-20211119/ claims both:
> The end target for this document is a Working Group Note.

and

> This document was published by the Internationalization Working Group as a Working Draft using the Recommendation track. 

which are incompatible under process 2021.

**Comment by xfq** [comment]
I think @r12a has fixed this issue in cef05a0ecb938f266676daf694d322ad5c695c2a , so it will be correct the next time it is published.

**Comment by xfq** [comment]
I sent https://github.com/w3c/clreq/pull/416 to fix the layout requirements document.

**Comment by r12a** [comment]
> I think @r12a has fixed this issue in cef05a0 , so it will be correct the next time it is published.

Indeed. I've been actively working on changes to the document and expect to republish soon.  

There are, however, 30-odd documents like this which all need to be changed.  I've done some already, but the rest will take a bit longer to get to.

I'm therefore going to close this issue.
