### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#420]
Should we document the layout of the Table of Contents?

**Comment by realfish** [comment]
The [point 3 of 2.3.3](https://w3c.github.io/clreq/#id41) covers some layout/design conventions about TOC. Aside from some minor editorial bugs (which have been discussed on the editors’ meeting in Aug 2022), it looks good enough to me.

See also #352, #368, #379, and #382.

**Comment by xfq** [comment]
Closing per https://www.w3.org/2022/08/23-clreq-minutes.html#t12
