### ISSUE TITLE
关于 2.1.3 汉字的配置原则 的两个疑问

### ISSUE THREAD

**Issue by VirgilMing** [w3c/clreq#43]
1. (a) 和 (b) 的区别是什么？我的理解是它们都是增加 tracking，且达到的效果似乎都是使文字在某个宽度内平均分布，请问它们的区别是什么？
2. (c) 减少字距下的第 2 项似乎是个注解而不是用法本身。

**Comment by bobbytung** [comment]
@VirgilMing 
1. 以CSS來解釋的話，(a)就是letter-spacing，直接指定字距為固定值。(b)是text-align:justify，是在每行行長確定的狀況下，達到頭尾對齊。還是有點差別。
2. 這邊我會改成：

> 減少字與字間的字距，使得文字外框一部份重疊，稱作紧排。這種處理方式，主要應用於：雜誌標題以及廣告文案字數較多，為使其排列於一行，或為求特殊表現時使用。
> 
> 注1)
> 由於漢字皆為正方形，此方式並不適用於活字排版，故不應用於書籍標題與內文的排列上。

**Comment by bobbytung** [comment]
感謝 @ryukeikun 改寫，應該比較易於理解。
