### ISSUE TITLE
请考虑添加「什么样的人应该阅读本文档」

### ISSUE THREAD

**Issue by VirgilMing** [w3c/clreq#44]
内核恐慌第十六期提到，大家对本文档有相当严重的误解。与其反复澄清本文档不是一份 Spec，还不如直接在开头声明：本文档只为某些特定的人群提供参考，其他人并无必要将其奉为圭臬。

**Comment by hax** [comment]
这个可以在本repo的readme写，但是不适合放到文档里吧。
