### ISSUE TITLE
注音符号中的“ㄧ”

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#443]
文档里似乎没有提到注音符号中的“[ㄧ](https://zh.wikipedia.org/zh-tw/%E3%84%A7)”（i）在横排时应写作一横还是一竖的问题。我们是否需要在文档里体现这一点？

**Comment by acli** [comment]
橫排通常就是預設什麼就排什麼，預設就是一橫；直排才是問題？

**Comment by realfish** [comment]
「ㄧ」（U+3127）的转向问题，需不需要考虑一下[注音扩展符号](https://zh.wikipedia.org/wiki/%E6%B3%A8%E9%9F%B3%E7%AC%A6%E8%99%9F#%E6%BC%A2%E8%AA%9E%E6%97%8F%E8%AA%9E%E8%A8%80%E6%93%B4%E5%85%85%E7%AC%A6%E8%99%9F)：

- 目前已被 Unicode 收录的「ㆪ」（U+31AA）和「ㆳ」（U+31B3）的转向一致性问题；
- 润音符、方音符没有 Unicode 码位，情况可能更复杂一些。

**Comment by ryukeikun** [comment]
相关背景比较复杂，请参考 @bobbytung 的[这篇文章](https://medium.com/@bobtung/用ruby-寫台語-3a1e3ed9bf3c) 的相关章节。然后问题就变成，这一复杂的背景是否需要写到 clreq 这个需求文档里。  @bobbytung 觉得有必要么？

**Comment by bobbytung** [comment]
這裡我們加一段note來說明好了。

> 注音符號ㄧ（U+3127 BOPOMOFO LETTER I）於制定初期，排版規定直排時為一橫、橫排時為一豎。此用法出現在民國時期的文獻，以及中國的新華字典上。但注音符號系統應用於台灣的國語文教學，無論直橫排列，都以橫畫為原則。
> 
> 因此在Unicode中修改此碼點的範例字型為橫畫。但在字型技術處理上，可使用OpenType字型功能`hist`，即歷史形式來取代顯示直畫，供呈現歷史文獻或特殊需求。

**Comment by xfq** [comment]
这个note添加到文档的什么位置比较合适呢？

**Comment by bobbytung** [comment]
我想加到「3.3.3.4 Examples of Zhuyin annotations 注音标音排版用例 注音標音排版用例」的figure 22之後。
才發現這一整段並未提到注音符號使用的文字，加在有圖例的這兒看來最適宜了。
