### ISSUE TITLE
3.1.1.2 標號 一节中，結束雙彎引號[”](RIGHT SINGLE QUOTATION MARK) 英文翻译是否笔误？

### ISSUE THREAD

**Issue by lianqi** [w3c/clreq#45]
結束雙彎引號[”](RIGHT SINGLE QUOTATION MARK) 英文翻译是否应该(RIGHT DOUBLE QUOTATION MARK)？

**Comment by ethantw** [comment]
是的，應作：

> 簡體中文採用先雙、後單的引號體例，彎引號用於橫排、直角引號用於直排。雙引號，包含開始雙彎引號[“](LEFT DOUBLE QUOTATION MARK)、開始雙直角引號[『](LEFT WHITE CORNER BRACKET)、結束雙彎引號[”](RIGHT **DOUBLE** QUOTATION MARK)、結束雙直角引號[』](RIGHT WHITE CORNER BRACKET)；單引號，包含開始單彎引號[‘](LEFT **SINGLE** QUOTATION MARK)、開始單直角引號[「](LEFT CORNER BRACKET)、結束單彎引號[’](RIGHT SINGLE QUOTATION MARK)、結束單直角引號[」](RIGHT CORNER BRACKET)。

（粗體字者為需要修正處，共二個）

**Comment by lianqi** [comment]
谢谢Ethan！那我就close 这个issue。
