### ISSUE TITLE
「紧排」图示表意不够明确

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#450]
[§2.1.3.3](https://w3c.github.io/clreq/#reduced_inter_character_spacing) 的图示（figure 2），可能存在两个问题：

1. 没有直观体现「外框重叠」；
2. 上下两行文字的字距不同，但没有明确指出「紧排效果」和默认对照样本分别是哪一行。

**Comment by ryukeikun** [comment]
同样 Figure1 也应该直观体现字框之间被拉大的间距，应该统一修改，比如图一改成这样
![figure1](https://user-images.githubusercontent.com/8192599/192454418-4a24b26a-9cf5-4d6d-b513-e23c45482ffb.png)

图二改成这样
![figure2](https://user-images.githubusercontent.com/8192599/192454445-d8c8dea9-3be6-4b9b-9f7e-64fb98927e06.png)

**Comment by ryukeikun** [comment]
As per talked in [CLReq Editors' Call of Sep 27, 2022](https://www.w3.org/2022/09/27-clreq-minutes.html)  , 

changed Fig 1 with indicators A/B/C/D, which can be explained in captions, to avoid plural pictures; also changed the green color to match other figures
![Fig1](https://user-images.githubusercontent.com/8192599/196366256-76d110aa-268f-466d-8e5a-361d457f2610.png)

Caption: A. 1/4 em space; B. 1/3 em space; C. 1/2 em space; D. 1 em space 


changed Fig 2 with Kaiti font (actually STKaiti in this case) 
![Fig2](https://user-images.githubusercontent.com/8192599/196364583-cc614644-4dc2-49ea-8a7d-73a445fe6a80.png)
