### ISSUE TITLE
数值与单位（符号）间的空格不统一

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#452]
数值和单位（符号，非汉字）之间是否加空格，目前文档内存在着不一致：例如 `14 pt` 和 `14pt`。

**Comment by kecrily** [comment]
在国际计量委员会 2019 年出的《The International System of Units》中要求，除 `°`、`′` 、`″` 外，数字和计量单位间需要空格[^1]。英国出的《Writing for Home Office Science 》中也有类似规定，但例外符号为 `°C` 和 `%`[^2]。

但在多用到这个单位的场景，如 CSS 和 UI 设计中，普遍不加空格。

[^1]: The International System of Units. *[The International System of Units](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9.pdf/fcf090b2-04e6-88cc-1149-c3e029ad8232)* (9th). 2019. p. 151. "The numerical value always precedes the unit and a space is always used to separate the unit from the number. Thus the value of the quantity is the product of the number and the unit. The space between the number and the unit is regarded as a multiplication sign (just as a space between units implies multiplication). The only exceptions to this rule are for the unit symbols for degree, minute and second for plane angle, °, ′ and ″, respectively, for which no space is left between the numerical value and the unit symbol."
[^2]: Home Office Science. *[Writing for Home Office Science ](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/116153/guide_to_authors.pdf)* (1st). June 2011. p. 13. "There is a space between a number and a unit of measurement e.g. 20 mg – except for temperatures e.g. 20°C and percentages e.g. 20% (or in text use 20 per cent)."

**Comment by stone-zeng** [comment]
LaTeX 的 `siunitx` 包使用 `\,` 作为数值与单位的间距，大致相当于 U+202F NARROW NO-BREAK SPACE。

**Comment by kecrily** [comment]
在 IEEE 的标准里也有些单位与数值间用的是 U+00A0 NO-BREAK SPACE ` `[^1]。

[^1]: IEEE Standards Association. *[SCC 14 Conventions for Metrication of IEEE Standards](https://standards.ieee.org/wp-content/uploads/import/governance/revcom/scc14.pdf)*. October 31, 2017. p. 5. "Note that the percent symbol is a unit symbol. A fixed and non-breaking space should appear between the percent symbol (%) and the preceding numerical value. Use the % symbol not the word percent. [3.4.8.2.c)]"

**Comment by xfq** [comment]
我们可以在[编辑指南](https://github.com/w3c/clreq/blob/gh-pages/EDITING.md)里也提一下这一点。
