### ISSUE TITLE
3.1.4 行首行尾禁則：标点符号出现在行尾也不可以么？

### ISSUE THREAD

**Issue by lianqi** [w3c/clreq#46]
3.1.4 行首行尾禁則Prohibition Rules for Line Start and Line End 
為了保持閱讀順暢、體例一致，多數標點符號的位置有其限制，通常一個標點符號依其性質，禁止出現在一行之首或之末。
---- 标点不能出现在行首是通用做法。希望确认一下，标点符号是否不可以出现在行尾。

**Comment by upsuper** [comment]
有些标点符号当然不可以出现在行尾，比如前引号、左括号等等。

**Comment by lianqi** [comment]
收到，多谢！
