### ISSUE TITLE
What is the purpose of the `class` attribute of the `script` tag in `index.html`?

### ISSUE THREAD

**Issue by kecrily** [w3c/clreq#462]
I found that the `script` tag in `index.html` uses the class attribute.

https://github.com/w3c/clreq/blob/58376bca9a35a5e069a7b704d46b27e2f8ed085c/index.html#L9

I didn't know that script had this attribute and thought it was some kind of feature, so I looked up MDN.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

But I couldn't find it in the MDN, so what is its purpose?

**Comment by r12a** [comment]
The Respec content management code uses this script to generate the page, then removes the no longer needed javascript from the final rendered document.

**Comment by kecrily** [comment]
So the `class` attribute is a description of the purpose of this script? Right?

**Comment by r12a** [comment]
The class attribute is being used to indicate to the CMS that it should remove the not-needed script code from the rendered page.  So not so much a description of the purpose of the script, but a description of what to do with the script.

**Comment by kecrily** [comment]
I got it! Thanks r12a

**Comment by xfq** [comment]
See https://github.com/w3c/respec/wiki/remove for details.
