### ISSUE TITLE
更新CLReq的更新日期

### ISSUE THREAD

**Issue by upsuper** [w3c/clreq#47]
之前的观察，W3C的草案文档似乎每次更新的时候都会同时更新最顶上的日期，但CLReq草案的日期自首次公开发布以后似乎就没有更新过，至今仍是四月十日。看GitHub最后一次修改是五月一日了吧。

希望能够及时更新该日期，以方便草案读者知晓文档是否有新版本。

**Comment by siusin** [comment]
同意～下一次更新内容时候注意修改一下日期吧。

**Comment by siusin** [comment]
Should be ok now with the help of ReSpec lib.
