### ISSUE TITLE
h5 links in lists

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#48]
the zh doc often uses &lt;h5> markup around text inside &lt;li> markup.  This is problematic wrt sectioning, and causes some problems for respec, and i don't think it's really semantically sensible.

i recommend that we replace that markup with &lt;span class="leadin"> and move it inside the following &lt;p> tag.

This actually makes the English version easier to read, although i suspect that there is a small difference in expectations of layout between English and Chinese versions.

i'm making this issue now so that i don't forget to.  If you wait a short while, i'll put up the latest english translation, which will show what i suggest.  I'll add a comment to this issue when it's ready.

**Comment by VirgilMing** [comment]
Care to encapsulate those h5 tag in code block? I'm not quite sure what you are talking about. Issues support Markdown so you need to escape them.



Virgil Ming

**Comment by r12a** [comment]
thanks for drawing my attention to that, Virgil. I escaped the &lt; characters and i think it now reads as i expected.

**Comment by r12a** [comment]
this has been done in https://github.com/w3c/clreq/commit/6aec5dee5bf7aacdd415b5b90d45fc6e9b004ad6
