### ISSUE TITLE
西文、西文字母、阿拉伯数字等术语的用法

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#483]
CLReq 行文中存在以下一组关联性较强的术语：

- 西文（正文中多使用 Western text，术语表则翻译为 Western script）
- 西文字母（Western letter/character）
- 阿拉伯数字（European numeral）

* * *

首先，术语表内的译法「Western script」在正文中的使用频率相对较低。在术语定义中：

> Writing systems derived from Greek and Latin.
> 欧洲、美洲和大洋洲通行的文字。

中文将「西文」术语视作文字/文种（script），英文则将其翻译为「书写系统」（writing system），二者范畴不同。

* * *

其次，有时这组术语在行文中的范畴/从属关系似乎不够明确，中文用法不完全统一，英文翻译也不完全统一。以下举例：

> There are many examples in Chinese text where Western characters, such as Latin letters, Greek letters, or European numerals, are found alongside Han characters. The following are just a few examples:\
> 中文排版中，汉字与拉丁字母、希腊字母或阿拉伯数字等西文混排的状况经常出现，以下列举部分范例。

——摘自 [3.2.1](https://w3c.github.io/clreq/#composition_of_chinese_and_western_mixed_text)，阿拉伯数字（European numerals）和西文（Western characters）是包含关系，阿拉伯数字是西文（分类）内的一项。

> For vertical writing mode, the following list describes methods of setting Western letters and European numerals:
> 直排时，西文与阿拉伯数字的配置有以下三种方法：

——摘自 [3.2.3](https://w3c.github.io/clreq/#mixed_text_composition_in_vertical_writing_mode)，西文（Western letters）与阿拉伯数字（European numerals）是并列关系。

> Western text or European numerals used for this arrangement should have the same fixed size and width as the Chinese characters, rather than a proportional width.
> 西文字母或阿拉伯数字，采用此配置时，需使用与汉字相同尺寸、字幅固定的等宽字体，而非比例字体。

——摘自 [2.4.2 第一个 note](https://w3c.github.io/clreq/#n017)，西文字母（Western text）和阿拉伯数字（European numerals）是并列关系。

* * *

以下提出几个问题：

1. 「西文」作为术语，在 CLReq 中应该指代「文种」还是「书写系统」？
2. 如果将阿拉伯数字视作「西文」分类下的一种字符，在大多数「西文字符与阿拉伯数字」并举的语境里，是否可以省略「阿拉伯数字」，直接统称「西文/西文字母/西文字符」？
3. 与第 2 点相对，是否有必要另外引入一个独立术语，例如「西文字母/西文字符 Western letter/character」，用以统称拉丁字母、希腊字母、基里尔字母等欧洲语言常用的字符（但不包含阿拉伯数字）？并以此跟「阿拉伯数字」并列使用？

**Comment by ryukeikun** [comment]
我个人的意见是，

1. 「西文」，当作为一些所谓西方语言的「书写系统」，比如英语的书写系统时，使用拉丁字母、阿拉伯数字（有时候甚至包含希腊字母）。在一般泛指的情况下，用 western text 即可，此时是包含阿拉伯数字的，即 3 点需要的那个词。
2. 在谈到字符分类时候，尽量不用「西文」这样含糊的词，而改用「拉丁字母」，此时「拉丁字母」与「阿拉伯数字」并列，这样明显逻辑更清晰一些。

**Comment by ryukeikun** [comment]
我建议

- 西文（European text），是一个含糊概念，包含拉丁字母、阿拉伯数字（有时候甚至包含希腊字母）
- 西文字母（European alphabet）
- 阿拉伯数字（European numeral）

**Comment by xfq** [comment]
Discussion in yesterday's meeting: https://www.w3.org/2022/09/27-clreq-minutes.html#t08
