### ISSUE TITLE
using Unicode codepoint values

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#49]
in text such as the following:

`句號[。](IDEOGRAPHIC FULL STOP)、逗號[，](FULLWIDTH COMMA)以及頓號[、](IDEOGRAPHIC COMMA)。句號表示語句結束、逗點表示語氣停頓、頓號使用於並列連用、表示次序的字詞之間。`

the Unicode code point values are not listed.

I suggest that we change the above, and similar text, to read:

`句號[。](U+3002 IDEOGRAPHIC FULL STOP)、逗號[，](U+FF0C FULLWIDTH COMMA)以及頓號[、](U+3001 IDEOGRAPHIC COMMA)。句號表示語句結束、逗點表示語氣停頓、頓號使用於並列連用、表示次序的字詞之間。`

**Comment by VirgilMing** [comment]
Again you might want to escape [ character.

**Comment by r12a** [comment]
hmmm, this is becoming annoying - ok, edited

**Comment by r12a** [comment]
actually, as i struggle with the translation, i'm beginning to think that it would be easier to change

`[。](IDEOGRAPHIC FULL STOP)`

to 

`U+3002 IDEOGRAPHIC FULL STOP [。]`

and likewise throughout the document.

**Comment by r12a** [comment]
Any thoughts on this? I'm working through the translation at the moment, and it would be nice to be able to adjust the text to the desired outcome.

I'd also like to surround the codepoint value and name with <span class="uname"> markup, so that we can style the text. Ok?

**Comment by jjgod** [comment]
Sounds like a good change, will you please submit a pull request?

**Comment by r12a** [comment]
ok, since i have had no objections and one expression of support i'll implement that

**Comment by r12a** [comment]
done
https://github.com/w3c/clreq/commit/0f64bfa4f9814562919309b4f0b7a472eedafde2
