### ISSUE TITLE
Definition of code point

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#490]
The term 'code point' may be unfamiliar to those unfamiliar with encoding, so I suggest adding / linking to the definition of the term, such as https://www.w3.org/TR/i18n-glossary/#def_code_point

**Comment by ryukeikun** [comment]
Great!

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/commit/8ccc302a23ba92a1332ed8d5fb960a85bed53b6c
