### ISSUE TITLE
「汉字」作为术语时的英语翻译

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#496]
目前存在两种翻译：Chinese character(s) 和 Han character(s)。且两种不同译法，在使用时的区分不够明显。

建议优先统一，也即，将表意相同的「汉字」，翻译成同样的英语词组。只在明确需要区分 Chinese 和 Han 的语境中，再分别使用。

**Comment by ryukeikun** [comment]
对于真正讨论到所谓 CJK unified ideographs，正如之前是不是讨论过统一用 Han character?

如果有微妙语感的区别，可以尝试用 Chinese text 和 Han character 进行区别

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/pull/504
