### ISSUE TITLE
省略号、連接號、書名號乙式等描述的改進

### ISSUE THREAD

**Issue by siusin** [w3c/clreq#5]
from Xidorn
[[
3.1.1.2
1. 省略号，关于省略号的位置问题，我想或许值得说明一下。虽然我个人很喜欢在底部的省略号，但并不是所有的字体都是如此，而且 GB/T 15834-2011 里面，省略号也是摆在正中的。
2. 连接号，依据 GB/T 15834-2011，似乎除了 em dash 以外，也还有普通的 dash？不知道是否需要提到？
3. 书名号，乙式，我不确定繁体中文的用法，但是简体中文中双书名号和单书名号皆可以标示书名及篇名，其区别类似于双引号和单引号，用于在书名号内引用另一个名称，如《如何评价〈狼图腾〉》（随便在知乎上找了个问题 233）。

]]

from @ethantw 
[[
Re 省略号
這部分在「3.1.2 標點符號的字形、尺寸與字面分布」節中已經有說明。因為國標跟台灣教育部的省略號都位正中，所以並沒有特別描述。

> 包括：刪節號、破折號等標號，位字面正中，佔一個漢字之高、二個漢字之寬，並不得以適配分行之由拆至二行，依文字書寫方向使用相應的標注方向。

有些漢字字體會把U+2026的點放在底部，主要應該是因為這個字元漢字、西文共用，放底部方便fallback。

Re 连接号
那分文件採用的Unicode字元很亂，基本上是字形的差異，語意上還是用en dash才對。（GB/T是推薦而非強制標準，所以模糊、有問題的地方就不去管它了）

Re 书名号
乙式書名號看來還是要區別大陸跟台灣的用法（原先沒寫是不希望太複雜，光書名號就有甲、乙式，乙式又分二種……）。

台灣是以單書名號為篇名、雙書名號為書名，比如《舊約聖經》和〈馬太福音〉。
]]

**Comment by upsuper** [comment]
不不不，这个并不只是省略号，里面有三个符号的问题……

**Comment by bobbytung** [comment]
@upsuper 省略號我這邊過去遇到兩個字元：
「⋯」（MIDLINE HORIZONTAL ELLIPSIS Unicode: U+22EF）
「…」（HORIZONTAL ELLIPSIS Unicode: U+2026）
剩下的是U+FE19嗎？

我原先覺得應可用這兩個字元來切分位置，但語意上還是U+2026正確。

**Comment by ethantw** [comment]
@bobbytung 最好用圖片描述。語意不對的字元不能因為長相對了就算對（U+22EF是數學符號），而且很有可能被誤解。加上某些平台可能沒有支援U+22EF的字體，會顯示成豆腐。

**Comment by bobbytung** [comment]
@ethantw 這一點我以前寫過一篇，所以這裏使用U+2026。
總之，依照文件Glyph應是置中三點，留個ACTION，之後處理。
- [ ] 整理有字型差的標點符號，以圖片呈現。

**Comment by ethantw** [comment]
在 55c7aac6 中已大致調整完畢，先關票。省略號的圖片就之後加咯。
