### ISSUE TITLE
heading of 2.1.1 Characters used for Chinese composition

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#53]
http://w3c.github.io/clreq/#characters_used_in_chinese_composition
http://w3c.github.io/clreq/zh/#characters_used_in_chinese_composition

the heading of section 2.1.1 is the same as that for section 2.1.  Should we simply remove the heading (and section tags) for this section?  (ie. section 2.1.2 would become the new 2.1.1)

**Comment by ryukeikun** [comment]
I think this section is written base on JLreq, so I think they should be 

2.1 Characters **_and the Principles of Setting them**_ for Chinese Composition
2.1.1 Characters Used for Chinese Composition

while the zh version should be accordingly

2.1 中文排版所使用的文字和基本原则
2.1.1 中文排版所使用的文字
