### ISSUE TITLE
关于括号

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#537]
https://w3c.github.io/clreq/#n025

> There are other brackets and quotation marks which include [此处省略，见原文]. These brackets and quotation marks are rarely used in Chinese publications.

关于这个note，我有两个问题：

1. 中文版没有提到“These brackets and quotation marks are rarely used in Chinese publications.”
2. 【】这对括号可能因为输入法支持较好，出现比其他列出的括号要更加常见，是否应该被列为例外呢？

**Comment by realfish** [comment]
> 2. 【】这对括号可能因为输入法支持较好，出现比其他列出的括号要更加常见，是否应该被列为例外呢？

`【】` 比其他括号更常见，能展开描述一下么？

根据 GB/T 15834—2011 的描述和范例——

- 方括号 `［］`、六角括号 `〔〕` 的使用场景常见于：
  - 学术文献——例如在参考文献列表中标注国籍、朝代、出版物类型；
  - 公文/合同——例如文件编号中的年份；
  - 多层括号嵌套时，优化括号的配对（与 `（）` 嵌套使用时，提高视觉区分度）。
- 方头括号 `【】` 的使用场景常见于：
  - 新闻报道开头的格式化标记；
  - 辞书类文献的词条标记。

就使用场景来看，方头括号可能更贴近大众阅读，其他两组括号在专业类文献或公文/法律写作场景中更多见。但两类场景重要性难以区分高下，并且这三组括号在一定程度上可以互换使用，似乎不能判断哪一组更为「例外」？

**Comment by xfq** [comment]
根据[会议讨论](https://www.w3.org/2023/05/30-clreq-minutes.html#t11)，删除了“These brackets and quotation marks are rarely used in Chinese publications”。
