### ISSUE TITLE
note about SC/TC character equivalences

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#54]
http://w3c.github.io/clreq/#characters_used_in_chinese_composition
http://w3c.github.io/clreq/zh/#characters_used_in_chinese_composition

the second note in this section is no longer in the zh version. Angel and i feel that it is useful information for non-Chinese audience. Should we reinstate it in the zh version?

**Comment by VirgilMing** [comment]
I strongly agree. This pseudo common sense is not emphasized in Simplified Chinese so there's a good chance that a Chinese reader doesn't know it.

**Comment by ryukeikun** [comment]
We had a discussion and delete it in zh version as such a note is the contents of Chinese Etymology/philology more than LAYOUT Requirement. 

Since it is small note, I don't mind if you would llike to add it back.
