### ISSUE TITLE
翻译 Help wanted!

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#544]
README.md 里添加了一个新的小节，叫“Help wanted!”，需将其内容翻译成中文。

**Comment by realfish** [comment]
试译：

> ## 求助！
> 我们正在征集当前书写系统的相关信息。详询请点该链接：[中文书写系统](https://github.com/w3c/clreq/issues?q=is%3Aissue+is%3Aopen+label%3A%E5%95%8F%E9%A1%8C/question)。

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/commit/7ec58b234db4cb7996c7e50718b858b730ab36ba
