### ISSUE TITLE
关于基本版式和格子

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#556]
https://w3c.github.io/clreq/#n005

> 在文章仅由汉字构成的状况下，行首、行尾对齐版心边界是中文书排版重要的原则。但在与西文混排、或配置标点禁则处理时，为遵从本项原则，内文可不按照格子排列。

有两个问题：

1. 「行首、行尾对齐版心边界」和「按照格子排列」应该是不同的两件事，这里有点混为一谈的感觉；
2. 在什么情况下内文可不按照格子排列？希望这里说得更清楚一些。比如说，在行首对齐和两端对齐时都会出现吗？

**Comment by realfish** [comment]
> 1. 「行首、行尾对齐版心边界」和「按照格子排列」应该是不同的两件事，这里有点混为一谈的感觉；

「对齐版心边界」和「按照格子排列」是两个并行的规则。引文中第一句话，在描述「对齐版心边界」这个规则。引文中的第二句话，应该是基于另外一个前提——「其格子设定于中文排版原则下，内文必须依照格子进行配置」——所做的补充说明。

我个人的感觉是，行文整体上逻辑没有特别大的冲突。但由于措辞上没有明显的连词来表达逻辑、承转的关系，同时语句顺序有点随机，所以可能跳跃阅读/选读时，会出现轻微的理解障碍。

**Comment by ryukeikun** [comment]
我个人觉得这段话写得逻辑比较混乱。即使「文章仅由汉字构成的状况下」，内容也可能会因为避头尾等因素而无法「按照格子排列」。这段话似乎是按照「纵横对齐、不做避头尾」的思维模式而写的，建议删除。

**Comment by bobbytung** [comment]
這一段改成

基本版式設定步驟不僅是在頁面中設定一個長方形空間，還需要為內文、標題、圖片配置等做出一個基礎的格子設定。

於中文排版原則下，內文逐格進行配置，而得以對齊行首與行尾。

但與西文混排、或配置標點禁則處理，內文可不按照格子排列；但仍須遵守對齊行首行尾的原則。
