### ISSUE TITLE
「底端」与「顶端」

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#577]
术语表中的「底端」的英文是foot side，但是正文中使用了under、foot end、underneath、below等多种翻译，希望能够统一。

同样，术语表中的「顶端」的英文是head side，但是正文中使用了right side（直排时）和above的翻译。

**Comment by ethantw** [comment]
由於中文排版涉及直、橫排，以上下左右來表示文本方向會導致描述過於冗長混亂，我們在CLReq中引入了「底端」「顶端」同時還有「始端」「末端」一共四個與文本方向相關的邏輯詞彙。

另外「寬度」和「高度」的定義在CLReq中皆屬邏輯上的度量（如字寬、行高等），與常識中的概念不完全相同，在 #472 中有相應討論。

過去的行文中可能會有相互混淆的歷史問題，應統一在一個PR中一并調整中英文文本。同時應注意未來涉及相關概念的新文本需符合相應的定義。

根據詞彙表，四個方向的定義為，

始端 starting point
> 文本或文字靠近該行行首的一端。通常，文字直排時始端在上，橫排在左。

末端 end point
> 文本或文字靠近其所在行行尾的一端。通常，文字直排時末端在下，橫排在右。

頂端 head side
> 文本或文字靠近版面近起始的一端。通常，文字直排時頂端在右，橫排在上。

底端 foot side
> 文本或文字靠近版面結尾的一端。通常，文字直排時底端在左，橫排在下。


cc: @ryukeikun @eisoch

**Comment by xfq** [comment]
CSS标准中也有表示逻辑尺寸和方向的图：https://www.w3.org/TR/2018/WD-css-logical-1-20180827/#mapping-diagram

**Comment by xfq** [comment]
和Richard讨论之后，他的建议：

-----

始端：starting point -> start point

如果是一段文字，建议使用range start。如果是一行文字，可以使用line start。

-----

末端：end point

如果是一段文字，建议使用range end。如果是一行文字，可以使用line end。

-----

頂端和底端：

side隐含有左右两侧的意思，Richard认为head side和foot side不好，建议考虑：

* 对于行：line head or line foot
* 对于字符：character head or character foot
* 对于一段文字：range head or range foot

他说这些词不完美，但比现在的用词稍自然一点。

**Comment by xfq** [comment]
综合12月14日例会讨论意见：

* 弃用「始端」和「末端」两个术语（见 #589 和 #590 ）
* 使用line head和line foot表示「顶端」和「底端」
* 使用line start和line end表示「行首」和「行尾」
