### ISSUE TITLE
line gap definition

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#58]
http://w3c.github.io/clreq/#considerations_in_designing_type_area
http://w3c.github.io/clreq/zh/#considerations_in_designing_type_area

I think bullet 4 should start with an explanation of what 'line gap' means, particularly since it's not immediately obvious that this is not the same as the line height/line feed/leading. I propose the following replacement text for the paragraph:

"A &lt;dfn id="def_line-gap">line gap&lt;/dfn> is the smallest amount of space between adjacent lines. The line gaps between each line should be the same throughout the book, except for special cases."

In the third note, i thnk the term 'line-height' should be in a dfn tag. (I added this in the en version.)

**Comment by realfish** [comment]
The “line-gap” here seems to be mapped to “行與行之間的空白（行距）”. It nearly refers to the stripe of lead between two lines which was used in the hand-typestting days.

**Comment by bobbytung** [comment]
It's fine to replace 'line-gap' with 'line-height' here.

**Comment by r12a** [comment]
but in some parts of the text 'line gap' is contrasted with 'line height'.  @ethantw when you pull together the definitions for the glossary, could you treat defintions of line gap and line height as a priority? I think a key enabler for this discussion is to clearly define what each of those terms mean.  Only then can we move forward with our understanding of the rules associated with them.

**Comment by ethantw** [comment]
OK :ok_hand:

**Comment by bobbytung** [comment]
merge to #78
