### ISSUE TITLE
楷体和仿宋体的使用场景

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#593]
https://www.w3.org/TR/clreq/#commonly_used_chinese_typefaces

> 楷体普遍用于公文书、教科书。台湾的公文书多全文使用楷体。

> 仿宋体常用于文艺作品和古籍，而中国大陆则规定政府公文原则上应使用仿宋体。

这里主要是指纸质出版物，还是也包括网页、电子书和Web应用？

**Comment by shizhao** [comment]
这说的是纸质书

Fuqiao Xue ***@***.***> 于 2024年1月16日周二 11:45写道：

**Comment by ryukeikun** [comment]
按照原文撰写意图，是指纸质出版物。但，正是由于目前并没有很好的机制调用楷体与仿宋，导致网页、电子书与 web 应用上缺乏实例。所以这是「先有蛋、还是先有鸡」的问题。

正如[2024 年 6 月的编辑会议](https://www.w3.org/2024/05/29-clreq-minutes.html)所讨论，作为需求文档，我们只需说明在纸质时候很重要，意即在电子环境里本应有同样需求即可，因此文档本身没有问题，无需修改。
