### ISSUE TITLE
简体中文中的括号

### ISSUE THREAD

**Issue by upsuper** [w3c/clreq#6]
3.1.1.2 括号

在简体中文中括号的类型似乎还是比较丰富的，GB/T 15834-2011 里面除了圆括号以外还列举了方括号（［］）、六角括号（〔〕）、方头括号（【】）三种。见该标准 4.9.3.2-4.9.3.5。或许应该考虑添加进去。

**Comment by bobbytung** [comment]
這裏應該是從TCL改寫成CL時的疏漏。
3.1.1.2中引號內的

> NOTE
> 其餘引號類如：[【](LEFT BLACK LENTICULAR BRACKET)、[】](RIGHT BLACK LENTICULAR BRACKET)、[〖](LEFT WHITE LENTICULAR BRACKET)[〗](RIGHT WHITE LENTICULAR BRACKET)、[〔](LEFT TORTOISE SHELL BRACKET)、[〕](RIGHT TORTOISE SHELL BRACKET)、[［](FULLWIDTH LEFT SQUARE BRACKET)、[］](FULLWIDTH RIGHT SQUARE BRACKET)、[｛](FULLWIDTH LEFT CURLY BRACKET)、[｝](FULLWIDTH RIGHT CURLY BRACKET)，則較少使用於中文書籍。
- [x] 應移至括号之下
- [x] 將文中引號改為括号
- [x] 刪除最末「則較少使用於中文書籍」。
- [x] 附錄A標點符號表也修改為括号類
