### ISSUE TITLE
indication punctuation marks?

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#60]
http://w3c.github.io/clreq/#indication_punctuation_marks
http://w3c.github.io/clreq/zh/#generatedID-4

where did we get the term 'indication punctuation marks'?

'indicator' seems a more likely word than 'indication' in this context.

Bringhurst refers to parentheses as 'phrase markers'. Is that a better candidate?

(i will fix the generated frag id)

**Comment by realfish** [comment]
In Chinese, “标点符号” is the combination of “标号” and “点号”. In the GB/T 15834—2011, “标点符号” translates as “punctuation”, while I haven't found the translation of “标号” or “点号”.

In the narrow sense, “点号” means dots (_punctus_) while “标号” means the other marks of punctuation.

Also, the “点号” may inherit the concept from “句读”.
