### ISSUE TITLE
additional explanation for Parentheses section

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#61]
http://w3c.github.io/clreq/#indication_punctuation_marks
http://w3c.github.io/clreq/zh/#generatedID-4

in bullet 2 Parentheses, Angel has expanded the text to be more explanatory to non-Chinese readers. Is the text ok? Should we also beef up the chinese version?

**Comment by VirgilMing** [comment]
~~I'd say it's more "including" than "also called."~~ Including it in Chinese version is a good idea.
Wait.. I was wrong.

**Comment by r12a** [comment]
i'm not sure i understand the previous comment
