### ISSUE TITLE
term "Connection symbols"

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#62]
Did this term come from a particular source?  If not, i'd like to translate it as 'connector symbols'.

**Comment by realfish** [comment]
Instead of the action of “connecting”, I advice to use the term “dash marks” or “middle line marks” to focus on the shapes of these marks.

**Comment by bobbytung** [comment]
It's translated from "[連接號](http://www.edu.tw/FILES/SITE_CONTENT/M0001/HAU/h15.htm)". I'm ok with 'connector symbols'. In Taiwan we do not have official translation for punctuations. I will send first English draft to the ministry for review after published.

**Comment by ethantw** [comment]
Both ‘dash marks’ and ‘connector symbols’ look good to me. I would prefer the first one more though. It conveys the relations to ‘en dash’ in English.

**Comment by ryukeikun** [comment]
Personally, I prefer “dash marks” but it how about “破折号”？On functional side, 破折号 works more like “em dash” while 连接号 works more like “en dash” and hyphen, it does’t fit any current English punctuation, so maybe using Dash Mark for 破折号，and using Connector Mark – better use “mark” than “symbol”?

**Comment by ethantw** [comment]
Agree!
- 破折号：dash mark
- 連接號：connector mark
