### ISSUE TITLE
Restructure clreq per standardised headings

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#629]
The suggestion was made to consider reorganising the clreq content to fit around the standardised headings used for the Script Resources and Gap Analysis, etc. documents.  Such reorganisations have been applied to Arabic, Mongolian, and Tibetan layout requirements, and will be applied to the Korean and Ethiopic layout requirements.

Using this new structure has benefits such as:
1. making it easier to maintain links from the Chinese Script Resources and other documents.
2. pointing up places in the content where typographic features are not yet described
3. making it easier for people familiar with other layout requirements information (eg. developers and implementers) to find their way around the Chinese content.

For the latest proposed changes see https://w3c.github.io/clreq/indexNEW.html

**Comment by r12a** [comment]
After adding a number of edits this morning, i have now posted an ED of a draft proposal. See the link above.  Some polishing is probably needed, and comments would be appreciated.

There is currently no content in clreq for a number of the standard headings.  I left most of the headings in place so that we can decide what to do about it.  Broadly, there are 3 options:
1. Remove this section until we have some content to add to it.  (The disadvantage of this is that we lose sight of gaps that should probably be eventually filled.)
2. Write up some information for these sections.
3. Leave this as a placeholder for future reference with the text TBD. (Which reminds us that we need to supply additional information.)

A couple of the standard sections are removed already, since they don't apply to Chinese.  These are Cursive Text, and Case & Other Character Transforms.

Some section headings were not added, nor were stubs created.  These include: Grids & Tables; Footnotes, Endnotes, Etc; and Page Headers, Footers, etc.

The Forms & User Interaction section was moved out from under Page & Book Layout, per request from the group — but there's no content for it yet.

**Comment by xfq** [comment]
Thanks, Richard.

> There is currently no content in clreq for a number of the standard headings. I left most of the headings in place so that we can decide what to do about it. Broadly, there are 3 options:
> 
> 1. Remove this section until we have some content to add to it.  (The disadvantage of this is that we lose sight of gaps that should probably be eventually filled.)
> 2. Write up some information for these sections.
> 3. Leave this as a placeholder for future reference with the text TBD. (Which reminds us that we need to supply additional information.)

Another option is to create issues about these sections to remind us to write related content in the future. We have a [new section](https://github.com/w3c/clreq/labels/%E6%96%B0%E5%A2%9E%E7%AB%A0%E7%AF%80%2Fnew%20section) label for that.

**Comment by xfq** [comment]
Trying to translate the section titles:

### Text direction 文本方向

* Writing mode 行文模式
* Bidirectional text 双向文本

### Glyph shaping & positioning 字形的变形与定位

* Fonts &amp; font styles 字型与字型样式
* Context-based shaping &amp; positioning 基于上下文的字形变形与定位
* Cursive text 连写文本
* Letterform slopes, weights, &amp; italics 斜体、字重与意大利体
* Case &amp; other transforms 大小写与其他变换

### Typographic units 排版单元

* Characters &amp; encoding 字符（字元）与编码
* Grapheme/word segmentation &amp; selection 字素、词语的分割与选择

### Punctuation & other inline features 标点符号与其他行内特性

* Phrase &amp; section boundaries 短语与章节边界
* Quotations &amp; citations 引文
* Emphasis &amp; highlighting 强调与突出显示
* Abbreviation, ellipsis, &amp; repetition 缩写、省略与重复
* Inline notes &amp; annotations 行内注与行间注
* Text decoration &amp; other inline features 文本标示与其他行内特性
* Data formats &amp; numbers 数据格式与数字

### Line & paragraph layout 行与段落版式

* Line breaking &amp; hyphenation 换行与断词连字
* Text alignment &amp; justification 文本对齐
* Text spacing 文本的间距调整
* Baselines, line height, etc. 基线、行高等
* Lists, counters, etc. 列表、计数器等
* Styling initials 首字样式

### Page & book layout 页面与书籍版式

* General page layout &amp; progression 基本页面版式与装订方向
* Grids &amp; tables 网格与表格
* Footnotes, endnotes, etc. 脚注、尾注等
* Page headers, footers, etc. 页眉、页脚等
* Forms &amp; user interaction 表单与用户交互

Feedback is welcome.

**Comment by xfq** [comment]
Related clreq discussions:

* https://www.w3.org/2024/08/07-clreq-minutes.html#t02
* https://www.w3.org/2024/09/11-clreq-minutes.html#t01
* https://www.w3.org/2024/10/16-clreq-minutes.html#74ea
* https://www.w3.org/2024/11/13-clreq-minutes.html#5618
* https://www.w3.org/2024/12/18-clreq-minutes.html#3d8e

-----

Related jlreq discussions:

* https://github.com/w3c/jlreq/discussions/441
* https://github.com/w3c/jlreq-d/discussions/62#discussioncomment-10332328

**Comment by r12a** [comment]
Reading the minutes, it seems like it would be useful for me to attend the next telecon to answer questions.

In the meantime, here are some pointers that may help.

1. The organisation of material is driven by _function_ rather than appearance/techniques used, ie. what message the author is attempting to convey, rather than how they do it.  So, for example, underlining of text may be described under Text Emphasis for many languages, but belongs under Quotations & Citations when we are dealing with book title underlines in Chinese. This, for example, is why some of the punctuation related information is split into different sections – what the author is trying to achieve is more more important in determining the organisation of material than the fact that these are all punctuation marks.
2. I agreed to separate out the Interaction section from Page & Book Layout because i considered it a tweak that doesn't significantly change the order or segmentation of the data.  In general, however, the headings listed in https://github.com/w3c/clreq/issues/629#issuecomment-2270501142 are the things that provide harmonisation and consistency with all the other materials in the lreq framework.  Changing them breaks that link and reduces the benefits of adopting the standard toc.  On the other hand, the content and subsections within those sections can be whatever is preferred, and are the things that are likely to change from language to language when this template is used.
3. I developed the headings in this template over many years while developing a standard approach to describe 90 different orthographies from all around the world.  The focus on the content author's intention, rather than the techniques used, helps to ensure that the template fits well for all of those orthographies. Using the standard template across these orthographies makes it easy to find and compare information across those very different orthographies.

Btw, i fixed the sectioning bug so that baselines, lists, and initials now all fall under Line & Paragraph Layout, as they should.

**Comment by xfq** [comment]
> Reading the minutes, it seems like it would be useful for me to attend the next telecon to answer questions.

I will invite you to attend the [teleconference](https://www.w3.org/events/meetings/10830a38-3b37-4659-adc8-6c2fab86e38d/) this Wednesday.

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/clreq/commit/0196c14400eee3f2d177f6c96b518bb90632795f and https://github.com/w3c/clreq/commit/e7bde6172d1488bd3c1d5965a6dc4c272c7258b0
