### ISSUE TITLE
TWO-EM DASH

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#63]
http://w3c.github.io/clreq/#unbreakable_marks_punctuation
http://w3c.github.io/clreq/zh/#generatedID-7

in bullet 1 Em dash and long dash, it mentions two adjacent em dashes.  I wondered whether U+2E3A TWO-EM DASH [⸺] is used for the long dash.

**Comment by realfish** [comment]
The best practice of the “破折号” is the ligature of two EM DASH `U+2014`, since there is rare typeface/font that contains the glyph of `U+2E3A`. To be honest, I can only tell the Source Han Sans.

**Comment by bobbytung** [comment]
Practically as @realfish said, we used two EM Dash with ligature in ebooks.
@ethantw 's description "視作一個字元存在，不得以適配分行之由拆至二行" that means should not be separated to two lines more than one code point.

**Comment by ethantw** [comment]
I believe the use of `U+2014` is sort of a workaround (hack) before we can popularise `U+2E3A`. We should list both of them.

**Comment by r12a** [comment]
Could someone please edit the chinese text to refer to U+2E3A, and provide a translation?

**Comment by ethantw** [comment]
@r12a, done. :yum:
