### ISSUE TITLE
为什么文档自身没有遵循“横排的中、西文混排配置”原则？

### ISSUE THREAD

**Issue by gotounix** [w3c/clreq#631]
如 https://www.w3.org/International/clreq/#mixed_text_composition_in_horizontal_writing_mode 所述：

![image](https://github.com/user-attachments/assets/d0bf2772-2480-47d9-a88e-93c7113cb501)

可是文档自身全文并没有采用这个原则：

![image](https://github.com/user-attachments/assets/bd699904-351c-489f-a1b6-db8ff301601e)

是为何？

**Comment by xfq** [comment]
你指的是中西文之间的空白？`text-autospace`的[默认值](https://www.w3.org/TR/css-text-4/#valdef-text-autospace-normal)是有中西文之间的空白的，等浏览器实现之后，文档也会有中西文之间的空白。另见 https://github.com/w3c/clreq/issues/14 。

-----

如果没有其他问题，我会在下周关闭本issue。
