### ISSUE TITLE
names for numerals

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#64]
http://w3c.github.io/clreq/#composition_of_chinese_and_western_mixed_text
http://w3c.github.io/clreq/zh/#composition_of_chinese_and_western_mixed_text

Referring to digits 0..9 as arabic numbers is not very clear, since the differently-shaped numbers used in Arabic text are often referred to also as arabic numerals.  The Unicode Consortium has already grappled with this terminology and i propose we adopt their solution: 
call 0..9 european numbers
call ٠..٩ (used in arabic text) arabic-indic numbers, and
call ०..९ (used in hindi text) indian numbers.

Thus for the first note in 3.2.1 i propose to use the following translation:
"Western numerals, sometimes called arabic, or arabic-indic numerals, are referred to as European numerals in the context of this document, unless notes indicate otherwise."

**Comment by bobbytung** [comment]
agreed.

**Comment by ethantw** [comment]
👍
