### ISSUE TITLE
description of grid alignment

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#65]
http://w3c.github.io/clreq/#handling_of_grid_alignment_in_chinese_and_western_mixed_text_composition
http://w3c.github.io/clreq/zh/#handling_of_grid_alignment_in_chinese_and_western_mixed_text_composition

i propose to translate the following
由於漢字各字等寬的性質，無論在直排或橫排的情況下，除了行齊頭尾對齊外，亦求各行間的各個漢字能夠縱橫對齊。

as
Due to the fact that each Han character is of the same width, not only should characters at the start and end of a line be aligned but it is also a requirement for characters within blocks of Han text to be aligned both vertically and horizontally, whether in vertical or horizontal writing mode.

is that ok?

**Comment by realfish** [comment]
I advice to refer to the “type area” concept (see at 2.3.2), like the “kihon-hanmen” in _JLReq_, to interpret the concept of “縱橫對齊”.

The “縱橫對齊” literally means every character (Han character and Chinese full-width punctuation) should snap to a specific character frame of the kihon-hanmen preferentially.

**Comment by bobbytung** [comment]
I think that "characters at the start and end of a line be aligned" is a must. And characters in grid is quite hard because punctuations prohibition rules and Latin words in propositional typeface. But we tried to make it possible.

**Comment by r12a** [comment]
I can't actually read the Chinese, so specific comments on how/if i need to change the english text would be helpful.

**Comment by ethantw** [comment]
Maybe we can use a new invented term such as ‘grid alignment’ advised by @r12a, and give it a definition in the glossary (not only should characters at the start and end of a line be aligned but it is also a requirement for characters within blocks of Han text to be aligned both vertically and horizontally)?
