### ISSUE TITLE
ruby or interlinear annotation?

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#66]
http://w3c.github.io/clreq/#usage_of_interlinear_annotations
http://w3c.github.io/clreq/zh/#usage_of_interlinear_annotations

this currently says
Chinese ruby, also known as interlinear annotation, ...

should it say instead
Interlinear annotation, also known as ruby, ....

and should we replace the use of 'ruby' with 'interlinear annotation' throughout the document.  I think there was some prior discussion around this, but i'm not clear on the outcome.

**Comment by ethantw** [comment]
> should it say instead
> Interlinear annotation, also known as ruby, ....

Yes, we have decided to use ‘interlinear annotation(s)’ over ruby in most cases. The only exception might be when referring to the ruby section of JLReq.

**Comment by r12a** [comment]
ok, i'll implement that then. Thanks.

**Comment by r12a** [comment]
done.
