### ISSUE TITLE
other parts section

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#67]
http://w3c.github.io/clreq/#other_parts no longer exists in the zh version. Should we drop it from the en version too, or reinstate it in the zh version?

**Comment by ethantw** [comment]
Totally. We should omit this section.

**Comment by ryukeikun** [comment]
Agree

**Comment by r12a** [comment]
section removed https://github.com/w3c/clreq/commit/31b93210b566021033ff1addf81643768a7a0071
