### ISSUE TITLE
meaning of 新五號四行＝36pt

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#69]
section 2.3.5 reads:
【请问在两岸这是通用的做法吗？还是各自不同？】中文活字尺寸以「號」為單 位，又分新舊兩種寸法。可完整對應美制的「點」（point），分別如下：初 號＝42pt、一號＝27.5pt、二號＝21pt、三號＝15.75pt、四號＝13.75pt、五 號＝10.5pt、六號＝7.875pt、七號＝5.25pt。新五號四行＝36pt、新一 號＝24pt、新二號＝18pt、新三號字＝16pt、新四號＝12pt、新五號＝9pt。 

here is my version

There are two traditional size systems for Chinese characters, and old one and a new one. The following shows the equivalence in the Western point system. In the Old size system, Size 0 = 42pt, Size 1 = 27.5pt, Size 2 = 21pt, Size 3 = 15.75pt, Size 4 = 13.75pt, Size 5 = 10.5pt, Size 6 = 7.875pt, and Size 7 = 5.25pt; while 4 lines of New Size 5 is 36pt, New Size 1 = 24pt, New Size 2 = 18pt, New Size 3 = 16pt, New Size 4 = 12pt, New Size 5 is 9pt.

i didn't understand the bit that says "4 lines of New Size 5 is 36pt". Should this be New Size 0 = 36pt?  The english appears to be a direct translation of the chinese...

**Comment by lianqi** [comment]
when I translated this, my best guess was  that New Size 5 (9pt) X 4 = 36pt...
but I don't quite understand why it has to be 4 lines

**Comment by realfish** [comment]
“新五號四行”, also known as “小初号” / “新初号” in SC, may translate as “New Size 0” for better consistency.

**Comment by hax** [comment]
“新五号四行”就是“新初号”。称为“五号四行”恐怕是强调传统排版以五号字作为排版基准。即老初号（42pt）为老五号（10.5pt）的四倍，而新五号是9pt，故新初号为36pt。
参考此文：http://blog.justfont.com/2013/01/rixing-on-typography/

**Comment by bobbytung** [comment]
replace 「新五號四行」 to 「新初號」，that means 「4 lines of New Size 5」 to 「New Size 0」.
