### ISSUE TITLE
「直排時旋轉90度」 改成「依文字書寫方向標注」

### ISSUE THREAD

**Issue by siusin** [w3c/clreq#7]
from @ethantw 
[[
「5.1 附錄Ａ 中文標點符號表」有個欄位的標題是：

> 直排時旋轉90度（是∕否）

原先的描述過於「橫排本位」，我希望改成「依文字書寫方向標注」（依文字書寫方向使用相應的標注方向）。
]]

**Comment by bobbytung** [comment]
我認為保留較佳，主要因為兩份相關的文件：
- [CSS Writing Modes Level 3](http://dev.w3.org/csswg/css-writing-modes-3/#intro-text-layout)
- [UTR#50](http://unicode.org/reports/tr50/)
  都有相關的敘述。

改成「依文字書寫方向標注」，反而不容易對應。而這個表格的目的就是快速參照使用。

**Comment by ethantw** [comment]
How about 依文字書寫方向標注（直排時順時針旋轉90度）?

可以斷作二行，括注的內容也可以改用`small`元素。

**Comment by bobbytung** [comment]
避免誤解。這表格功能重於表意，若內文敘述要修改我沒意見，但這表格我希望讀者能迅速理解。

**Comment by ethantw** [comment]
理解。但原欄位標題還是改成「直排時**順時針**旋轉90度」較好。

**Comment by bobbytung** [comment]
順時針ok，感謝。
