### ISSUE TITLE
Hei and Kai description

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#70]
the former description (at least in english) in the doc was:

"<dfn id="en_def_hei">Hei</dfn>, also known as Heiti or Gothic, is a type style characterized by strokes of even thickness, reduced curves, and a lack of decoration. It is commonly used in headlines, signs, and personal names in dialogs. For certain types of text, characters in Kai style with thicker strokes typically indicate emphasis."

the current text says:

"<dfn id="en_def_hei">Hei</dfn>, is commonly used in headlines, signs, and personal names in dialogs. For certain types of text, characters in Kai style with thicker strokes typically indicate emphasis."

I liked the additional explanations. Can we add them back?

Same for Kai:

"<dfn id="en_def-kai">Kai</dfn>, also known as Kaiti or regular script, is another of the major typefaces, and provides calligraphic styles for Chinese characters. It is also the most easily and widely recognized style and shows notable handwriting features."

has become:

"<dfn id="en_def-kai">Kai</dfn>, is another of the major typefaces, and shows notable handwriting features."

Was there a reason for reducing the information here?

**Comment by ethantw** [comment]
I forgot the reason why we omitted these description in the first place. I am okay with adding them back in both zh and en versions.

**Comment by ryukeikun** [comment]
Agree!

**Comment by r12a** [comment]
so someone needs to do this?  I would just do it myself, but i can't change the chinese :(

should i put in the english above and mark the chinese equivalents as needing attention?
