### ISSUE TITLE
建议在规范前言里写明中文用户的反馈通道

### ISSUE THREAD

**Issue by upsuper** [w3c/clreq#8]
理论上大多数文档的初期都应该是使用行内注解的方式来管理 issue 的？那种情况下通常使用邮件列表来接受反馈。因为本文档应当需要接受中文用户的反馈，因此如果使用邮件列表的话，应该写明一个使用中文的邮件列表，比如 public-zhreq 等，而不是写英文的 public-i18n-cjk。

另外考虑到邮件列表的使用在中文用户群或许不是很广泛，或许也可以考虑将此 GitHub 或者甚至相应的 Hackpad 链接写入文档。我不是很确定 W3C 在这方面的规定。不过或许使用邮件列表管理而不是 GitHub 仍然是一种合适的方式。

**Comment by kennyluck** [comment]
考虑到 `public-zhreq` 也[没有这么多人在用](https://lists.w3.org/Archives/Public/public-zhreq/)，考虑直接放 `public-html-ig-zh` 吧，这么多年来小组累计的订阅人数还是比较多的。

GitHub 链接 + 1。

**Comment by siusin** [comment]
Agree. 

@r12a offered the same advice just now.

public-zhreq 有部分不重合的人（出版界的），还是留着吧。收到重复邮件的话多多包涵。

**Comment by siusin** [comment]
Done.

Thx.
