### ISSUE TITLE
绪论部分，简体中文版本发现文字缺失。

### ISSUE THREAD

**Issue by rambolee** [w3c/clreq#80]
> 1.2 Purpose of this document 目的 本文書之目的
> 
> Each cultural community has its own language, script and writing system. The transfer of each writing system into cyberspace is a task with very high importance for information and communication technology.
> 
> 每一个文化群体都拥有独自的语言、文字、书写系统。对文化资产的承继而言，将个别书写系统在**虚空间**再现，是信息传播技术的重要责任。
> 
> 每一個文化群體都擁有獨自的語言、文字、書寫系統。將個別書寫系統得以在**虛擬空間**再現，對文化資產的承繼而言，是資訊傳播技術的重要責任。

简体部分：虚空间
繁体部分：虛擬空間

**Comment by ryukeikun** [comment]
Typo fixed.
