### ISSUE TITLE
Unify the Hant/Hans/original text

### ISSUE THREAD

**Issue by ethantw** [w3c/clreq#84]
Chaps in CLReq,

Hello. Currently the translated Simplified Chinese part is not identical with the original text, which may result in inconvenience to sort out and edit the document in the future. I think that we should work on some principals to follow and unify the Hant/Hans part within our workflow.

What I have in mind list below. Feel free to provide more suggestions.
1. We shall not change any single character unless the intention is to switch to its corresponding Hant/Hans form.
2. We shall not add or omit any single character, unless the original text is changed.
3. We shall not change any term unless it is listed in the Hant/Hans column in the glossary.
4. Principal 3. can be ignored while such term has a corresponding Hant/Hans form found in dictionaries. For example, 文件 in the original text can be replaced with 文档 in Hans part although it is not listed in the glossary.
5. We shall not modify the orders of words, clauses or sentences, unless the original text is changed.

Please let me know if you think this is feasible. Thanks.

**Comment by r12a** [comment]
hi Ethan,

for clarification, when you say 'the original text', i assume you mean the text marked as lang=zh? 

i agree that it will be useful to ensure that terms used are those in the glossary, and that new terms get a new glossary entry

i'm not qualified to comment on the variations in syntax and character usage in chinese.
