### ISSUE TITLE
直排時的標點符號 引號

### ISSUE THREAD

**Issue by c933103** [w3c/clreq#85]
我記得是會用﹁﹂和﹃﹄的。要不要也寫進去？

**Comment by bobbytung** [comment]
一般而言不建議直接指定（U+FE41﹁PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET）這類的符號。而是透過瀏覽器等來自動取代為該字碼。故在此不列出。

**Comment by bobbytung** [comment]
Add note in 3.1.1.2 to describe.

There are vertical blacket codepoints such like U+FE41 PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET in Unicode. But they are not suitable for author to use directly. They should be replaced by other mechanism.

万国码编码中有如U+FE41 PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET等直立的符号，但不适宜作者直接使用该符号，而是透过其他机制替代使用。

萬國碼編碼中有如U+FE41 PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET等直立的符號，但不適宜作者直接使用該符號，而是透過其他機制替代使用。
