### ISSUE TITLE
Some expression issues discussion

### ISSUE THREAD

**Issue by paincompiler** [w3c/clreq#87]
- In 「中文排版有别于其它版本」, 「体系」(like the [Traditional-Chinese version](https://github.com/w3c/clreq/blob/gh-pages/index.html#L126)) may be better than「版本」.  [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L126)
- 「我们非常感谢来自不同语言文化背景的编辑和合作者对本文档的贡献，以及他们跨越文化差异共同致力完善本文档的美好愿景」 in short will be 「感谢......贡献，以及......愿景」, I don't think 「感谢」 and 「愿景」 go together. [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L169) and [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L170)
- Chinese versions here, which are following the English syntactic construction, are a little crappy don't you think? I'd like to rephrase that to 「对中文排版与其在《<a href="http://www.w3.org/TR/jlreq/">日文排版规范</a>》中相关内容的相同与差异之处作出说明」. [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L201)
- A little redundant here 「减少字与字间的字距」, does it mean 「字间距」? Or just rephrase it to 「字与字间的距离」.[Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L371) and [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L372)
- Two issues in sentence 「决定版心除了在页面中设定长方形的空间外，也有着供内文、标题、图片配置做为基准的格子设定」: ([Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L551) and [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L552))
  - The subject of sentence 「决定版心除了在页面中设定长方形的空间外」 is following the general English syntax, which will be better if using 「版心的决定」 as subject. 
  - 「也有着」 seems too oral, will 「也包含」 be better?

**Comment by ryukeikun** [comment]
> In 「中文排版有别于其它版本」, 「体系」(like the Traditional-Chinese version) may be better than「版本」

changed into 「書寫體系」to match English text.

> 「我们非常感谢来自不同语言文化背景的编辑和合作者对本文档的贡献，以及他们跨越文化差异共同致力完善本文档的美好愿景」 in short will be 「感谢......贡献，以及......愿景」, I don't think 「感谢」 and 「愿景」 go together. 

rewrote as 「我們感謝來自不同語言文化背景的編輯們和合作者們對本文檔的貢獻，並對他們跨越文化差異、共同致力完善本文檔的美好願景表示欽佩。」

> Chinese versions here, which are following the English syntactic construction, are a little crappy don't you think? I'd like to rephrase that to 「对中文排版与其在《日文排版规范》中相关内容的相同与差异之处作出说明」

Rewrote.

> A little redundant here 「减少字与字间的字距」, does it mean 「字间距」? Or just rephrase it to 「字与字间的距离」

Changed into「字距」。

> Two issues in sentence 「决定版心除了在页面中设定长方形的空间外，也有着供内文、标题、图片配置做为基准的格子设定」

Rewrote as「版心設定步驟不僅是在頁面中設定一個長方形空間，還需要為內文、標題、圖片配置等做出一個基礎的格子設定。」

**Comment by hax** [comment]
“美好愿景”这句总感觉不通顺……

**Comment by ryukeikun** [comment]
可能是因为按照繁体中文习惯行文的缘故吧，但是在语法上是通顺的，我觉得问题不大。
