### ISSUE TITLE
Some layout issues discussion

### ISSUE THREAD

**Issue by paincompiler** [w3c/clreq#88]
- Wrong list order of Traditional Chinese version and Simplified Chinese version of [楷体](https://github.com/w3c/clreq/blob/gh-pages/index.html#L434) and [黑体](https://github.com/w3c/clreq/blob/gh-pages/index.html#L456) in [中文排版常用字体](https://github.com/w3c/clreq/blob/gh-pages/index.html#L394).
- A blank among words. [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L506)
- Wrong comma in sentence 「中文的文字书写方向,分为直排与横排」which should be 「，」. [Here](https://github.com/w3c/clreq/blob/gh-pages/index.html#L776)

Updated at 2015.9.12 18:50

**Comment by ryukeikun** [comment]
> Wrong list order of Traditional Chinese version and Simplified Chinese version of 楷体 and 黑体 in 中文排版常用字体.

I don’t think it is wrong. These 4 items are not even placed by frequency orders.

> A blank among words.

Deleted.

> Wrong comma in sentence 「中文的文字书写方向,分为直排与横排」which should be 「，」

This comma is even not needed, so I just delete it.

**Comment by paincompiler** [comment]
> Wrong list order of Traditional Chinese version and Simplified Chinese version of 楷体 and 黑体 in 中文排版常用字体.

这里是我表述不清，我是指这三项字体介绍的内容中，不是按照「英文、简体中文、繁体中文」的顺序排列的，与文档其他部分不统一。

**Comment by paincompiler** [comment]
> Wrong list order of Traditional Chinese version and Simplified Chinese version of 楷体 and 黑体 in 中文排版常用字体.

这里是我表述不清，我是指这三项字体介绍的内容中，不是按照「英文、简体中文、繁体中文」的顺序排列的，与文档其他部分不统一。
