### ISSUE TITLE
Some advice of the document

### ISSUE THREAD

**Issue by DingJunyao** [w3c/clreq#89]
Some words and translation of some words in different places of China is different. The document didn't pay attention to it.
Some grammar in simplified and traditional Chinese is different, too. e.g. ,the"之" using between two words in traditional Chinese is often written as "的" in simplified Chinese. 
And the mixture of different (kinds of) languages seems too terrible, though I can understand both simplified and traditional Chinese. 
In my opinion, the document should have three separated versions at least: The Simplified Chinese, The Traditional Chinese and English.

**Comment by DingJunyao** [comment]
Sorry, what I saw is an earlier version of the document.

**Comment by ethantw** [comment]
Thanks for the advice. We have been working on these already. Please feel free to report other issues in the future.
