### ISSUE TITLE
对于千呼万唤始出来的《中文排版规范》

### ISSUE THREAD

**Issue by jornakbobo** [w3c/clreq#9]
今天在很特殊的情况下，知道了W3C发布了《中文排版规范》！作为一枚码农，好奇的查看了W3C的源代码。不过第一眼我就看到个问题，列表用的都是ul，规范里说的ol呢，dl呢？你tm是闹哪样啊？我亲爱的W3C君.......

**Comment by bobbytung** [comment]
這是第一份編輯發布的草稿，內文格式待後期慢慢細修，連內容都沒寫完呢。
