### ISSUE TITLE
Baselines Calculation for mixture of Hans & Western

### ISSUE THREAD

**Issue by siusin** [w3c/clreq#92]
![2015-10-30 094622](https://cloud.githubusercontent.com/assets/5643782/10835975/964bfcac-7eeb-11e5-8fa3-7247852270f2.jpg)

Details followed.

**Comment by bobbytung** [comment]
這是在2015年CSS WG上討論的問題。
就現在數位字體排版時，會因為字體設計的差異造成Baseline偏高或者偏低，所以希望CSS能有如InDesign等排版軟體的機制能夠對中西混排時，字體的Baseline進行調整對齊。
但對中文排版而言，我們沒有辦法給出一套標準的做法，所以這是實務上的需求，但在CLREQ裡不能給出明確的說明與指引。
