### ISSUE TITLE
⁇ ‼ 是否需要列在中文標點符號表

### ISSUE THREAD

**Issue by audreyt** [w3c/clreq#94]
在 GB/T 15834-2011 和 《重訂標點符號手冊》都未見 ⁇ (U+2047) ‼ (U+0203C) ，而且目前的字形也未必都把它們造成 1x1 grid，請問可以加上出處嗎？尤其直排時，是否有具體的用例？感謝 :rainbow:

**Comment by audreyt** [comment]
#51

**Comment by audreyt** [comment]
GB15834 的 5.1.2 裡說的是「三個 ? / ! 連寫時，需要排版成兩個漢字的寬度」，以 @bobbytung 的說明而言，目前技術上尚無法實作，而 2047/0203C 只是 compatible composition form，這樣的話我可以接受。

**Comment by bobbytung** [comment]
merge to #51

**Comment by lianqi** [comment]
to be merged with#51
