### ISSUE TITLE
请将该文档本身遵照规则修改

### ISSUE THREAD

**Issue by yw80** [w3c/clreq#95]
例如，规则中有一条：
3.2.2 横排的中、西文混排配置 橫排的中、西文混排配置
橫排時，西文使用比例字體；阿拉伯數字則常用比例字體或等寬字體。原則上，漢字與西文字母、數字間使用四分之一個漢字寬的字距或空白。但西文出現在行頭或行尾時，則毋須加入空白。
或可使用西文詞間空格（U+0020 SPACE [ ]，其寬度隨不同字體有所變化）。

但是该文档并没有遵循这个规则。例如首页：
http://w3c.github.io/clreq/zh/
随处可见中英混排的情况，都没有加空格。

请将该文档本身遵照规则修改。

**Comment by upsuper** [comment]
See #14
